.\" $File: file.man,v 1.150 2023/05/21 17:08:34 christos Exp $
.Dd May 21, 2023
.Dt FILE 1
.Os
.Sh ИМЯ
.Nm file
.Nd определение типа файла
.Sh СИНТАКСИС
.Nm
.Bk -words
.Op Fl bcdEhiklLNnprsSvzZ0
.Op Fl Fl apple
.Op Fl Fl exclude-quiet
.Op Fl Fl extension
.Op Fl Fl mime-encoding
.Op Fl Fl mime-type
.Op Fl e Ar testname
.Op Fl F Ar separator
.Op Fl f Ar namefile
.Op Fl m Ar magicfiles
.Op Fl P Ar name=value
.Ar
.Ek
.Nm
.Fl C
.Op Fl m Ar magicfiles
.Nm
.Op Fl Fl help
.Sh ОПИСАНИЕ
Эта справочная страница описывает версию 5.45 команды
.Nm .
.Pp
.Nm
проверяет каждый аргумент, пытаясь классифицировать его.
Существует три набора тестов, выполняемых в следующем порядке:
тесты файловой системы, магические тесты и языковые тесты.
Первый успешный тест приводит к печати типа файла.
.Pp
Выводимый тип обычно будет содержать одно из слов
.Em text
(файл содержит только печатные символы и несколько распространённых
управляющих символов и, вероятно, безопасен для чтения на
.Dv ASCII
терминале),
.Em executable
(файл содержит результат компиляции программы
в форме, понятной некоторому ядру
.Tn UNIX
или другой),
или
.Em data
что означает всё остальное (данные обычно являются
.Dq двоичными
или непечатаемыми).
Исключениями являются известные форматы файлов (файлы ядра, tar-архивы),
которые, как известно, содержат двоичные данные.
При изменении магических файлов или самой программы убедитесь, что
эти ключевые слова сохранены.
Пользователи полагаются на то, что все читаемые файлы в каталоге
имеют слово
.Dq text
в выводе.
Не делайте так, как сделали в Беркли, и не меняйте
.Dq shell commands text
на
.Dq shell script .
.Pp
Тесты файловой системы основаны на проверке возвращаемого значения
системного вызова
.Xr stat 2 .
Программа проверяет, является ли файл пустым
или каким-либо специальным файлом.
Любые известные типы файлов, соответствующие вашей системе
(сокеты, символические ссылки или именованные каналы (FIFO) в системах, где они реализованы)
определяются, если они определены в системном заголовочном файле
.In sys/stat.h .
.Pp
Магические тесты используются для проверки файлов с данными в
определённых фиксированных форматах.
Каноническим примером этого является двоичный исполняемый файл (скомпилированная программа)
.Dv a.out ,
формат которого определён в
.In elf.h ,
.In a.out.h
и, возможно,
.In exec.h
в стандартном каталоге заголовочных файлов.
Эти файлы имеют
.Dq магическое число ,
хранящееся в определённом месте
ближе к началу файла, которое сообщает операционной системе
.Tn UNIX ,
что файл является двоичным исполняемым файлом, и какого именно типа.
Концепция
.Dq магического числа
была по расширению применена к файлам данных.
Любой файл с некоторым инвариантным идентификатором по небольшому фиксированному
смещению внутри файла обычно может быть описан таким образом.
Информация, идентифицирующая эти файлы, читается из /etc/magic
и скомпилированного
магического файла
.Pa /usr/share/misc/magic.mgc ,
или файлов в каталоге
.Pa /usr/share/misc/magic ,
если скомпилированный файл не существует.
Кроме того, если
.Pa $HOME/.magic.mgc
или
.Pa $HOME/.magic
существуют, они будут использоваться вместо системных магических файлов.
.Pp
Если файл не соответствует ни одной записи в магическом файле,
он проверяется, чтобы увидеть, похож ли он на текстовый файл.
Наборы символов ASCII, ISO-8859-x, не-ISO 8-битные расширенные ASCII
(такие как используемые в системах Macintosh и IBM PC),
Unicode в кодировке UTF-8, Unicode в кодировке UTF-16 и EBCDIC
можно различить по разным диапазонам и последовательностям байтов,
которые составляют печатаемый текст в каждом наборе.
Если файл проходит любой из этих тестов, сообщается его набор символов.
Файлы ASCII, ISO-8859-x, UTF-8 и расширенные ASCII идентифицируются
как
.Dq text ,
потому что они в основном читаемы на почти любом терминале;
UTF-16 и EBCDIC являются только
.Dq символьными данными ,
потому что, хотя
они содержат текст, этот текст требует преобразования
перед чтением.
Кроме того,
.Nm
попытается определить другие характеристики текстовых файлов.
Если строки файла завершаются CR, CRLF или NEL, вместо
стандартного для Unix LF, это будет отмечено.
Файлы, содержащие управляющие последовательности или перепечатку,
также будут идентифицированы.
.Pp
После того как
.Nm
определил набор символов, используемый в текстовом файле,
он попытается определить, на каком языке написан файл.
Языковые тесты ищут определённые строки (см.
.In names.h ),
которые могут появляться в любом месте первых нескольких блоков файла.
Например, ключевое слово
.Em .br
указывает, что файл, скорее всего, является входным файлом
.Xr troff 1 ,
так же как ключевое слово
.Em struct
указывает на программу на C.
Эти тесты менее надёжны, чем предыдущие
две группы, поэтому они выполняются последними.
Подпрограммы языковых тестов также проверяют некоторые прочие вещи
(такие как
.Xr tar 1
архивы, файлы JSON).
.Pp
Любой файл, который не может быть идентифицирован как написанный
в любом из перечисленных выше наборов символов, просто считается
.Dq data .
.Sh ПАРАМЕТРЫ
.Bl -tag -width indent
.It Fl Fl apple
Заставляет команду
.Nm
выводить тип файла и код создателя, как
используется в старых версиях MacOS.
Код состоит из восьми букв,
первая описывает тип файла, вторая — создателя.
Эта опция работает корректно только для форматов файлов, для которых
определён вывод в стиле apple.
.It Fl b , Fl Fl brief
Не добавлять имена файлов к строкам вывода (краткий режим).
.It Fl C , Fl Fl compile
Записать выходной файл
.Pa magic.mgc ,
содержащий предварительно разобранную версию магического файла или каталога.
.It Fl c , Fl Fl checking-printout
Вывести проверочную распечатку разобранной формы магического файла.
Обычно используется в сочетании с опцией
.Fl m
для отладки нового магического файла перед его установкой.
.It Fl d
Выводит внутреннюю отладочную информацию в stderr.
.It Fl E
При ошибках файловой системы (файл не найден и т.п.), вместо обработки ошибки
как обычного вывода, как требует POSIX, и продолжения, выдать сообщение об ошибке
и завершить работу.
.It Fl e , Fl Fl exclude Ar testname
Исключить тест с именем
.Ar testname
из списка тестов, используемых для определения типа файла.
Допустимые имена тестов:
.Bl -tag -width compress
.It apptype
Тип приложения
.Dv EMX
(только на EMX).
.It ascii
Различные типы текстовых файлов (этот тест попытается угадать кодировку
текста, независимо от настройки опции
.Sq encoding ).
.It encoding
Различные кодировки текста для мягких магических тестов.
.It tokens
Игнорируется для обратной совместимости.
.It cdf
Выводит подробности составных файлов документов.
.It compress
Проверяет сжатые файлы и заглядывает внутрь них.
.It csv
Проверяет файлы с разделителями-запятыми.
.It elf
Выводит подробности ELF-файлов, при условии, что включены мягкие магические тесты и
найдена магия elf.
.It json
Исследует файлы JSON (RFC-7159) путём их разбора на соответствие.
.It soft
Использует магические файлы.
.It simh
Исследует ленточные файлы SIMH.
.It tar
Исследует tar-файлы путём проверки контрольной суммы 512-байтового заголовка tar.
Исключение этого теста может дать более детальное описание содержимого, используя
метод мягкой магии.
.It text
Синоним для
.Sq ascii .
.El
.It Fl Fl exclude-quiet
Как
.Fl Fl exclude ,
но игнорирует тесты, которые
.Nm
не знает.
Предназначено для совместимости со старыми версиями
.Nm .
.It Fl Fl extension
Вывести разделённый слэшами список допустимых расширений для найденного типа файла.
.It Fl F , Fl Fl separator Ar separator
Использовать указанную строку в качестве разделителя между именем файла и
результатом определения файла.
По умолчанию
.Sq \&: .
.It Fl f , Fl Fl files-from Ar namefile
Читать имена файлов для проверки из
.Ar namefile
(по одному в строке)
перед списком аргументов.
Должен присутствовать либо
.Ar namefile ,
либо хотя бы один аргумент с именем файла;
для проверки стандартного ввода используйте
.Sq -
в качестве аргумента имени файла.
Обратите внимание, что
.Ar namefile
раскрывается, и имена файлов в нём обрабатываются, когда эта опция
встречается, и до того, как будет выполнена дальнейшая обработка параметров.
Это позволяет обрабатывать несколько списков файлов с разными аргументами командной строки
в одном вызове
.Nm .
Таким образом, если вы хотите установить разделитель, вам нужно сделать это до того, как вы укажете
список файлов, например:
.Dq Fl F Ar @ Fl f Ar namefile ,
вместо:
.Dq Fl f Ar namefile Fl F Ar @ .
.It Fl h , Fl Fl no-dereference
Эта опция предписывает не переходить по символьным ссылкам
(в системах, поддерживающих символические ссылки).
Это значение по умолчанию, если переменная окружения
.Dv POSIXLY_CORRECT
не определена.
.It Fl i , Fl Fl mime
Заставляет команду
.Nm
выводить строки типа MIME вместо более
традиционных человекочитаемых.
Таким образом, она может сказать
.Sq text/plain; charset=us-ascii
вместо
.Dq ASCII text .
.It Fl Fl mime-type , Fl Fl mime-encoding
Как
.Fl i ,
но выводить только указанный элемент(ы).
.It Fl k , Fl Fl keep-going
Не останавливаться на первом совпадении, продолжать.
К последующим совпадениям будет
добавлена строка
.Sq "\[rs]012\- "
в начале.
(Если вы хотите новую строку, см. опцию
.Fl r .)
Шаблон магии с наибольшей силой (см. опцию
.Fl l
) идёт первым.
.It Fl l , Fl Fl list
Показывает список шаблонов и их силу, отсортированный по убыванию
силы
.Xr magic 5 ,
которая используется для сопоставления (см. также опцию
.Fl k ).
.It Fl L , Fl Fl dereference
Эта опция предписывает переходить по символьным ссылкам, как одноимённая опция в
.Xr ls 1
(в системах, поддерживающих символические ссылки).
Это значение по умолчанию, если переменная окружения
.Ev POSIXLY_CORRECT
определена.
.It Fl m , Fl Fl magic-file Ar magicfiles
Указать альтернативный список файлов и каталогов, содержащих магию.
Это может быть один элемент или список, разделённый двоеточиями.
Если скомпилированный магический файл найден рядом с файлом или каталогом,
он будет использован вместо него.
.It Fl N , Fl Fl no-pad
Не дополнять имена файлов пробелами для выравнивания в выводе.
.It Fl n , Fl Fl no-buffer
Принудительно сбрасывать stdout после проверки каждого файла.
Это полезно только при проверке списка файлов.
Предназначено для использования программами, которые хотят получать вывод типа файла из канала.
.It Fl p , Fl Fl preserve-date
В системах, поддерживающих
.Xr utime 3
или
.Xr utimes 2 ,
пытаться сохранить время доступа к анализируемым файлам, чтобы создать видимость, что
.Nm
никогда не читал их.
.It Fl P , Fl Fl parameter Ar name=value
Установить различные ограничения параметров.
.Bl -column "elf_phnum" "Default" "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
.It Sy "Имя" Ta Sy "По умолчанию" Ta Sy "Пояснение"
.It Li bytes Ta 1M Ta максимальное количество байт для чтения из файла
.It Li elf_notes Ta 256 Ta максимальное количество обработанных ELF-заметок
.It Li elf_phnum Ta 2K Ta максимальное количество обработанных ELF-программных секций
.It Li elf_shnum Ta 32K Ta максимальное количество обработанных ELF-секций
.It Li elf_shsize Ta 128MB Ta максимальный размер обработанной ELF-секции
.It Li encoding Ta 65K Ta максимальное количество байт для определения кодировки
.It Li indir Ta 50 Ta ограничение рекурсии для косвенной магии
.It Li name Ta 50 Ta ограничение счётчика использования для магии name/use
.It Li regex Ta 8K Ta ограничение длины для поиска по регулярным выражениям
.El
.It Fl r , Fl Fl raw
Не преобразовывать непечатаемые символы в \eooo.
Обычно
.Nm
преобразует непечатаемые символы в их восьмеричное представление.
.It Fl s , Fl Fl special-files
Обычно
.Nm
пытается только читать и определять тип файлов аргументов, которые
.Xr stat 2
сообщает как обычные файлы.
Это предотвращает проблемы, поскольку чтение специальных файлов может иметь
неожиданные последствия.
Указание опции
.Fl s
заставляет
.Nm
также читать файлы аргументов, которые являются блочными или символьными специальными файлами.
Это полезно для определения типов файловых систем данных в необработанных
разделах диска, которые являются блочными специальными файлами.
Эта опция также заставляет
.Nm
игнорировать размер файла, сообщаемый
.Xr stat 2 ,
поскольку в некоторых системах он сообщает нулевой размер для необработанных разделов диска.
.It Fl S , Fl Fl no-sandbox
В системах, где доступен libseccomp
.Pa ( https://github.com/seccomp/libseccomp ),
опция
.Fl S
отключает изоляцию, которая включена по умолчанию.
Эта опция необходима для
.Nm
для выполнения внешних программ распаковки,
т.е. когда указана опция
.Fl z
и встроенные распаковщики недоступны.
В системах, где изоляция недоступна, эта опция не имеет эффекта.
.Pp
.Em Примечание:
Эта версия file для Debian собрана без поддержки seccomp, поэтому эта опция
не имеет эффекта.
.It Fl v , Fl Fl version
Вывести версию программы и выйти.
.It Fl z , Fl Fl uncompress
Попытаться заглянуть внутрь сжатых файлов.
.It Fl Z , Fl Fl uncompress-noreport
Попытаться заглянуть внутрь сжатых файлов, но сообщать информацию только о содержимом,
а не о сжатии.
.It Fl 0 , Fl Fl print0
Выводить нулевой символ
.Sq \e0
после окончания имени файла.
Удобно для
.Xr cut 1
вывода.
Это не влияет на разделитель, который всё равно печатается.
.Pp
Если эта опция повторяется более одного раза,
.Nm
выводит только имя файла, за которым следует NUL, затем описание
(или текст ERROR:) и затем второй NUL для каждой записи.
.It Fl -help
Вывести справочное сообщение и выйти.
.El
.Sh ПЕРЕМЕННЫЕ ОКРУЖЕНИЯ
Переменная окружения
.Ev MAGIC
может использоваться для задания имени магического файла по умолчанию.
Если эта переменная установлена, то
.Nm
не будет пытаться открыть
.Pa $HOME/.magic .
.Nm
добавляет
.Dq Pa .mgc
к значению этой переменной, если это необходимо.
Переменная окружения
.Ev POSIXLY_CORRECT
управляет (в системах, поддерживающих символические ссылки) тем,
будет ли
.Nm
пытаться переходить по символьным ссылкам или нет.
Если она установлена, то
.Nm
переходит по символьным ссылкам, в противном случае — нет.
Это также управляется опциями
.Fl L
и
.Fl h .
.Sh ФАЙЛЫ
.Bl -tag -width /usr/share/misc/magic.mgc -compact
.It Pa /usr/share/misc/magic.mgc
Скомпилированный список магии по умолчанию.
.It Pa /usr/share/misc/magic
Каталог, содержащий магические файлы по умолчанию.
.El
.Sh КОД ВЫХОДА
.Nm
завершится с кодом
.Dv 0 ,
если операция выполнена успешно, или
.Dv >0 ,
если произошла ошибка.
Следующие ошибки вызывают диагностические сообщения, но не влияют на код
выхода программы (как требует POSIX), если не указана опция
.Fl E :
.Bl -bullet -compact -offset indent
.It
Файл не найден
.It
Нет разрешения на чтение файла
.It
Тип файла не может быть определён
.El
.Sh ПРИМЕРЫ
.Bd -literal -offset indent
$ file file.c file /dev/{wd0a,hda}
file.c:	  C program text
file:	  ELF 32-bit LSB executable, Intel 80386, version 1 (SYSV),
	  dynamically linked (uses shared libs), stripped
/dev/wd0a: block special (0/0)
/dev/hda: block special (3/0)

$ file -s /dev/wd0{b,d}
/dev/wd0b: data
/dev/wd0d: x86 boot sector

$ file -s /dev/hda{,1,2,3,4,5,6,7,8,9,10}
/dev/hda:   x86 boot sector
/dev/hda1:  Linux/i386 ext2 filesystem
/dev/hda2:  x86 boot sector
/dev/hda3:  x86 boot sector, extended partition table
/dev/hda4:  Linux/i386 ext2 filesystem
/dev/hda5:  Linux/i386 swap file
/dev/hda6:  Linux/i386 swap file
/dev/hda7:  Linux/i386 swap file
/dev/hda8:  Linux/i386 swap file
/dev/hda9:  empty
/dev/hda10: empty

$ file -i file.c file /dev/{wd0a,hda}
file.c:	     text/x-c
file:	     application/x-executable
/dev/hda:    application/x-not-regular-file
/dev/wd0a:   application/x-not-regular-file

.Ed
.Sh СМ. ТАКЖЕ
.Xr hexdump 1 ,
.Xr od 1 ,
.Xr strings 1 ,
.Xr magic 5
.Sh СООТВЕТСТВИЕ СТАНДАРТАМ
Считается, что эта программа превосходит определение System V Interface
Definition of FILE(CMD), насколько можно судить по нечёткому языку,
содержащемуся в нём.
Её поведение в основном совместимо с программой System V с тем же именем.
Однако эта версия знает больше магии, поэтому она будет выдавать
другой (хотя и более точный) вывод во многих случаях.
.\" URL: http://www.opengroup.org/onlinepubs/009695399/utilities/file.html
.Pp
Одно существенное различие
между этой версией и System V
состоит в том, что эта версия рассматривает любой пробельный символ
как разделитель, поэтому пробелы в строках шаблонов должны экранироваться.
Например,
.Bd -literal -offset indent
\*[Gt]10	string	language impress\	(imPRESS data)
.Ed
.Pp
в существующем магическом файле должно быть изменено на
.Bd -literal -offset indent
\*[Gt]10	string	language\e impress	(imPRESS data)
.Ed
.Pp
Кроме того, в этой версии, если строка шаблона содержит обратную косую черту,
она должна быть экранирована.
Например
.Bd -literal -offset indent
0	string		\ebegindata	Andrew Toolkit document
.Ed
.Pp
в существующем магическом файле должно быть изменено на
.Bd -literal -offset indent
0	string		\e\ebegindata	Andrew Toolkit document
.Ed
.Pp
Релизы SunOS 3.2 и новее от Sun Microsystems включают команду
.Nm ,
производную от System V, но с некоторыми расширениями.
Эта версия отличается от Sun's только в мелочах.
Она включает расширение оператора
.Sq \*[Am]
, используемого, например,
.Bd -literal -offset indent
\*[Gt]16	long\*[Am]0x7fffffff	\*[Gt]0		not stripped
.Ed
.Sh БЕЗОПАСНОСТЬ
В системах, где доступен libseccomp
.Pa ( https://github.com/seccomp/libseccomp ),
.Nm
обеспечивает ограничение системных вызовов только теми, которые необходимы для
работы программы.
Это ограничение не обеспечивает никаких преимуществ в безопасности, когда
.Nm
запрашивается распаковка входных файлов с запуском внешних программ с
опцией
.Fl z .
Чтобы разрешить выполнение внешних распаковщиков, необходимо отключить
изоляцию с помощью опции
.Fl S .
.Sh КАТАЛОГ МАГИИ
Записи магического файла собраны из различных источников,
в основном USENET, и предоставлены различными авторами.
Кристос Зулас (адрес ниже) будет собирать дополнительные
или исправленные записи магического файла.
Объединение записей магического файла
будет распространяться периодически.
.Pp
Порядок записей в магическом файле важен.
В зависимости от того, какую систему вы используете, порядок,
в котором они объединены, может быть неправильным.
.Sh ИСТОРИЯ
Команда
.Nm
существовала в каждой
.Dv UNIX
по крайней мере с Research Version 4
(страница руководства датирована ноябрём 1973 года).
Версия System V представила одно важное крупное изменение:
внешний список магических типов.
Это немного замедлило работу программы, но сделало её гораздо более гибкой.
.Pp
Эта программа, основанная на версии System V,
была написана Яном Дарвином
.Aq ian@darwinsys.com
без просмотра чьего-либо исходного кода.
.Pp
Джон Гилмор значительно переработал код, сделав его лучше,
чем первая версия.
Джефф Коллиер нашёл несколько недостатков
и предоставил некоторые записи магического файла.
Вклад оператора
.Sq \*[Am]
от Роба МакМахона,
.Aq cudcv@warwick.ac.uk ,
1989.
.Pp
Гай Харрис,
.Aq guy@netapp.com ,
внёс множество изменений с 1993 года по настоящее время.
.Pp
Основная разработка и сопровождение с 1990 года по настоящее время
Кристосом Зуласом
.Aq christos@astron.com .
.Pp
Изменено Крисом Лоутом
.Aq chris@lowth.com ,
2000: добавлена обработка опции
.Fl i
для вывода строк типа mime с использованием альтернативного
магического файла и внутренней логики.
.Pp
Изменено Эриком Фишером
.Aq enf@pobox.com ,
июль 2000,
для идентификации кодировок и попытки идентификации языков
не-ASCII файлов.
.Pp
Изменено Рубеном Томасом
.Aq rrt@sc3d.org ,
2007-2011, для улучшения поддержки MIME, объединения MIME и не-MIME магии,
поддержки каталогов, а также файлов магии, применения множества исправлений ошибок,
обновления и исправления большого количества магии, улучшения системы сборки, улучшения
документации и переписывания привязок Python на чистом Python.
.Pp
Список участников в каталоге
.Sq magic
(магические файлы)
слишком длинный, чтобы включать его сюда.
Вы знаете, кто вы; спасибо.
Многие участники перечислены в исходных файлах.
.Sh ЮРИДИЧЕСКОЕ УВЕДОМЛЕНИЕ
Copyright (c) Ian F. Darwin, Toronto, Canada, 1986-1999.
Охраняется стандартной лицензией Berkeley Software Distribution; см. файл
COPYING в дистрибутиве исходных кодов.
.Pp
Файлы
.Pa tar.h
и
.Pa is_tar.c
были написаны Джоном Гилмором из его общедоступной
программы
.Xr tar 1
и не охватываются вышеуказанной лицензией.
.Sh ОШИБКИ
Пожалуйста, сообщайте об ошибках и отправляйте исправления в трекер ошибок по адресу
.Pa https://bugs.astron.com/
или в список рассылки
.Aq file@astron.com
(посетите
.Pa https://mailman.astron.com/mailman/listinfo/file
сначала для подписки).
.Sh ПЛАНИРУЕМЫЕ УЛУЧШЕНИЯ
Исправить вывод так, чтобы тесты для флагов MIME и APPLE не требовались
повсеместно, а фактический вывод выполнялся только в одном месте.
Это требует проектирования.
Предложение: помещать возможные выводы в список, затем выбирать
последнее помещённое (наиболее конкретное, как надеются) значение в конце, или
использовать значение по умолчанию, если список пуст.
Это не должно замедлять вычисление.
.Pp
Обработка
.Dv MAGIC_CONTINUE
и печать \e012- между записями громоздка и сложна; провести рефакторинг
и централизовать.
.Pp
Некоторая логика кодирования жёстко закодирована в encoding.c и может быть перенесена
в магические файлы, если бы у нас была аннотация !:charset.
.Pp
Продолжать устранять все ошибки магии.
См. Debian BTS как хороший источник.
.Pp
Хранить строки произвольной длины, например для шаблонов %s, чтобы
их можно было выводить.
Исправляет ошибку Debian #271672.
Это можно сделать, выделяя строки в пуле строк, сохраняя
пул строк в конце магического файла и преобразуя все указатели
строк в относительные смещения от пула строк.
.Pp
Добавить синтаксис для относительных смещений после текущего уровня (ошибка Debian #466037).
.Pp
Сделать так, чтобы file -ki работал, т.е. выдавал несколько типов MIME.
.Pp
Добавить библиотеку zip, чтобы можно было заглядывать внутрь документов Office2007 для
вывода более подробной информации об их содержимом.
.Pp
Добавить опцию для вывода URL-адресов источников описаний файлов.
.Pp
Объединить поиск сценариев и добавить способ сопоставления имён исполняемых файлов с типами
MIME (например, иметь магическое значение !:mime, которое вызывает поиск
результирующей строки в таблице).
Это позволит избежать добавления одной и той же магии повторно для каждого нового
интерпретатора hash-bang.
.Pp
Когда доступен файловый дескриптор, мы можем пропускать и корректировать буфер
вместо того взломанного управления буфером, которое мы делаем сейчас.
.Pp
Исправить
.Dq name
и
.Dq use
для проверки согласованности во время компиляции (дублирование
.Dq name ,
.Dq use
указывающее на неопределённое
.Dq name
).
Сделать
.Dq name
/
.Dq use
более эффективным, поддерживая отсортированный список имён.
Особым случаем сделать ^ для переключения порядка байтов в парсере, чтобы его не
пришлось экранировать, и задокументировать это.
.Pp
Если смещения, указанные внутри файла, превышают размер буфера
(
.Dv HOWMANY
в файле file.h), то мы не ищем это смещение, а сдаёмся.
Было бы лучше, если бы управление буфером выполнялось, когда файловый дескриптор
доступен, чтобы мы могли искать по файлу.
Однако нужно быть осторожным, потому что это влияет на производительность и, следовательно,
на безопасность, поскольку можно замедлить работу, многократно выполняя поиск.
.Pp
Сейчас есть поддержка ведения отдельных буферов и смещений от
конца файла, но внутреннее управление буфером всё ещё требует
капитального ремонта.
.Sh ДОСТУПНОСТЬ
Вы можете получить последнюю версию оригинального автора по анонимному FTP
на
.Pa ftp.astron.com
в каталоге
.Pa /pub/file/file-X.YZ.tar.gz .
