'\" t
.TH FIND 1 \" -*- nroff -*-
.SH ИМЯ
find \- поиск файлов в иерархии каталогов
.SH СИНТАКСИС
.B find
[\-H] [\-L] [\-P] [\-D debugopts] [\-Olevel] [starting-point...\&] [expression]
.
.SH ОПИСАНИЕ
Эта man-страница
документирует версию
.BR find ,
входящую в состав GNU.
GNU
.B find
осуществляет поиск в дереве каталогов, начиная с каждой указанной отправной точки, путем вычисления заданного выражения слева направо в соответствии с правилами приоритета (см. раздел ОПЕРАТОРЫ) до тех пор, пока результат не станет известен (левая часть ложна для операций \fIи\fR, истинна для
.IR или ),
после чего
.B find
переходит к следующему имени файла. Если отправная точка не указана, предполагается `.\&'.
.PP
Если вы используете
.B find
в среде, где важна безопасность (например, при поиске в каталогах, доступных для записи другим пользователям), вам следует прочитать главу «Вопросы безопасности» в документации findutils, которая называется \fBFinding Files\fP и поставляется вместе с findutils.
Этот документ также содержит гораздо больше подробностей и обсуждений, чем данная man-страница, поэтому он может оказаться более полезным источником информации.
.
.SH ПАРАМЕТРЫ
Параметры
.BR \-H ,
.B \-L
и
.B \-P
управляют обработкой символических ссылок. Аргументы командной строки, следующие за ними, считаются именами файлов или каталогов, подлежащих проверке, вплоть до первого аргумента, начинающегося с `\-', или аргумента `(' или `!'. Этот аргумент и все последующие аргументы считаются выражением, описывающим то, что нужно найти. Если пути не указаны, используется текущий каталог. Если выражение не указано, используется выражение
.B \-print
(однако вам, вероятно, стоит рассмотреть использование
.B \-print0
вместо него).
.PP
В этой man-странице обсуждаются «параметры» внутри списка выражений.
Эти параметры управляют поведением
.B find ,
но указываются сразу после последнего имени пути. Пять «настоящих» параметров
.BR \-H ,
.BR \-L ,
.BR \-P ,
.B  \-D
и
.B  \-O
должны стоять перед первым именем пути, если они вообще используются. Двойное тире
.B \-\-
теоретически можно использовать для обозначения того, что все оставшиеся аргументы не являются параметрами, но это не работает должным образом из-за того, как
.B find
определяет конец последующих аргументов пути: он делает это путем чтения до тех пор, пока не встретит аргумент выражения (который также начинается с `-').
Теперь, если аргумент пути будет начинаться с `-', то
.B find
вместо этого воспримет его как аргумент выражения.
Таким образом, чтобы гарантировать, что все начальные точки будут восприняты как таковые, и особенно чтобы предотвратить ошибочную обработку шаблонов подстановки, развернутых вызывающей оболочкой, как аргументов выражений, обычно безопаснее добавлять к шаблонам или сомнительным именам путей `./' или использовать абсолютные пути, начинающиеся с '/'.
.IP \-P
Никогда не переходить по символическим ссылкам. Это поведение по умолчанию. Когда
.B find
проверяет или выводит информацию о файлах, и файл является символической ссылкой, используемая информация берется из свойств самой символической ссылки.

.IP \-L
Переходить по символическим ссылкам. Когда
.B find
проверяет или выводит информацию о файлах, используемая информация берется из свойств файла, на который указывает ссылка, а не из самой ссылки (за исключением случаев, когда это битая символическая ссылка или
.B find
не может проверить файл, на который указывает ссылка). Использование этого параметра подразумевает
.BR \-noleaf .
Если вы позже используете параметр
.B \-P
,
.B \-noleaf
все равно останется в силе. Если
.B \-L
активен и
.B find
обнаруживает символическую ссылку на подкаталог во время поиска, будет выполнен поиск в подкаталоге, на который указывает символическая ссылка.
.IP
Когда параметр
.B \-L
активен, предикат
.B \-type
всегда будет сравнивать тип файла, на который указывает символическая ссылка, а не саму ссылку (если только символическая ссылка не является битой). Действия, которые могут привести к нарушению символических ссылок во время выполнения
.B find
(например,
.BR \-delete ),
могут привести к запутанному поведению.
Использование
.B \-L
приводит к тому, что предикаты
.B \-lname
и
.B \-ilname
всегда возвращают false.

.IP \-H
Не переходить по символическим ссылкам, за исключением случаев обработки аргументов командной строки. Когда
.B find
проверяет или выводит информацию о файлах, используемая информация берется из свойств самой символической ссылки.
Единственное исключение из этого поведения — когда файл, указанный в командной строке, является символической ссылкой и ссылка может быть разрешена.
В этой ситуации используемая информация берется из того, на что указывает ссылка (то есть ссылка разыменовывается).
Информация о самой ссылке используется в качестве запасного варианта, если файл, на который указывает символическая ссылка, не может быть проверен.
Если
.B \-H
активен и один из путей, указанных в командной строке, является символической ссылкой на каталог, будет исследовано содержимое этого каталога (хотя, конечно,
.B \-maxdepth\ 0
предотвратит это).
.P
Если указано более одного параметра из
.BR \-H ,
.B \-L
и
.B \-P
, каждый из них переопределяет остальные; в силу вступает последний, указанный в командной строке.
Поскольку это поведение по умолчанию, параметр
.B \-P
следует считать активным, если не указан ни
.B \-H
, ни
.B \-L
.

GNU
.B find
часто опрашивает файлы (stat) во время обработки самой командной строки, до начала какого-либо поиска. Эти параметры также влияют на то, как обрабатываются эти аргументы. В частности, существует ряд тестов, которые сравнивают файлы, перечисленные в командной строке, с файлом, который мы рассматриваем в данный момент. В каждом случае файл, указанный в командной строке, будет проверен, и некоторые его свойства будут сохранены. Если названный файл на самом деле является символической ссылкой и активен параметр
.B \-P
(или если не были указаны ни
.B \-H
, ни
.B \-L
), информация, используемая для сравнения, будет взята из свойств символической ссылки. В противном случае она будет взята из свойств файла, на который указывает ссылка. Если
.B find
не может перейти по ссылке (например, из-за недостаточных прав или если ссылка указывает на несуществующий файл), будут использованы свойства самой ссылки.
.P
Когда активны параметры
.B \-H
 или
.B \-L
, любые символические ссылки, указанные в качестве аргумента
.B \-newer
, будут разыменованы, и временная метка будет взята из файла, на который указывает символическая ссылка. То же самое относится к
.BR \-newerXY ,
.B \-anewer
и
.BR \-cnewer .

Параметр
.B \-follow
оказывает влияние, аналогичное
.BR \-L ,
хотя он вступает в силу в той точке, где он появляется (то есть, если
.B \-L
не используется, но
.B \-follow
используется, любые символические ссылки, появляющиеся после
.B \-follow
в командной строке, будут разыменованы, а те, что до него — нет).

.IP "\-D debugopts"
Вывести диагностическую информацию; это может быть полезно для диагностики проблем, почему
.B find
делает не то, что вы хотите. Список параметров отладки должен быть разделен запятыми. Совместимость параметров отладки не гарантируется между выпусками findutils. Полный список допустимых параметров отладки см. в выводе
.BR "find \-D\ help" .
Допустимые параметры отладки включают:
.RS
.IP exec
Показывать диагностическую информацию, относящуюся к \-exec, \-execdir, \-ok и \-okdir.
.IP opt
Выводит диагностическую информацию, относящуюся к оптимизации дерева выражений; см. параметр \-O.
.IP rates
Выводит сводку, показывающую, как часто каждый предикат завершался успехом или неудачей.
.IP search
Подробная навигация по дереву каталогов.
.IP stat
Выводить сообщения при проверке файлов с помощью системных вызовов
.B stat
и
.B lstat
. Программа
.B find
старается минимизировать такие вызовы.
.IP tree
Показать дерево выражений в его исходном и оптимизированном виде.
.IP all
Включить все остальные параметры отладки (но не
.BR help ).
.IP help
Объяснить параметры отладки.
.RE
.IP \-Olevel
Включает оптимизацию запросов.
Программа
.B find
переупорядочивает тесты для ускорения выполнения, сохраняя при этом общий эффект; то есть предикаты с побочными эффектами не переупорядочиваются относительно друг друга. Оптимизации, выполняемые на каждом уровне оптимизации, следующие:
.RS
.IP 0
Эквивалентно уровню оптимизации 1.
.IP 1
Это уровень оптимизации по умолчанию, соответствующий традиционному поведению. Выражения переупорядочиваются так, чтобы тесты, основанные только на именах файлов (например,
.B \-name
и
.BR \-regex ),
выполнялись первыми.
.IP 2
Любые тесты
.B \-type
или
.B \-xtype
выполняются после любых тестов, основанных только на именах файлов, но перед любыми тестами, требующими информации из inode. Во многих современных версиях Unix типы файлов возвращаются функцией
.B readdir()
, поэтому эти предикаты вычисляются быстрее, чем предикаты, которым нужно сначала получить stat файла.
Если вы используете предикат
.B "\-fstype\ \fIFOO\fR"
и указываете тип файловой системы
.I FOO
, который не известен (то есть отсутствует в `/etc/mtab') на момент запуска
.B find
, этот предикат эквивалентен
.BR \-false .
.IP 3
На этом уровне оптимизации включен полный оптимизатор запросов, основанный на стоимости. Порядок тестов изменяется так, чтобы дешевые (т.е. быстрые) тесты выполнялись первыми, а более дорогие — позже, если это необходимо. Внутри каждой ценовой группы предикаты оцениваются раньше или позже в зависимости от того, велика ли вероятность их успеха. Для
.BR \-o ,
предикаты, которые, скорее всего, будут успешными, оцениваются раньше, а для
.BR \-a ,
предикаты, которые, скорее всего, не сработают, оцениваются раньше.
.RE
.IP
Оптимизатор, основанный на стоимости, имеет фиксированное представление о том, насколько вероятно, что данный тест будет успешным. В некоторых случаях вероятность учитывает специфический характер теста (например, предполагается, что
.B \-type\ f
скорее будет успешным, чем
.BR "\-type\ c" ).
Оптимизатор, основанный на стоимости, в настоящее время оценивается.
Если он не улучшает производительность
.B find
, он будет удален. И наоборот, оптимизации, которые докажут свою надежность, устойчивость и эффективность, могут со временем быть включены на более низких уровнях оптимизации. Однако поведение по умолчанию (т.е. уровень оптимизации 1) не будет изменено в серии выпусков 4.3.x. Набор тестов findutils выполняет все тесты для
.B find
на каждом уровне оптимизации и гарантирует, что результат остается неизменным.
.
.SH ВЫРАЖЕНИЕ
Часть командной строки после списка отправных точек представляет собой
.IR выражение .
Это своего рода спецификация запроса, описывающая, как мы сопоставляем файлы и что мы делаем с файлами, которые были сопоставлены.
Выражение состоит из последовательности элементов:

.IP Тесты
Тесты возвращают значение true или false, обычно на основе некоторого свойства рассматриваемого файла. Тест
.B \-empty
, например, истинен только тогда, когда текущий файл пуст.

.IP Действия
Действия имеют побочные эффекты (например, вывод чего-либо на стандартный вывод) и возвращают true или false, обычно в зависимости от того, успешны они или нет. Действие
.B \-print
, например, выводит имя текущего файла на стандартный вывод.

.IP "Глобальные параметры"
Глобальные параметры влияют на работу тестов и действий, указанных в любой части командной строки. Глобальные параметры всегда возвращают true. Параметр
.B \-depth
, например, заставляет
.B find
обходить файловую систему в порядке поиска в глубину.

.IP "Позиционные параметры"
Позиционные параметры влияют только на тесты или действия, которые следуют за ними. Позиционные параметры всегда возвращают true. Параметр
.B \-regextype
, например, является позиционным и указывает диалект регулярных выражений для регулярных выражений, встречающихся позже в командной строке.

.IP Операторы
Операторы объединяют другие элементы внутри выражения. Они включают, например,
.B \-o
(означает логическое ИЛИ) и
.B \-a
(означает логическое И). Там, где оператор отсутствует, предполагается
.B \-a
.

.P
Действие
.B \-print
выполняется для всех файлов, для которых все выражение истинно, если только оно не содержит действие, отличное от
.B \-prune
или
.BR \-quit .
Действия, которые подавляют действие
.B \-print
по умолчанию:
.BR \-delete ,
.BR \-exec ,
.BR \-execdir ,
.BR \-ok ,
.BR \-okdir ,
.BR \-fls ,
.BR \-fprint ,
.BR \-fprintf ,
.BR \-ls ,
.B \-print
и
.BR \-printf .


Действие
.B \-delete
также действует как параметр (поскольку оно подразумевает
.BR \-depth ).

.SS ПОЗИЦИОННЫЕ ПАРАМЕТРЫ
Позиционные параметры всегда возвращают true. Они влияют только на тесты, встречающиеся позже в командной строке.

.IP \-daystart
Измерять время (для
.BR \-amin ,
.BR \-atime ,
.BR \-cmin ,
.BR \-ctime ,
.BR \-mmin ,
и
.BR \-mtime )
с начала текущего дня, а не с 24 часов назад. Этот параметр влияет только на тесты, которые появляются позже в командной строке.

.IP \-follow
Устарело; используйте параметр
.B \-L
вместо этого. Разыменовывать символические ссылки.
Подразумевает
.BR \-noleaf .
Параметр
.B \-follow
влияет только на тесты, которые появляются после него в командной строке. Если не указан параметр
.B \-H
 или
.B \-L
, положение параметра
.B \-follow
изменяет поведение предиката
.B \-newer
; любые файлы, указанные в качестве аргумента
.B \-newer
, будут разыменованы, если они являются символическими ссылками. То же самое относится к
.BR \-newerXY ,
.B \-anewer
и
.BR \-cnewer .
Аналогично, предикат
.B \-type
всегда будет сравнивать тип файла, на который указывает символическая ссылка, а не саму ссылку. Использование
.B \-follow
приводит к тому, что предикаты
.B \-lname
и
.B \-ilname
всегда возвращают false.

.IP "\-regextype \fItype\fR"
Изменяет синтаксис регулярных выражений, понимаемый тестами
.B \-regex
и
.B \-iregex
, которые встречаются позже в командной строке. Чтобы увидеть, какие типы регулярных выражений известны, используйте
.BR "\-regextype\ help" .
Документация Texinfo (см.
.B СМ.
.BR ТАКЖЕ )
объясняет значение и различия между различными типами регулярных выражений.

.IP "\-warn, \-nowarn"
Включить или выключить предупреждающие сообщения. Эти предупреждения применяются только к использованию командной строки, а не к любым условиям, с которыми
.B find
может столкнуться при поиске в каталогах. Поведение по умолчанию соответствует
.B \-warn
, если стандартный ввод является терминалом, и
.B \-nowarn
в противном случае. Если выдается предупреждающее сообщение, относящееся к использованию командной строки, код выхода
.B find
не затрагивается. Если установлена переменная окружения POSIXLY_CORRECT и также используется
.B \-warn
, не определено, какие предупреждения (если они есть) будут активны.

.SS ГЛОБАЛЬНЫЕ ПАРАМЕТРЫ
Глобальные параметры всегда возвращают true.
Глобальные параметры вступают в силу даже для тестов, которые встречаются раньше в командной строке. Чтобы предотвратить путаницу, глобальные параметры следует указывать в командной строке после списка начальных точек, непосредственно перед первым тестом, позиционным параметром или действием.
Если вы укажете глобальный параметр в другом месте,
.B find
выдаст предупреждающее сообщение, объясняющее, что это может привести к путанице.

Глобальные параметры встречаются после списка начальных точек, поэтому они не являются таким же типом параметров, как, например,
.BR \-L .

.IP \-d
Синоним для \-depth, для совместимости с FreeBSD, NetBSD, MacOS X и OpenBSD.

.IP \-depth
Обрабатывать содержимое каждого каталога перед самим каталогом. Действие \-delete также подразумевает
.BR \-depth .

.IP "\-help, \-\-help"
Вывести краткую справку по использованию
.B find
в командной строке и завершить работу.

.IP \-ignore_readdir_race
Обычно
.B find
выдает сообщение об ошибке, когда ему не удается получить информацию о файле (stat).
Если вы укажете этот параметр, и файл будет удален в промежутке между моментом, когда
.B find
прочитает имя файла из каталога, и моментом, когда он попытается получить информацию о нем, сообщение об ошибке не будет выдано.
Это также относится к файлам или каталогам, чьи имена указаны в командной строке.
Этот параметр вступает в силу в момент чтения командной строки, что означает, что вы не можете искать в одной части файловой системы с включенным этим параметром, а в другой — с выключенным (если вам нужно сделать это, вам придется выполнить две команды
.B find
, одну с параметром, а другую без него).

Более того,
.B find
с параметром
.B \-ignore_readdir_race
будет игнорировать ошибки действия
.B \-delete
в том случае, если файл исчез с момента чтения родительского каталога: он не будет выводить диагностику ошибки, а код возврата действия
.B \-delete
будет true.

.IP "\-maxdepth \fIlevels\fR"
Спускаться не более чем на \fIlevels\fR (неотрицательное целое число) уровней каталогов ниже начальных точек. Использование
.B \-maxdepth\ 0
означает применение тестов и действий только к самим начальным точкам.

.IP "\-mindepth \fIlevels\fR"
Не применять тесты или действия на уровнях меньше \fIlevels\fR (неотрицательное целое число). Использование
.B \-mindepth\ 1
означает обработку всех файлов, кроме начальных точек.

.IP \-mount
Не спускаться в каталоги на других файловых системах. Альтернативное имя для
.BR \-xdev ,
для совместимости с некоторыми другими версиями
.BR find .

.IP \-noignore_readdir_race
Отключает действие
.BR \-ignore_readdir_race .

.IP "\-noleaf"
Не оптимизировать, предполагая, что каталоги содержат на 2 подкаталога меньше, чем их счетчик жестких ссылок. Этот параметр необходим при поиске в файловых системах, которые не следуют соглашению Unix о ссылках на каталоги, таких как CD-ROM, файловые системы MS-DOS или точки монтирования томов AFS. Каждый каталог в обычной файловой системе Unix имеет как минимум 2 жесткие ссылки: его имя и его запись `.\&'. Кроме того, каждый из его подкаталогов (если они есть) имеет запись `..\&', связанную с этим каталогом. Когда
.B find
проверяет каталог, после того как он обнаружил на 2 подкаталога меньше, чем счетчик ссылок каталога, он знает, что остальные записи в каталоге являются не каталогами (файлы «листья» в дереве каталогов). Если нужно проверять только имена файлов, нет необходимости вызывать stat для них; это дает значительное увеличение скорости поиска.

.IP "\-version, \-\-version"
Вывести номер версии
.B find
и завершить работу.

.IP \-xdev
Не спускаться в каталоги на других файловых системах.

.SS ТЕСТЫ
Некоторые тесты, например
.B \-newerXY
и
.BR \-samefile ,
позволяют выполнять сравнение между файлом, который проверяется в данный момент, и некоторым эталонным файлом, указанным в командной строке. Когда используются эти тесты, интерпретация эталонного файла определяется параметрами
.BR \-H ,
.B \-L
и
.B \-P
и любыми предыдущими
.BR \-follow ,
но эталонный файл проверяется только один раз, во время разбора командной строки. Если эталонный файл не может быть проверен (например, системный вызов
.BR stat (2)
завершается с ошибкой для него), выдается сообщение об ошибке, и
.B find
завершает работу с ненулевым статусом.
.P
Числовой аргумент \fIn\fR может быть указан для тестов (таких как
.BR \-amin ,
.BR \-mtime ,
.BR \-gid ,
.BR \-inum ,
.BR \-links ,
.BR \-size ,
.BR \-uid
и
.BR \-used )
как:
.IP \fI+n\fP
для значения больше
.IR n ,
.IP \fI\-n\fP
для значения меньше
.IR n ,
.IP \fIn\fP
для значения, равного в точности
.IR n .
.
.P
Поддерживаемые тесты:

.IP "\-amin \fIn\fR"
Файл был в последний раз прочитан менее, более или ровно \fIn\fR минут назад.

.IP "\-anewer \fIreference\fR"
Время последнего доступа к текущему файлу более позднее, чем время последнего изменения данных эталонного файла
.I reference
. Если
.I reference
является символической ссылкой и активен параметр
.B \-H
 или
.B \-L
, то всегда используется время последнего изменения данных файла, на который она указывает.

.IP "\-atime \fIn\fR"
Файл был в последний раз прочитан менее, более или ровно
.IR n *24
часов назад.
Когда find вычисляет, сколько 24-часовых периодов назад файл был в последний раз прочитан, любая дробная часть игнорируется, поэтому, чтобы соответствовать
.BR "\-atime\ +1" ,
файл должен был быть прочитан как минимум
.I два
дня назад.

.IP "\-cmin \fIn\fR"
Статус файла был в последний раз изменен менее, более или ровно \fIn\fR минут назад.

.IP "\-cnewer \fIreference\fR"
Время последнего изменения статуса текущего файла более позднее, чем время последнего изменения данных эталонного файла
.I reference
. Если
.I reference
является символической ссылкой и активен параметр
.B \-H
 или
.B \-L
, то всегда используется время последнего изменения данных файла, на который она указывает.

.IP "\-ctime \fIn\fR"
Статус файла был в последний раз изменен менее, более или ровно
.IR n *24
часов назад.
См. комментарии к
.B \-atime
, чтобы понять, как округление влияет на интерпретацию времени изменения статуса файла.

.IP \-empty
Файл пуст и является либо обычным файлом, либо каталогом.

.IP \-executable
Соответствует файлам, которые являются исполняемыми, и каталогам, которые доступны для поиска (в смысле разрешения имен файлов) текущим пользователем.
Это учитывает списки контроля доступа и другие артефакты прав доступа, которые тест
.B \-perm
игнорирует. Этот тест использует системный вызов
.BR access (2)
, поэтому его могут обмануть NFS-серверы, которые выполняют UID-маппинг (или root-squashing), поскольку многие системы реализуют
.BR access (2)
в ядре клиента и поэтому не могут использовать информацию о UID-маппинге, хранящуюся на сервере. Поскольку этот тест основан только на результате системного вызова
.BR access (2)
, нет гарантии, что файл, для которого этот тест успешен, действительно может быть выполнен.

.IP \-false
Всегда false.

.IP "\-fstype \fItype\fR"
Файл находится на файловой системе типа
.IR type .
Допустимые типы файловых систем различаются в разных версиях Unix; неполный список типов файловых систем, принимаемых в той или иной версии Unix: ufs, 4.2, 4.3, nfs, tmp, mfs, S51K, S52K. Вы можете использовать
.B \-printf
с директивой %F, чтобы увидеть типы ваших файловых систем.

.IP "\-gid \fIn\fR"
Числовой идентификатор группы файла меньше, больше или равен
.IR n .

.IP "\-group \fIgname\fR"
Файл принадлежит группе
.I gname
(допускается числовой идентификатор группы).

.IP "\-ilname \fIpattern\fR"
Как
.BR \-lname ,
но без учета регистра.
Если активен параметр
.B \-L
 или
.B \-follow
, этот тест возвращает false, если только символическая ссылка не является битой.


.IP "\-iname \fIpattern\fR"
Как
.BR \-name ,
но без учета регистра. Например, шаблоны `fo*' и `F??' соответствуют именам файлов `Foo', `FOO', `foo', `fOo' и т.д.
Шаблон `*foo*' также будет соответствовать файлу с именем '.foobar'.

.IP "\-inum \fIn\fR"
Файл имеет номер inode меньше, больше или равен
.IR n .
Обычно проще использовать тест
.B \-samefile
.

.IP "\-ipath \fIpattern\fR"
Как
.BR \-path ,
но без учета регистра.

.IP "\-iregex \fIpattern\fR"
Как
.BR \-regex ,
но без учета регистра.

.IP "\-iwholename \fIpattern\fR"
См. \-ipath. Эта альтернатива менее переносима, чем
.BR \-ipath .

.IP "\-links \fIn\fR"
Файл имеет меньше, больше или ровно
.IR n
жестких ссылок.

.IP "\-lname \fIpattern\fR"
Файл является символической ссылкой, содержимое которой соответствует шаблону оболочки
.IR pattern .
Метасимволы не обрабатывают `/' или `.\&' особым образом.
Если активен параметр
.B \-L
 или
.B \-follow
, этот тест возвращает false, если только символическая ссылка не является битой.

.IP "\-mmin \fIn\fR"
Данные файла были в последний раз изменены менее, более или ровно \fIn\fR минут назад.

.IP "\-mtime \fIn\fR"
Данные файла были в последний раз изменены менее, более или ровно
.IR n *24
часов назад.
См. комментарии к
.B \-atime
, чтобы понять, как округление влияет на интерпретацию времени изменения данных файла.

.IP "\-name \fIpattern\fR"
Базовое имя файла (путь с удаленными ведущими каталогами) соответствует шаблону оболочки
.IR pattern .
Поскольку ведущие каталоги удалены, имена файлов, рассматриваемые для сопоставления с
.B \-name
, никогда не будут содержать косую черту, поэтому `\-name a/b' никогда ничего не найдет (вам, вероятно, стоит использовать
.B \-path
вместо этого).
Выдается предупреждение, если вы попытаетесь сделать это, если только не установлена переменная окружения POSIXLY_CORRECT.
Метасимволы (`*', `?' и `[]') соответствуют `.\&' в начале базового имени (это изменение в findutils-4.2.2; см. раздел СООТВЕТСТВИЕ СТАНДАРТАМ ниже). Чтобы игнорировать каталог и файлы под ним, используйте
.B \-prune
вместо проверки каждого файла в дереве; см. пример в описании этого действия.
Фигурные скобки не распознаются как имеющие особое значение, несмотря на то, что некоторые оболочки, включая Bash, придают им особый смысл в шаблонах оболочки. Сопоставление имен файлов выполняется с использованием библиотечной функции
.BR fnmatch (3)
.
Не забудьте заключить шаблон в кавычки, чтобы защитить его от раскрытия оболочкой.

.IP "\-newer \fIreference\fR"
Время последнего изменения данных текущего файла более позднее, чем время последнего изменения данных эталонного файла
.I reference
. Если
.I reference
является символической ссылкой и активен параметр
.B \-H
 или
.B \-L
, то всегда используется время последнего изменения данных файла, на который она указывает.

.IP "\-newerXY \fIreference\fR"
Истинно, если временная метка \fIX\fR рассматриваемого файла новее, чем временная метка \fIY\fR файла
.IR reference .
Буквы \fIX\fR и \fIY\fR могут быть любыми из следующих:

.TS
ll
ll
ll
ll
llw(2i).
a	Время последнего доступа к файлу \fIreference\fR
B	Время создания файла \fIreference\fR
c	Время последнего изменения статуса inode файла \fIreference\fR
m	Время последнего изменения данных файла \fIreference\fR
t	\fIreference\fR интерпретируется напрямую как время
.TE

Некоторые комбинации недопустимы; например, недопустимо, чтобы
.I X
было
.IR t .
Некоторые комбинации реализованы не во всех системах; например,
.I B
поддерживается не везде. Если указана недопустимая или неподдерживаемая комбинация
.I XY
, это приводит к фатальной ошибке. Спецификации времени интерпретируются так же, как и для аргумента параметра
.B \-d
команды GNU
.BR date .
Если вы попытаетесь использовать время создания эталонного файла, и его невозможно определить, это приведет к фатальной ошибке. Если вы укажете тест, который ссылается на время создания проверяемых файлов, этот тест будет неудачным для всех файлов, время создания которых неизвестно.

.IP \-nogroup
Нет группы, соответствующей числовому идентификатору группы файла.

.IP \-nouser
Нет пользователя, соответствующего числовому идентификатору пользователя файла.

.IP "\-path \fIpattern\fR"
Имя файла соответствует шаблону оболочки
.IR pattern .
Метасимволы не обрабатывают `/' или `.\&' особым образом; поэтому, например,
.in +4m
.nf
find . \-path \(dq./sr*sc\(dq
.fi
.in
выведет запись для каталога с именем
.I ./src/misc
(если такой существует). Чтобы игнорировать целое дерево каталогов, используйте
.B \-prune
вместо проверки каждого файла в дереве.
Обратите внимание, что тест сопоставления шаблона применяется ко всему имени файла, начиная с одной из начальных точек, указанных в командной строке. Использование здесь абсолютного пути имело бы смысл, только если соответствующая начальная точка также является абсолютным путем. Это означает, что следующая команда никогда ничего не найдет:
.br
.in +4m
.nf
find bar \-path /foo/bar/myfile \-print
.fi
.in
Find сравнивает аргумент
.B \-path
с объединением имени каталога и базового имени проверяемого файла. Поскольку объединение никогда не заканчивается косой чертой, аргументы
.B \-path
, заканчивающиеся на косую черту, ничему не будут соответствовать (за исключением, возможно, начальной точки, указанной в командной строке).
Предикат
.B \-path
также поддерживается командой
.B find
в HP-UX и является частью стандарта POSIX 2008.

.IP "\-perm \fImode\fR"
Биты прав доступа файла точно равны \fImode\fR (восьмеричное или символьное значение).
Поскольку требуется точное совпадение, если вы хотите использовать эту форму для символьных режимов, вам, возможно, придется указать довольно сложную строку режима. Например, `\-perm g=w' будет соответствовать только файлам, имеющим режим 0020 (то есть тем, для которых право записи группой является единственным установленным правом). Скорее всего, вы захотите использовать формы `/' или `\-', например `\-perm \-g=w', которая соответствует любому файлу с правом записи для группы. См. раздел
.B ПРИМЕРЫ
для наглядных примеров.

.IP "\-perm \-\fImode\fR"
Все биты прав доступа \fImode\fR установлены для файла.
Символьные режимы принимаются в этой форме, и обычно это тот способ, которым вы захотите их использовать. Вы должны указать `u', `g' или `o', если используете символьный режим.
См. раздел
.B ПРИМЕРЫ
для наглядных примеров.

.IP "\-perm /\fImode\fR"
Любой из битов прав доступа \fImode\fR установлен для файла. Символьные режимы принимаются в этой форме. Вы должны указать `u', `g' или `o', если используете символьный режим. См. раздел
.B ПРИМЕРЫ
для наглядных примеров. Если в
.I mode
не установлено ни одного бита прав доступа, этот тест соответствует любому файлу (идея здесь в том, чтобы соответствовать поведению
.BR "\-perm\ \-000" ).

.IP "\-perm +\fImode\fR"
Больше не поддерживается (и считается устаревшим с 2005 года). Используйте
.B "\-perm /\fImode\fR"
вместо этого.

.IP \-readable
Соответствует файлам, которые доступны для чтения текущему пользователю. Это учитывает списки контроля доступа и другие артефакты прав доступа, которые тест
.B \-perm
игнорирует. Этот тест использует системный вызов
.BR access (2)
, поэтому его могут обмануть NFS-серверы, которые выполняют UID-маппинг (или root-squashing), поскольку многие системы реализуют
.BR access (2)
в ядре клиента и поэтому не могут использовать информацию о UID-маппинге, хранящуюся на сервере.

.IP "\-regex \fIpattern\fR"
Имя файла соответствует регулярному выражению
.IR pattern .
Это сопоставление со всем путем, а не поиск.
Например, чтобы найти файл с именем
.IR ./fubar3,
вы можете использовать регулярное выражение `.*bar.\&' или `.*b.*3', но не `f.*r3'.
Регулярные выражения, понимаемые
.B find
, по умолчанию являются регулярными выражениями Emacs (за исключением того, что `.' соответствует символу новой строки), но это можно изменить с помощью параметра
.B \-regextype
.

.IP "\-samefile \fIname\fR"
Файл ссылается на тот же inode, что и
.IR name .
Когда активен параметр
.B \-L
, это может включать символические ссылки.

.IP "\-size \fIn\fR[cwbkMG]"
Файл использует меньше, больше или ровно \fIn\fP единиц пространства с округлением вверх.
Можно использовать следующие суффиксы:
.RS
.IP `b'
для 512-байтовых блоков (это значение по умолчанию, если суффикс не указан)
.IP `c'
для байтов
.IP `w'
для двухбайтовых слов
.IP `k'
для кибибайт (KiB, единицы по 1024 байта)
.IP `M'
для мебибайт (MiB, единицы по 1024 * 1024 = 1\|048\|576 байт)
.IP `G'
для гибибайт (GiB, единицы по 1024 * 1024 * 1024 = 1\|073\|741\|824 байт)
.RE
.IP
Размер — это просто элемент st_size структуры stat, заполненный системным вызовом lstat (или stat), округленный вверх, как показано выше.
Другими словами, это согласуется с результатом, который вы получаете для
.BR "ls\ \-l" .
Имейте в виду, что спецификаторы формата `%k' и `%b' действия
.B \-printf
обрабатывают разреженные файлы иначе. Суффикс `b' всегда обозначает 512-байтовые блоки, а не 1024-байтовые, что отличается от поведения
.BR \-ls .
.IP
Префиксы + и - означают больше и меньше, как обычно; т.е. точный размер в \fIn\fR единиц не соответствует.
Имейте в виду, что размер округляется вверх до следующей единицы.
Поэтому
.B \-size\ \-1M
не эквивалентно
.BR "\-size\ \-1\|048\|576c" .
Первое соответствует только пустым файлам, второе соответствует файлам от 0 до 1 048 575 байт.
.IP \-true
Всегда true.

.IP "\-type \fIc\fR"
Файл имеет тип
.IR c :
.RS
.IP b
блочное (буферизуемое) специальное устройство
.IP c
символьное (небуферизуемое) специальное устройство
.IP d
каталог
.IP p
именованный канал (FIFO)
.IP f
обычный файл
.IP l
символическая ссылка; это никогда не бывает истинно, если активен параметр
.B \-L
 или
.B \-follow
, если только символическая ссылка не является битой. Если вы хотите искать символические ссылки, когда активен
.B \-L
, используйте
.BR \-xtype .
.IP s
сокет
.IP D
door (Solaris)
.RE
.IP
Для поиска более чем одного типа одновременно можно указать объединенный список букв типов, разделенных запятой `,' (расширение GNU).
.IP "\-uid \fIn\fR"
Числовой идентификатор пользователя файла меньше, больше или равен
.IR n .

.IP "\-used \fIn\fR"
Файл был в последний раз прочитан менее, более или ровно \fIn\fR дней после того, как его статус был в последний раз изменен.

.IP "\-user \fIuname\fR"
Файл принадлежит пользователю
.I uname
(допускается числовой идентификатор пользователя).

.IP "\-wholename \fIpattern\fR"
См. \-path. Эта альтернатива менее переносима, чем
.BR \-path .

.IP "\-writable"
Соответствует файлам, которые доступны для записи текущему пользователю. Это учитывает списки контроля доступа и другие артефакты прав доступа, которые тест
.B \-perm
игнорирует. Этот тест использует системный вызов
.BR access (2)
, поэтому его могут обмануть NFS-серверы, которые выполняют UID-маппинг (или root-squashing), поскольку многие системы реализуют
.BR access (2)
в ядре клиента и поэтому не могут использовать информацию о UID-маппинге, хранящуюся на сервере.

.IP "\-xtype \fIc\fR"
То же самое, что и
.B \-type
, если только файл не является символической ссылкой. Для символических ссылок: если был указан параметр
.B \-H
 или
.B \-P
, истинно, если файл является ссылкой на файл типа
.IR c ;
если был дан параметр
.B \-L
, истинно, если \fIc\fR — это `l'. Другими словами, для символических ссылок
.B \-xtype
проверяет тип файла, который
.B \-type
не проверяет.
.IP "\-context \fIpattern\fR"
(только SELinux) Контекст безопасности файла соответствует glob-шаблону
.IR pattern .

.SS ДЕЙСТВИЯ
.IP "\-delete\fR"
Удалить файлы; истинно, если удаление прошло успешно. Если удаление не удалось, выдается сообщение об ошибке.
Если
.B \-delete
завершается неудачно, код выхода
.B find
будет ненулевым (когда он в конечном итоге завершится).
Использование
.B \-delete
автоматически включает параметр
.RB ` \-depth '
.

.BR Предупреждения :
Не забывайте, что командная строка find вычисляется как выражение, поэтому размещение
.B \-delete
в начале заставит
.B find
попытаться удалить все ниже указанных вами отправных точек.
При тестировании командной строки
.B find
, которую вы позже собираетесь использовать с
.BR \-delete ,
вам следует явно указать
.B \-depth
, чтобы избежать неприятных сюрпризов. Поскольку
.B \-delete
подразумевает
.BR \-depth ,
вы не можете эффективно использовать
.B \-prune
и
.B \-delete
вместе.

Вместе с параметром
.B \-ignore_readdir_race
,
.B find
будет игнорировать ошибки действия
.B \-delete
в том случае, если файл исчез с момента чтения родительского каталога: он не будет выводить диагностику ошибки, а код возврата действия
.B \-delete
будет true.

.IP "\-exec \fIcommand\fR ;"
Выполнить
.IR command ;
истинно, если возвращен статус 0. Все последующие аргументы для
.B find
считаются аргументами команды до тех пор, пока не встретится аргумент, состоящий из `;'. Строка `{}' заменяется текущим именем обрабатываемого файла везде, где она встречается в аргументах команды, а не только в аргументах, где она стоит одна, как в некоторых версиях
.BR find .
Обе эти конструкции могут потребовать экранирования (с помощью `\e') или заключения в кавычки для защиты от раскрытия оболочкой. См. раздел
.B ПРИМЕРЫ
для примеров использования параметра
.B \-exec
. Указанная команда выполняется один раз для каждого найденного файла.
Команда выполняется в начальном каталоге.
Существуют неизбежные проблемы безопасности, связанные с использованием действия
.B \-exec
; вам следует использовать параметр
.B \-execdir
вместо него.

.IP "\-exec \fIcommand\fR {} +"
Этот вариант действия
.B \-exec
выполняет указанную команду над выбранными файлами, но командная строка строится путем добавления каждого выбранного имени файла в конец; общее количество вызовов команды будет намного меньше, чем количество найденных файлов. Командная строка строится примерно так же, как
.B xargs
строит свои командные строки. Допускается только один экземпляр `{}' внутри команды, и он должен стоять в конце, непосредственно перед `+'; его нужно экранировать (с помощью `\e') или заключать в кавычки для защиты от интерпретации оболочкой.
Команда выполняется в начальном каталоге. Если какой-либо вызов с формой `+' возвращает ненулевое значение в качестве статуса выхода, то
.B find
возвращает ненулевой статус выхода. Если
.B find
сталкивается с ошибкой, это иногда может вызвать немедленный выход, поэтому некоторые ожидающие выполнения команды могут не быть выполнены вовсе. По этой причине
.B \-exec\ \fImy-command\fP\ ...\ {}\ +\ \-quit
может не привести к фактическому выполнению
.I my-command
. Этот вариант
.B \-exec
всегда возвращает true.

.IP "\-execdir \fIcommand\fR ;"
.IP "\-execdir \fIcommand\fR {} +"
Как и
.BR \-exec ,
но указанная команда выполняется из подкаталога, содержащего найденный файл, который обычно не является каталогом, в котором вы запустили
.BR find .
Как и в случае с -exec, {} следует заключать в кавычки, если find вызывается из оболочки.
Это гораздо более безопасный метод вызова команд, так как он позволяет избежать условий состязания (race conditions) при разрешении путей к найденным файлам. Как и в случае с действием
.B \-exec
, форма `+' действия
.B \-execdir
будет строить командную строку для обработки более чем одного найденного файла, но любой конкретный вызов
.I command
будет перечислять только файлы, существующие в одном и том же подкаталоге. Если вы используете этот параметр, вы должны убедиться, что ваша переменная окружения
.B $PATH
не ссылается на `.'; иначе злоумышленник может выполнить любые команды, какие захочет, оставив файл с подходящим именем в каталоге, в котором вы будете выполнять
.BR \-execdir .
То же самое относится к случаям, когда в
.B $PATH
есть пустые записи или записи, не являющиеся абсолютными именами каталогов. Если какой-либо вызов с формой `+' возвращает ненулевое значение в качестве статуса выхода, то
.B find
возвращает ненулевой статус выхода. Если
.B find
сталкивается с ошибкой, это иногда может вызвать немедленный выход, поэтому некоторые ожидающие выполнения команды могут не быть выполнены вовсе.
Результат действия зависит от того, используется ли вариант
.B +
 или
.B ;
;
.B \-execdir\ \fIcommand\fP\ {}\ +
всегда возвращает true, в то время как
.B \-execdir\ \fIcommand\fP\ {}\ ;
возвращает true только в том случае, если
.I command
возвращает 0.


.IP "\-fls \fIfile\fR"
True; как
.B \-ls
, но запись в
.I file
подобно
.BR \-fprint .
Выходной файл создается всегда, даже если предикат никогда не был удовлетворен.
См. раздел
.B НЕОБЫЧНЫЕ ИМЕНА ФАЙЛОВ
для получения информации о том, как обрабатываются необычные символы в именах файлов.

.IP "\-fprint \fIfile\fR"
True; вывести полное имя файла в файл
.IR file .
Если
.I file
не существует при запуске
.B find
, он создается; если он существует, он усекается. Имена файлов
.I /dev/stdout
 и
.I /dev/stderr
обрабатываются особым образом; они относятся к стандартному выводу и стандартному выводу ошибок соответственно.
Выходной файл создается всегда, даже если предикат никогда не был удовлетворен.
См. раздел
.B НЕОБЫЧНЫЕ ИМЕНА ФАЙЛОВ
для получения информации о том, как обрабатываются необычные символы в именах файлов.

.IP "\-fprint0 \fIfile\fR"
True; как
.B \-print0
, но запись в
.I file
подобно
.BR \-fprint .
Выходной файл создается всегда, даже если предикат никогда не был удовлетворен.
См. раздел
.B НЕОБЫЧНЫЕ ИМЕНА ФАЙЛОВ
для получения информации о том, как обрабатываются необычные символы в именах файлов.

.IP "\-fprintf \fIfile\fR \fIformat\fR"
True; как
.B \-printf
, но запись в
.I file
подобно
.BR \-fprint .
Выходной файл создается всегда, даже если предикат никогда не был удовлетворен.
См. раздел
.B НЕОБЫЧНЫЕ ИМЕНА ФАЙЛОВ
для получения информации о том, как обрабатываются необычные символы в именах файлов.

.IP \-ls
True; вывести текущий файл в формате
.B ls \-dils
на стандартный вывод.
Счетчики блоков — это блоки по 1 КБ, если не установлена переменная окружения POSIXLY_CORRECT, в этом случае используются блоки по 512 байт.
См. раздел
.B НЕОБЫЧНЫЕ ИМЕНА ФАЙЛОВ
для получения информации о том, как обрабатываются необычные символы в именах файлов.

.IP "\-ok \fIcommand\fR ;"
Как
.B \-exec
, но сначала спросить пользователя. Если пользователь согласен, выполнить команду. В противном случае просто вернуть false. Если команда выполняется, ее стандартный ввод перенаправляется из
.IR /dev/null .

.IP
Ответ на запрос сопоставляется с парой регулярных выражений, чтобы определить, является ли он утвердительным или отрицательным. Это регулярное выражение получается из системы, если установлена переменная окружения `POSIXLY_CORRECT', или, в противном случае, из переводов сообщений
.BR find .
Если в системе нет подходящего определения, будет использовано собственное определение
.BR find .
В любом случае на интерпретацию самого регулярного выражения будут влиять переменные окружения 'LC_CTYPE' (классы символов) и 'LC_COLLATE' (диапазоны символов и классы эквивалентности).



.IP "\-okdir \fIcommand\fR ;"
Как
.B \-execdir
, но сначала спросить пользователя так же, как для
.BR \-ok .
Если пользователь не согласен, просто вернуть false.
Если команда выполняется, ее стандартный ввод перенаправляется из
.IR /dev/null .

.IP \-print
True; вывести полное имя файла на стандартный вывод, за которым следует символ новой строки.
Если вы перенаправляете вывод
.B find
в другую программу и есть малейшая вероятность того, что файлы, которые вы ищете, могут содержать символ новой строки, то вам следует серьезно подумать об использовании параметра
.B \-print0
вместо
.BR \-print .
См. раздел
.B НЕОБЫЧНЫЕ ИМЕНА ФАЙЛОВ
для получения информации о том, как обрабатываются необычные символы в именах файлов.

.IP \-print0
True; вывести полное имя файла на стандартный вывод, за которым следует нулевой символ (вместо символа новой строки, который использует
.B \-print
).
Это позволяет программам, обрабатывающим вывод
.B find
, правильно интерпретировать имена файлов, содержащие символы новой строки или другие типы пробельных символов. Этот параметр соответствует параметру
.B \-0
команды
.BR xargs .

.IP "\-printf \fIformat\fR"
True; вывести
.I format
на стандартный вывод, интерпретируя `\e'-экранированные последовательности и `%'-директивы. Ширину поля и точность можно указывать так же, как и в функции C
.BR printf (3)
. Обратите внимание, что многие поля выводятся как %s, а не %d, и это может означать, что флаги не работают так, как вы могли бы ожидать. Это также означает, что флаг `\-' работает (он заставляет поля выравниваться по левому краю). В отличие от
.BR \-print ,
.B \-printf
не добавляет символ новой строки в конце строки. Экранированные последовательности и директивы:
.RS
.IP \ea
Звуковой сигнал.
.IP \eb
Backspace (возврат на один символ).
.IP \ec
Немедленно прекратить печать из этого формата и сбросить вывод.
.IP \ef
Перевод страницы (form feed).
.IP \en
Новая строка.
.IP \er
Возврат каретки.
.IP \et
Горизонтальная табуляция.
.IP \ev
Вертикальная табуляция.
.IP \e0
ASCII NUL.
.IP \e\e
Литеральная обратная косая черта (`\e').
.IP \eNNN
Символ, код ASCII которого равен NNN (восьмеричное).
.PP
Символ `\e', за которым следует любой другой символ, рассматривается как обычный символ, поэтому оба они выводятся.
.IP %%
Литеральный знак процента.
.IP %a
Время последнего доступа к файлу в формате, возвращаемом функцией C
.BR ctime (3)
.
.IP %A\fIk\fP
Время последнего доступа к файлу в формате, указанном параметром
.IR k ,
который является либо `@', либо директивой для функции C
.BR strftime (3)
.
Ниже приведен неполный список возможных значений для \fIk\fR.
Пожалуйста, обратитесь к документации
.BR strftime (3)
для получения полного списка.
Некоторые символы спецификации преобразования могут быть доступны не во всех системах из-за различий в реализации библиотечной функции
.BR strftime (3)
.
.RS
.IP @
секунды с 1 января 1970 г., 00:00 GMT, с дробной частью.
.PP
Поля времени:
.IP H
час (00..23)
.IP I
час (01..12)
.IP k
час ( 0..23)
.IP l
час ( 1..12)
.IP M
минута (00..59)
.IP p
AM или PM локали
.IP r
время, 12-часовой формат (hh:mm:ss [AP]M)
.IP S
секунды (00.00 .. 61.00). Присутствует дробная часть.
.IP T
время, 24-часовой формат (hh:mm:ss.xxxxxxxxxx)
.IP +
Дата и время, разделенные `+', например `2004\-04\-28+22:22:05.0'. Это расширение GNU. Время дается в текущем часовом поясе (на который может влиять установка переменной окружения TZ). Поле секунд включает дробную часть.
.IP X
представление времени локали (H:M:S). Поле секунд включает дробную часть.
.IP Z
часовой пояс (например, EDT) или ничего, если часовой пояс не определим.
.PP
Поля даты:
.IP a
сокращенное название дня недели локали (Sun..Sat)
.IP A
полное название дня недели локали, переменная длина (Sunday..Saturday)
.IP b
сокращенное название месяца локали (Jan..Dec)
.IP B
полное название месяца локали, переменная длина (January..December)
.IP c
дата и время локали (Sat Nov 04 12:02:33 EST 1989). Формат такой же, как для
.BR ctime (3)
, поэтому для сохранения совместимости с этим форматом в поле секунд нет дробной части.
.IP d
день месяца (01..31)
.IP D
дата (mm/dd/yy)
.IP F
дата (yyyy-mm-dd)
.IP h
то же, что и b
.IP j
день года (001..366)
.IP m
месяц (01..12)
.IP U
номер недели в году, воскресенье — первый день недели (00..53)
.IP w
день недели (0..6)
.IP W
номер недели в году, понедельник — первый день недели (00..53)
.IP x
представление даты локали (mm/dd/yy)
.IP y
последние две цифры года (00..99)
.IP Y
год (1970...\&)
.RE
.IP %b
Объем дискового пространства, используемого этим файлом, в 512-байтовых блоках. Поскольку дисковое пространство выделяется кратно размеру блока файловой системы, это значение обычно больше, чем %s/512, но оно также может быть меньше, если файл является разреженным.
.IP %c
Время последнего изменения статуса файла в формате, возвращаемом функцией C
.BR ctime (3)
.
.IP %C\fIk\fP
Время последнего изменения статуса файла в формате, указанном параметром
.IR k ,
который такой же, как для %A.
.IP %d
Глубина файла в дереве каталогов; 0 означает, что файл является начальной точкой.
.IP %D
Номер устройства, на котором существует файл (поле st_dev структуры stat), в десятичном виде.
.IP %f
Вывести базовое имя; имя файла с удаленными ведущими каталогами (только последний элемент). Для
.BR / ,
результат — `/'.
См. раздел
.B ПРИМЕРЫ
для примера.

.IP %F
Тип файловой системы, на которой находится файл; это значение можно использовать для \-fstype.
.IP %g
Имя группы файла или числовой идентификатор группы, если у группы нет имени.
.IP %G
Числовой идентификатор группы файла.
.IP %h
Dirname; ведущие каталоги имени файла (все элементы, кроме последнего). Если имя файла не содержит косых черт (поскольку он находится в текущем каталоге), спецификатор %h раскрывается в `.'. Для файлов, которые сами являются каталогами и содержат косую черту (включая
.BR / ),
%h раскрывается в пустую строку. См. раздел
.B ПРИМЕРЫ
для примера.
.IP %H
Начальная точка, под которой был найден файл.
.IP %i
Номер inode файла (в десятичном виде).
.IP %k
Объем дискового пространства, используемого этим файлом, в блоках по 1 КБ.
Поскольку дисковое пространство выделяется кратно размеру блока файловой системы, это значение обычно больше, чем %s/1024, но оно также может быть меньше, если файл является разреженным.
.IP %l
Объект символической ссылки (пустая строка, если файл не является символической ссылкой).
.IP %m
Биты прав доступа файла (в восьмеричном виде). Этот параметр использует «традиционные» числа, которые используют большинство реализаций Unix, но если ваша конкретная реализация использует необычный порядок битов восьмеричных прав доступа, вы увидите разницу между фактическим значением режима файла и выводом %m.
Обычно вы захотите иметь ведущий ноль в этом числе, и для этого следует использовать флаг
.B #
(как, например, `%#m').
.IP %M
Права доступа файла (в символической форме, как для
.BR ls ).
Эта директива поддерживается в findutils 4.2.5 и более поздних версиях.
.IP %n
Количество жестких ссылок на файл.
.IP %p
Имя файла.
.IP %P
Имя файла с удаленным именем начальной точки, под которой он был найден.
.IP %s
Размер файла в байтах.
.IP %S
Разреженность файла. Вычисляется как (BLOCKSIZE*st_blocks / st_size). Точное значение, которое вы получите для обычного файла определенной длины, зависит от системы. Однако обычно разреженные файлы имеют значения меньше 1.0, а файлы, использующие косвенные блоки, могут иметь значение больше 1.0. В целом, количество блоков, используемых файлом, зависит от файловой системы.
Значение, используемое для BLOCKSIZE, зависит от системы, но обычно составляет 512 байт.
Если размер файла равен нулю, выводимое значение не определено.
В системах, где отсутствует поддержка st_blocks, разреженность файла принимается равной 1.0.
.IP %t
Время последнего изменения файла в формате, возвращаемом функцией C
.BR ctime (3)
.
.IP %T\fIk\fP
Время последнего изменения файла в формате, указанном параметром
.IR k ,
который такой же, как для %A.
.IP %u
Имя пользователя файла или числовой идентификатор пользователя, если у пользователя нет имени.
.IP %U
Числовой идентификатор пользователя файла.
.IP %y
Тип файла (как в
.BR "ls \-l" ),
U=неизвестный тип (не должно случаться)
.IP %Y
Тип файла (как %y), плюс переход по символическим ссылкам: `L'=циклическая, `N'=несуществующая, `?' для любой другой ошибки при определении типа цели символической ссылки.
.IP %Z
(только SELinux) контекст безопасности файла.
.IP "%{ %[ %("
Зарезервировано для будущего использования.
.PP
Символ `%', за которым следует любой другой символ, отбрасывается, но другой символ выводится (не полагайтесь на это, так как могут быть введены дополнительные символы форматирования). `%' в конце аргумента формата вызывает неопределенное поведение, так как нет следующего символа. В некоторых локалях это может скрыть ключи от вашей двери, а в других — удалить последнюю страницу из книги, которую вы читаете.

Директивы %m и %d поддерживают флаги
.BR # ,
.B 0
и
.B +
, но другие директивы — нет, даже если они выводят числа. Числовые директивы, которые не поддерживают эти флаги, включают
.BR G ,
.BR U ,
.BR b ,
.BR D ,
.B  k
и
.BR n .
Флаг формата `\-' поддерживается и меняет выравнивание поля с выравнивания по правому краю (которое является поведением по умолчанию) на выравнивание по левому краю.
.PP
См. раздел
.B НЕОБЫЧНЫЕ ИМЕНА ФАЙЛОВ
для получения информации о том, как обрабатываются необычные символы в именах файлов.


.RE
.IP \-prune
True; если файл является каталогом, не спускаться в него. Если указан
.B \-depth
, то
.B \-prune
не оказывает никакого эффекта. Поскольку
.B \-delete
подразумевает
.BR \-depth ,
вы не можете эффективно использовать
.B \-prune
 и
.B \-delete
вместе.
Например, чтобы пропустить каталог
.I src/emacs
и все файлы и каталоги под ним, и вывести имена других найденных файлов, сделайте что-то вроде этого:
.in +4m
.nf
find . \-path ./src/emacs \-prune \-o \-print
.fi
.in


.IP "\-quit"
Немедленно завершить работу (с нулевым значением возврата, если не произошло ошибок).
Это отличается от
.B \-prune
, потому что
.B \-prune
применяется только к содержимому пропущенных каталогов, в то время как
.B \-quit
просто заставляет
.B find
немедленно остановиться. Никакие дочерние процессы не останутся запущенными. Любые командные строки, построенные с помощью
.B \-exec\ ...\ +
 или
.B \-execdir\ ...\ +
, вызываются до выхода из программы. После выполнения
.B \-quit
больше никаких файлов, указанных в командной строке, обрабатываться не будет. Например,
.RB ` "find\ \fI/tmp/foo\fP\ \fI/tmp/bar\fP\ \-print\ \-quit" `
выведет только `/tmp/foo`.
.br
Одно из частых применений
.B \-quit
— остановить поиск в файловой системе, как только мы нашли то, что искали. Например, если мы хотим найти только один файл, мы можем сделать это так:
.in +4m
.nf
find / -name needle -print -quit
.fi
.in

.SS ОПЕРАТОРЫ
Перечислены в порядке убывания приоритета:

.IP "( \fIexpr\fR )"
Принудительный приоритет. Поскольку скобки имеют особое значение для оболочки, вам обычно нужно будет заключать их в кавычки. Многие примеры на этой man-странице используют для этой цели обратную косую черту: `\e(...\e)' вместо `(...)'.

.IP "! \fIexpr\fR"
True, если
.I expr
false. Этот символ также обычно требует защиты от интерпретации оболочкой.

.IP "\-not \fIexpr\fR"
То же самое, что !\&
.IR expr ,
но не соответствует стандарту POSIX.

.IP "\fIexpr1 expr2\fR"
Два выражения подряд считаются объединенными с подразумеваемым
.BR \-a ;
\fIexpr2\fR не вычисляется, если
.I expr1
false.

.IP "\fIexpr1\fR \-a \fIexpr2\fR"
То же самое, что
.IR "expr1 expr2" .

.IP "\fIexpr1\fR \-and \fIexpr2\fR"
То же самое, что
.IR "expr1 expr2" ,
но не соответствует стандарту POSIX.

.IP "\fIexpr1\fR \-o \fIexpr2\fR"
ИЛИ;
.I expr2
не вычисляется, если
.I expr1
true.

.IP "\fIexpr1\fR \-or \fIexpr2\fR"
То же самое, что
.I expr1
.B \-o
.IR expr2 ,
но не соответствует стандарту POSIX.

.IP "\fIexpr1\fR , \fIexpr2\fR"
Список; как
.I expr1
, так и
.I expr2
всегда вычисляются. Значение
.I expr1
отбрасывается; значение списка — это значение
.IR expr2 .
Оператор «запятая» может быть полезен для поиска нескольких разных типов вещей, но при этом обход иерархии файловой системы осуществляется только один раз. Действие
.B \-fprintf
можно использовать для перечисления различных найденных элементов в несколько разных выходных файлов.
.P
Пожалуйста, обратите внимание, что
.B \-a
при указании неявно (например, двумя тестами, появляющимися без явного оператора между ними) или явно имеет более высокий приоритет, чем
.BR \-o .
Это означает, что
.B find . \-name afile \-o \-name bfile \-print
никогда не выведет
.IR afile .
.
.SH НЕОБЫЧНЫЕ ИМЕНА ФАЙЛОВ
Многие действия
.B find
приводят к выводу данных, которые находятся под контролем других пользователей. Это включает имена файлов, размеры, время изменения и так далее. Имена файлов являются потенциальной проблемой, поскольку они могут содержать любой символ, кроме `\e0' и `/'. Необычные символы в именах файлов могут приводить к неожиданным и часто нежелательным последствиям для вашего терминала (например, изменению настроек функциональных клавиш на некоторых терминалах). Необычные символы обрабатываются по-разному различными действиями, как описано ниже.

.IP "\-print0, \-fprint0"
Всегда выводить точное имя файла, без изменений, даже если вывод направлен на терминал.

.IP "\-ls, \-fls"
Необычные символы всегда экранируются. Пробелы, обратная косая черта и символы двойных кавычек выводятся с использованием экранирования в стиле C (например, `\ef', `\e\(dq'). Другие необычные символы выводятся с использованием восьмеричного экранирования. Другие печатные символы (для
.B \-ls
 и
.B \-fls
это символы между восьмеричными 041 и 0176) выводятся как есть.

.IP "\-printf, \-fprintf"
Если вывод не направлен на терминал, он выводится как есть.
В противном случае результат зависит от того, какая директива используется. Директивы %D, %F, %g, %G, %H, %Y и %y раскрываются в значения, которые не находятся под контролем владельцев файлов, поэтому они выводятся как есть. Директивы %a, %b, %c, %d, %i, %k, %m, %M, %n, %s, %t, %u и %U имеют значения, которые находятся под контролем владельцев файлов, но которые нельзя использовать для отправки произвольных данных на терминал, поэтому они выводятся как есть. Директивы %f, %h, %l, %p и %P заключаются в кавычки. Это заключение в кавычки выполняется так же, как для GNU
.BR ls .
Это не тот же механизм заключения в кавычки, который используется для
.B \-ls
 и
.BR \-fls .
Если вы можете решить, какой формат использовать для вывода
.B find
, то обычно лучше использовать `\e0' в качестве терминатора, чем символ новой строки, так как имена файлов могут содержать пробелы и символы новой строки. Настройка переменной окружения `LC_CTYPE' используется для определения того, какие символы необходимо заключать в кавычки.

.IP "\-print, \-fprint"
Заключение в кавычки обрабатывается так же, как для
.B \-printf
 и
.BR \-fprintf .
Если вы используете
.B find
в скрипте или в ситуации, где найденные файлы могут иметь произвольные имена, вам следует рассмотреть возможность использования
.B \-print0
вместо
.BR \-print .
.P
Действия
.B \-ok
 и
.B \-okdir
выводят текущее имя файла как есть. Это может измениться в будущем выпуске.
.
.SH "СООТВЕТСТВИЕ СТАНДАРТАМ"
Для максимального соответствия стандарту POSIX вам следует установить переменную окружения POSIXLY_CORRECT. Следующие параметры указаны в стандарте POSIX (IEEE Std 1003.1-2008, 2016 Edition):

.IP \fB\-H\fR
Этот параметр поддерживается.

.IP \fB\-L\fR
Этот параметр поддерживается.

.IP \fB\-name\fR
Этот параметр поддерживается, но соответствие POSIX зависит от соответствия POSIX библиотечной функции
.BR fnmatch (3)
системы. Начиная с findutils-4.2.2, метасимволы оболочки (например, `*', `?' или `[]') соответствуют ведущему `.', потому что интерпретация IEEE PASC 126 требует этого.
Это отличие от предыдущих версий findutils.

.IP \fB\-type\fR
Поддерживается.
POSIX определяет `b', `c', `d', `l', `p', `f' и `s'.
GNU find также поддерживает `D', представляющий Door, если ОС их предоставляет.
Более того, GNU find позволяет указывать несколько типов одновременно в списке, разделенном запятыми.

.IP \fB\-ok\fR
Поддерживается.
Интерпретация ответа соответствует шаблонам «yes» и «no», выбранным путем установки переменной окружения `LC_MESSAGES'.
Когда установлена переменная окружения `POSIXLY_CORRECT', эти шаблоны берутся из системного определения положительного (yes) или отрицательного (no) ответа. См. документацию системы по
.BR nl_langinfo (3),
в частности YESEXPR и NOEXPR.
Когда `POSIXLY_CORRECT' не установлена, шаблоны вместо этого берутся из собственного каталога сообщений
.BR find .

.IP \fB\-newer\fR
Поддерживается. Если указанный файл является символической ссылкой, он всегда разыменовывается. Это изменение по сравнению с предыдущим поведением, которое брало соответствующее время из символической ссылки; см. раздел ИСТОРИЯ ниже.

.IP \fB\-perm\fR
Поддерживается. Если переменная окружения POSIXLY_CORRECT не установлена, некоторые аргументы режима (например, +a+x), которые не являются допустимыми в POSIX, поддерживаются для обратной совместимости.

.IP "Другие первичные выражения"
Первичные выражения
.BR \-atime ,
.BR \-ctime ,
.BR \-depth ,
.BR \-exec ,
.BR \-group ,
.BR \-links ,
.BR \-mtime ,
.BR \-nogroup ,
.BR \-nouser ,
.BR \-ok ,
.BR \-path ,
.BR \-print ,
.BR \-prune ,
.BR \-size ,
.B \-user
и
.B \-xdev
все поддерживаются.

.P
Стандарт POSIX определяет скобки `(', `)', отрицание `!' и логические операторы И/ИЛИ
.B \-a
 и
.BR \-o .
.P
Все остальные параметры, предикаты, выражения и т.д. являются расширениями стандарта POSIX. Однако многие из этих расширений не являются уникальными для GNU find.
.P
Стандарт POSIX требует, чтобы
.B find
обнаруживал циклы:
.IP
Утилита
.B find
должна обнаруживать бесконечные циклы; то есть вход в ранее посещенный каталог, который является предком последнего встреченного файла. При обнаружении бесконечного цикла find должен записать диагностическое сообщение в стандартный вывод ошибок и либо восстановить свою позицию в иерархии, либо завершить работу.
.P
GNU
.B find
соответствует этим требованиям. Счетчик ссылок каталогов, которые содержат записи, являющиеся жесткими ссылками на предка, часто будет ниже, чем должен быть. Это может означать, что GNU find иногда оптимизирует посещение подкаталога, который на самом деле является ссылкой на предка. Поскольку
.B find
фактически не входит в такой подкаталог, ему разрешено не выдавать диагностическое сообщение. Хотя это поведение может быть несколько запутанным, маловероятно, что кто-то действительно зависит от него. Если оптимизация «листьев» была отключена с помощью
.BR \-noleaf ,
запись каталога всегда будет проверяться, и диагностическое сообщение будет выдано там, где это уместно. Символические ссылки нельзя использовать для создания циклов файловой системы как таковых, но если активен параметр
.B \-L
 или
.B \-follow
, выдается диагностическое сообщение, когда
.B find
сталкивается с циклом символических ссылок. Как и в случае с циклами, содержащими жесткие ссылки, оптимизация «листьев» часто означает, что
.B find
знает, что ему не нужно вызывать
.I stat()
 или
.I chdir()
 для символической ссылки, поэтому эта диагностика часто не является необходимой.
.P
Параметр
.B \-d
поддерживается для совместимости с различными системами BSD, но вам следует использовать соответствующий стандарту POSIX параметр
.B \-depth
вместо него.
.P
Переменная окружения POSIXLY_CORRECT не влияет на поведение тестов
.B \-regex
 или
.B \-iregex
, поскольку эти тесты не указаны в стандарте POSIX.
.
.SH "ПЕРЕМЕННЫЕ ОКРУЖЕНИЯ"

.IP LANG
Предоставляет значение по умолчанию для переменных интернационализации, которые не установлены или пусты.

.IP LC_ALL
Если установлено в непустое строковое значение, переопределяет значения всех остальных переменных интернационализации.

.IP LC_COLLATE
Стандарт POSIX указывает, что эта переменная влияет на сопоставление шаблонов, используемое для параметра
.B \-name
.
GNU find использует библиотечную функцию
.BR fnmatch (3)
, поэтому поддержка `LC_COLLATE' зависит от системной библиотеки.
Эта переменная также влияет на интерпретацию ответа на
.BR \-ok ;
хотя переменная `LC_MESSAGES' выбирает фактический шаблон, используемый для интерпретации ответа на
.BR \-ok ,
интерпретация любых выражений в квадратных скобках в шаблоне будет зависеть от `LC_COLLATE'.

.IP LC_CTYPE
Эта переменная влияет на обработку классов символов, используемых в регулярных выражениях, а также в тесте
.B \-name
, если системная библиотечная функция
.BR fnmatch (3)
поддерживает это. Эта переменная также влияет на интерпретацию любых классов символов в регулярных выражениях, используемых для интерпретации ответа на запрос, выданный
.BR \-ok .
Переменная окружения `LC_CTYPE' также влияет на то, какие символы считаются непечатными при выводе имен файлов; см. раздел НЕОБЫЧНЫЕ ИМЕНА ФАЙЛОВ.

.IP LC_MESSAGES
Определяет локаль, которая будет использоваться для интернационализированных сообщений. Если установлена переменная окружения `POSIXLY_CORRECT', это также определяет интерпретацию ответа на запрос, сделанный действием
.B \-ok
.

.IP NLSPATH
Определяет расположение каталогов сообщений интернационализации.

.IP PATH
Влияет на каталоги, которые просматриваются для поиска исполняемых файлов, вызываемых действиями
.BR \-exec ,
.BR \-execdir ,
.B \-ok
 и
.BR \-okdir .

.IP POSIXLY_CORRECT
Определяет размер блока, используемый
.B \-ls
 и
.BR \-fls .
Если
.B POSIXLY_CORRECT
установлена, блоки — это единицы по 512 байт. В противном случае это единицы по 1024 байта.
.IP
Установка этой переменной также отключает предупреждающие сообщения (т.е. подразумевает
.BR \-nowarn )
по умолчанию, поскольку POSIX требует, чтобы, помимо вывода для
.BR \-ok ,
все сообщения, напечатанные в stderr, были диагностическими и должны приводить к ненулевому статусу выхода.
.IP
Когда POSIXLY_CORRECT не установлена,
.B "\-perm \fI+zzz\fR"
обрабатывается так же, как
.B "\-perm \fI/zzz\fR"
, если \fI+zzz\fR не является допустимым символьным режимом. Когда POSIXLY_CORRECT установлена, такие конструкции рассматриваются как ошибка.
.IP
Когда POSIXLY_CORRECT установлена, ответ на запрос, сделанный действием
.B \-ok
, интерпретируется в соответствии с системным каталогом сообщений, в отличие от собственных переводов сообщений
.BR find .

.IP TZ
Влияет на часовой пояс, используемый для некоторых директив формата, связанных со временем, в
.B \-printf
 и
.BR \-fprintf .
.
.SH "ПРИМЕРЫ"
.\" A bulleted \[bu] list of examples.
.SS Простой подход `find|xargs`
.IP \[bu]
Найти файлы с именем
.I core
в каталоге
.I /tmp
или под ним и удалить их.
.nf
\&
.in +4m
.B $ find /tmp \-name core \-type f \-print | xargs /bin/rm \-f
.in
\&
.fi
Обратите внимание, что это будет работать некорректно, если есть какие-либо имена файлов, содержащие символы новой строки, одинарные или двойные кавычки или пробелы.
.
.SS Более безопасный подход `find -print0 | xargs -0`
.IP \[bu]
Найти файлы с именем \fIcore\fP в каталоге \fI/tmp\fP или под ним и удалить их, обрабатывая имена файлов таким образом, чтобы имена файлов или каталогов, содержащие одинарные или двойные кавычки, пробелы или символы новой строки, обрабатывались правильно.
.nf
\&
.in +4m
.B $ find /tmp \-name core \-type f \-print0 | xargs \-0 /bin/rm \-f
.in
\&
.fi
Тест
.B \-name
идет перед тестом
.B \-type
, чтобы избежать необходимости вызова
.B stat(2)
для каждого файла.
.PP
Обратите внимание, что между моментом, когда
.B find
обходит иерархию, выводя совпадающие имена файлов, и моментом, когда процесс, запущенный
.B xargs
, работает с этим файлом, все еще существует состояние состязания.

.SS
Выполнение команды для каждого файла
.IP \[bu]
Запустить
.I file
для каждого файла в текущем каталоге или под ним.
.nf
\&
.in +4m
.B $ find . \-type f \-exec file \(aq{}\(aq \e;
.in
\&
.fi
Обратите внимание, что фигурные скобки заключены в одинарные кавычки, чтобы защитить их от интерпретации как пунктуации сценария оболочки. Точка с запятой аналогичным образом защищена использованием обратной косой черты, хотя в этом случае также можно было использовать одинарные кавычки.
.PP
Во многих случаях можно предпочесть синтаксис
.B `\-exec\ \&...\&\ +`
или, что еще лучше,
.B `\-execdir\ \&...\&\ +`
по соображениям производительности и безопасности.
.
.SS Обход файловой системы только один раз — для 2 разных действий
.IP \[bu]
Обходить файловую систему только один раз, перечисляя файлы с установленным идентификатором пользователя (set-user-ID) и каталоги в
.I /root/suid.txt
, а большие файлы в
.IR /root/big.txt .
.nf
\&
.in +4m
.B $ find / \e
.in +4m
.B \e( \-perm \-4000 \-fprintf /root/suid.txt \(aq%#m %u %p\en\(aq \e) , \e
.br
.B \e( \-size +100M \-fprintf /root/big.txt  \(aq%\-10s %p\en\(aq \e)
.in -4m
.in -4m
\&
.fi
Этот пример использует символ продолжения строки \(aq\e\(aq в первых двух строках, чтобы указать оболочке продолжить чтение команды на следующей строке.
.
.SS
Поиск файлов по возрасту
.IP \[bu]
Искать файлы в вашем домашнем каталоге, которые были изменены за последние двадцать четыре часа.
.nf
\&
.in +4m
.B $ find $HOME  \-mtime 0
.in
\&
.fi
Эта команда работает таким образом, потому что время с момента последнего изменения каждого файла делится на 24 часа, а любой остаток отбрасывается. Это означает, что для соответствия
.B \-mtime
.BR 0 ,
файл должен был быть изменен в прошлом менее 24 часов назад.
.
.SS
Поиск файлов по правам доступа
.IP \[bu]
Искать файлы, которые являются исполняемыми, но не доступны для чтения.
.nf
\&
.in +4m
.B $ find /sbin /usr/sbin \-executable \e! \-readable \-print
.in
\&
.fi
.
.IP \[bu]
Искать файлы, которые имеют право чтения и записи для их владельца и группы, но которые другие пользователи могут читать, но не могут записывать.
.nf
\&
.in +4m
.B $ find . \-perm 664
.in
\&
.fi
Файлы, которые соответствуют этим критериям, но имеют установленные другие биты прав доступа (например, если кто-то может выполнить файл), не будут найдены.
.
.IP \[bu]
Искать файлы, которые имеют право чтения и записи для их владельца и группы, и которые другие пользователи могут читать, не обращая внимания на наличие каких-либо дополнительных битов прав доступа (например, бита исполнения).
.nf
\&
.in +4m
.B $ find . \-perm \-664
.in
\&
.fi
Это будет соответствовать файлу, который имеет режим
.IR 0777 ,
например.
.
.IP \[bu]
Искать файлы, которые доступны для записи кем-либо (их владельцем, или их группой, или кем-либо еще).
.nf
\&
.in +4m
.B $ find . \-perm /222
.in
\&
.fi
.
.IP \[bu]
Искать файлы, которые доступны для записи либо их владельцем, либо их группой.
.nf
\&
.in +4m
.B $ find . \-perm /220
.B $ find . \-perm /u+w,g+w
.B $ find . \-perm /u=w,g=w
.in
\&
.fi
Все три эти команды делают одно и то же, но первая использует восьмеричное представление режима файла, а две другие — символическую форму.
Файлы не обязательно должны быть доступны для записи и владельцем, и группой, чтобы быть найденными; достаточно любого из них.
.
.IP \[bu]
Искать файлы, которые доступны для записи и их владельцем, и их группой.
.nf
\&
.in +4m
.B $ find . \-perm \-220
.B $ find . \-perm \-g+w,u+w
.in
\&
.fi
Обе эти команды делают одно и то же.
.
.IP \[bu]
Более сложный поиск по правам доступа.
.nf
\&
.in +4m
.B $ find . \-perm \-444 \-perm /222 \e! \-perm /111
.B $ find . \-perm \-a+r \-perm /a+w \e! \-perm /a+x
.in
\&
.fi
Обе эти команды ищут файлы, которые доступны для чтения всем
.RB ( "\-perm \-444"
 или
.BR "\-perm \-a+r" ),
имеют хотя бы один бит записи
.RB ( "\-perm /222"
 или
.BR "\-perm /a+w" ),
но не являются исполняемыми ни для кого
.RB ( "! \-perm /111"
 или
.B ! \-perm /a+x
соответственно).
.
.SS
Пропуск - исключение файлов и подкаталогов
.IP \[bu]
Скопировать содержимое
.I /source-dir
в
.IR /dest-dir ,
но исключить файлы и каталоги с именем
.I .snapshot
(и все, что в них находится). Это также исключает файлы или каталоги, чье имя заканчивается на
.IR '\(ti' ,
но не их содержимое.
.nf
\&
.in +4m
.B $ cd /source-dir
.B $ find . \-name .snapshot \-prune \-o \e( \e! \-name \(aq*~\(aq \-print0 \e) \e
.br
.in +4m
.B | cpio \-pmd0  /dest-dir
.in -4m
.in -4m
\&
.fi
Конструкция
.B \-prune\ \-o\ \e(\ \&...\&\ \-print0\ \e)
довольно распространена. Идея здесь в том, что выражение перед
.B \-prune
соответствует вещам, которые должны быть пропущены. Однако само действие
.B \-prune
возвращает true, поэтому последующее
.B \-o
гарантирует, что правая часть вычисляется только для тех каталогов, которые не были пропущены (содержимое пропущенных каталогов даже не посещается, поэтому их содержимое не имеет значения). Выражение в правой части
.B \-o
заключено в скобки только для ясности. Оно подчеркивает, что действие
.B \-print0
происходит только для тех вещей, к которым не применялось
.B \-prune
. Поскольку условие «и» по умолчанию между тестами связывает сильнее, чем
.BR \-o ,
это поведение по умолчанию в любом случае, но скобки помогают показать, что происходит.
.
.IP \[bu]
Учитывая следующий каталог проектов и связанных с ними административных каталогов SCM, выполнить эффективный поиск корней проектов:
.nf
\&
.in +4m
.B $ find repo/ \e
.in +4m
.B \e( \-exec test \-d \(aq{}/.svn\(aq \e; \e
.B \-or \-exec test \-d \(aq{}/.git\(aq \e; \e
.B \-or \-exec test \-d \(aq{}/CVS\(aq \e; \e
.B \e) \-print \-prune
.in -4m
.in -4m
\&
.fi
Пример вывода:
.nf
\&
.in +4m
.B repo/project1/CVS
.B repo/gnu/project2/.svn
.B repo/gnu/project3/.svn
.B repo/gnu/project3/src/.svn
.B repo/project4/.git
.in
\&
.fi
В этом примере
.B \-prune
предотвращает ненужный спуск в каталоги, которые уже были обнаружены (например, мы не ищем в
.I project3/src
, потому что мы уже нашли
.IR project3/.svn ),
но гарантирует, что родственные каталоги
.RI ( project2
 и
.IR project3 )
будут найдены.
.
.SS
Другие полезные примеры
.IP \[bu]
Искать несколько типов файлов.
.nf
\&
.in +4m
.B $ find /tmp \-type f,d,l
.in
\&
.fi
Искать файлы, каталоги и символические ссылки в каталоге
.I /tmp
, передавая эти типы в виде списка, разделенного запятыми (расширение GNU), что в противном случае эквивалентно более длинному, но более переносимому:
.nf
\&
.in +4m
.B $ find /tmp \e( \-type f \-o \-type d \-o \-type l \e)
.in
\&
.fi
.
.IP \[bu]
Искать файлы с конкретным именем
.I needle
и немедленно остановиться, как только мы найдем первый из них.
.nf
\&
.in +4m
.B $ find / -name needle -print -quit
.in
\&
.fi
.
.IP \[bu]
Продемонстрировать интерпретацию директив формата
.B %f
 и
.B %h
действия
.B \-printf
для некоторых крайних случаев.
Вот пример, включающий некоторый вывод.
.nf
\&
.in +4m
.B $ find . .. / /tmp /tmp/TRACE compile compile/64/tests/find -maxdepth 0 -printf '[%h][%f]\en'
.B [.][.]
.B [.][..]
.B [][/]
.B [][tmp]
.B [/tmp][TRACE]
.B [.][compile]
.B [compile/64/tests][find]
.in
\&
.fi
.
.SH КОД ВЫХОДА
.B find
завершает работу со статусом 0, если все файлы успешно обработаны, и больше 0, если возникают ошибки.
Это намеренно очень общее описание, но если значение возврата ненулевое, вам не следует полагаться на правильность результатов
.BR find .

Когда возникает какая-либо ошибка,
.B find
может немедленно остановиться, не выполнив все указанные действия.
Например, некоторые отправные точки могли быть не исследованы, или некоторые ожидающие вызовы программ для
.B \-exec\ \&...\&\ {}\ +
 или
.B "\-execdir\ \&...\&\ {}\ +
могли не быть выполнены.
.
.SH "ИСТОРИЯ"
Начиная с findutils-4.2.2, метасимволы оболочки (например, `*', `?' или `[]'), используемые в шаблонах имен файлов, соответствуют ведущему `.', потому что интерпретация IEEE POSIX 126 требует этого.
.P
Начиная с findutils-4.3.3,
.B \-perm\ /000
теперь соответствует всем файлам вместо того, чтобы не соответствовать ни одному.
.P
Временные метки с наносекундным разрешением были реализованы в findutils-4.3.3.
.P
Начиная с findutils-4.3.11, действие
.B \-delete
устанавливает статус выхода
.B find
в ненулевое значение при сбое.
Однако
.B find
не завершит работу немедленно. Ранее статус выхода
.B find
не затрагивался сбоем
.BR \-delete .
.TS
l l l .
Возможность	Добавлено в	Также встречается в
\-newerXY	4.3.3	BSD
\-D	4.3.1
\-O	4.3.1
\-readable	4.3.0
\-writable	4.3.0
\-executable	4.3.0
\-regextype	4.2.24
\-exec ... +	4.2.12	POSIX
\-execdir	4.2.12	BSD
\-okdir	4.2.12
\-samefile	4.2.11
\-H	4.2.5	POSIX
\-L	4.2.5	POSIX
\-P	4.2.5	BSD
\-delete	4.2.3
\-quit	4.2.3
\-d	4.2.3	BSD
\-wholename	4.2.0
\-iwholename	4.2.0
\-ignore_readdir_race	4.2.0
\-fls	4.0
\-ilname	3.8
\-iname	3.8
\-ipath	3.8
\-iregex	3.8
.TE
.P
Синтаксис
\.B \-perm +MODE
был удален в findutils-4.5.12 в пользу
\.B \-perm
.BR /MODE .
Синтаксис
.B +MODE
считался устаревшим начиная с findutils-4.2.21, выпущенной в 2005 году.
.
.SH "НЕ-ОШИБКИ"
.SS Неожиданный приоритет операторов
Команда
.B find . \-name afile \-o \-name bfile \-print
никогда не выведет
.I afile
, потому что это на самом деле эквивалентно
.BR "find . \-name afile \-o \e( \-name bfile \-a \-print \e)" .
Помните, что приоритет
.B \-a
выше, чем у
.B \-o
, и когда между тестами не указан оператор, предполагается
.B \-a
.
.SS Сообщение об ошибке \(lqpaths must precede expression\(rq
.nf
.B $ find . \-name *.c \-print
find: paths must precede expression
find: possible unquoted pattern after predicate `-name'?
.fi
.P
Это происходит, когда оболочка может раскрыть шаблон
.I *.c
в более чем одно имя файла, существующее в текущем каталоге, и передать полученные имена файлов в командной строке для
.B find
вот так:
.nf
.
.B find . \-name frcode.c locate.c word_io.c \-print
.
.fi
Эта команда, конечно, не будет работать, потому что предикат
.B \-name
допускает ровно один шаблон в качестве аргумента. Вместо того чтобы делать это таким образом, вам следует заключить шаблон в кавычки или экранировать подстановочный знак, тем самым позволяя
.B find
использовать шаблон с подстановочным знаком во время поиска для сопоставления имен файлов вместо имен файлов, раскрытых родительской оболочкой:
.nf
.B $ find . \-name \(aq*.c\(aq \-print
.B $ find . \-name \e*.c \-print
.fi
.
.SH "ОШИБКИ"
Существуют проблемы безопасности, присущие поведению, которое стандарт POSIX определяет для
.BR find ,
и которые поэтому невозможно исправить. Например, действие
.B \-exec
по своей сути небезопасно, и вместо него следует использовать
.B \-execdir
.
.P
Переменная окружения
.B  LC_COLLATE
не оказывает никакого влияния на действие
.B \-ok
.
.
.SH "СООБЩЕНИЕ ОБ ОШИБКАХ"
Онлайн-справка GNU findutils: <https://www.gnu.org/software/findutils/#get-help>
.br
Сообщайте о любых ошибках перевода по адресу <https://translationproject.org/team/>
.PP
Сообщайте о любых других проблемах через форму в баг-трекере GNU Savannah:
.RS
<https://savannah.gnu.org/bugs/?group=findutils>
.RE
Общие темы по пакету GNU findutils обсуждаются в списке рассылки
.I bug\-findutils
:
.RS
<https://lists.gnu.org/mailman/listinfo/bug-findutils>
.RE
.
.SH АВТОРСКИЕ ПРАВА
Copyright \(co 1990-2021 Free Software Foundation, Inc.
Лицензия GPLv3+: GNU GPL версии 3 или более поздней <https://gnu.org/licenses/gpl.html>.
.br
Это свободное программное обеспечение: вы можете изменять и распространять его.
НИКАКИХ ГАРАНТИЙ, в пределах, разрешенных законом.
.
.SH "СМ. ТАКЖЕ"
.BR chmod (1),
.BR locate (1),
.BR ls (1),
.BR updatedb (1),
.BR xargs (1),
.BR lstat (2),
.BR stat (2),
.BR ctime (3)
.BR fnmatch (3),
.BR printf (3),
.BR strftime (3),
.BR locatedb (5),
.BR regex (7)
.PP
Полная документация <https://www.gnu.org/software/findutils/find>
.br
или доступна локально через:
.B info find
