.\" GNU grep man page
.de dT
.ds Dt \\$2
..
.dT Time-stamp: "2019-12-29"
.\" Update the above date whenever a change to either this file or
.\" grep.c's 'usage' function results in a nontrivial change to the man page.
.\" In Emacs, you can update the date by running 'M-x time-stamp'
.\" after you make a change that you decide is nontrivial.
.\" It is no big deal to forget to update the date.
.
.TH GREP 1 \*(Dt "GNU grep 3.7" "User Commands"
.
.if !\w|\*(lq| \{\
.\" groff an-old.tmac does not seem to be in use, so define lq and rq.
.	ie \n(.g \{\
.		ds lq \(lq\"
.		ds rq \(rq\"
.	\}
.	el \{\
.		ds lq ``
.		ds rq ''
.	\}
.\}
.
.if !\w|\*(la| \{\
.\" groff an-ext.tmac does not seem to be in use, so define the parts of
.\" it that are used below.  For a copy of groff an-ext.tmac, please see:
.\" https://git.savannah.gnu.org/cgit/groff.git/plain/tmac/an-ext.tmac
.\" --- Start of lines taken from groff an-ext.tmac
.
.\" Check whether we are using grohtml.
.nr mH 0
.if \n(.g \
.  if '\*(.T'html' \
.    nr mH 1
.
.
.\" Map mono-width fonts to standard fonts for groff's TTY device.
.if n \{\
.  do ftr CR R
.  do ftr CI I
.  do ftr CB B
.\}
.
.\" groff has glyph entities for angle brackets.
.ie \n(.g \{\
.  ds la \(la\"
.  ds ra \(ra\"
.\}
.el \{\
.  ds la <\"
.  ds ra >\"
.  \" groff's man macros control hyphenation with this register.
.  nr HY 1
.\}
.
.\" Start URL.
.de UR
.  ds m1 \\$1\"
.  nh
.  if \\n(mH \{\
.    \" Start diversion in a new environment.
.    do ev URL-div
.    do di URL-div
.  \}
..
.
.
.\" End URL.
.de UE
.  ie \\n(mH \{\
.    br
.    di
.    ev
.
.    \" Has there been one or more input lines for the link text?
.    ie \\n(dn \{\
.      do HTML-NS "<a href=""\\*(m1"">"
.      \" Yes, strip off final newline of diversion and emit it.
.      do chop URL-div
.      do URL-div
\c
.      do HTML-NS </a>
.    \}
.    el \
.      do HTML-NS "<a href=""\\*(m1"">\\*(m1</a>"
\&\\$*\"
.  \}
.  el \
\\*(la\\*(m1\\*(ra\\$*\"
.
.  hy \\n(HY
..
.
.
.\" Start email address.
.de MT
.  ds m1 \\$1\"
.  nh
.  if \\n(mH \{\
.    \" Start diversion in a new environment.
.    do ev URL-div
.    do di URL-div
.  \}
..
.
.
.\" End email address.
.de ME
.  ie \\n(mH \{\
.    br
.    di
.    ev
.
.    \" Has there been one or more input lines for the link text?
.    ie \\n(dn \{\
.      do HTML-NS "<a href=""mailto:\\*(m1"">"
.      \" Yes, strip off final newline of diversion and emit it.
.      do chop URL-div
.      do URL-div
\c
.      do HTML-NS </a>
.    \}
.    el \
.      do HTML-NS "<a href=""mailto:\\*(m1"">\\*(m1</a>"
\&\\$*\"
.  \}
.  el \
\\*(la\\*(m1\\*(ra\\$*\"
.
.  hy \\n(HY
..
.\" --- End of lines taken from groff an-ext.tmac
.\}
.
.hy 0
.
.SH ИМЯ
grep, egrep, fgrep, rgrep \- печатает строки, соответствующие шаблонам
.
.SH СИНТАКСИС
.B grep
.RI [ OPTION .\|.\|.]\&
.I PATTERNS
.RI [ FILE .\|.\|.]
.br
.B grep
.RI [ OPTION .\|.\|.]\&
.B \-e
.I PATTERNS
\&.\|.\|.\&
.RI [ FILE .\|.\|.]
.br
.B grep
.RI [ OPTION .\|.\|.]\&
.B \-f
.I PATTERN_FILE
\&.\|.\|.\&
.RI [ FILE .\|.\|.]
.
.SH ОПИСАНИЕ
.B grep
ищет
.I PATTERNS
в каждом
.IR FILE .
.I PATTERNS
— один или более шаблонов, разделённых символами новой строки, и
.B grep
выводит каждую строку, совпадающую с шаблоном.
Обычно
.I PATTERNS
следует заключать в кавычки, когда
.B grep
используется в командной оболочке.
.PP
.I FILE
равный .RB "\*(lq" \- "\*(rq"
обозначает стандартный ввод.
Если
.I FILE
не указан, рекурсивный поиск исследует текущий каталог, а нерекурсивный читает стандартный ввод.
.PP
Кроме того, программы‑варианты
.BR egrep ,
.B fgrep
и
.B rgrep
эквивалентны соответственно
.BR "grep\ \-E" ,
.BR "grep\ \-F" ,
и
.BR "grep\ \-r" .
Эти варианты устарели, но сохраняются для совместимости.
.
.SH ПАРАМЕТРЫ
.SS "Общая информация о программе"
.TP
.B \-\^\-help
Вывести сообщение о применении и завершить работу.
.TP
.BR \-V ", " \-\^\-version
Вывести номер версии
.B grep
и завершить работу.
.SS "Синтаксис шаблонов"
.TP
.BR \-E ", " \-\^\-extended\-regexp
Интерпретировать
.I PATTERNS
как расширенные регулярные выражения (ERE, см. ниже).
.TP
.BR \-F ", " \-\^\-fixed\-strings
Интерпретировать
.I PATTERNS
как фиксированные строки, а не как регулярные выражения.
.TP
.BR \-G ", " \-\^\-basic\-regexp
Интерпретировать
.I PATTERNS
как базовые регулярные выражения (BRE, см. ниже).
Это поведение по умолчанию.
.TP
.BR \-P ", " \-\^\-perl\-regexp
Интерпретировать
.I PATTERNS
как совместимые с Perl регулярные выражения (PCRE).
Этот параметр экспериментален в сочетании с параметром
.B \-z
.RB ( \-\^\-null\-data )
и
.B "grep \-P"
может выдавать предупреждения о нереализованных возможностях.
.SS "Управление совпадением"
.TP
.BI \-e " PATTERNS" "\fR,\fP \-\^\-regexp=" PATTERNS
Использовать
.I PATTERNS
в качестве шаблонов.
Если параметр указан несколько раз или используется вместе с
.B \-f
.RB ( \-\^\-file )
то ищутся все указанные шаблоны.
Этот параметр позволяет защитить шаблон, начинающийся с \*(lq\-\*(rq.
.TP
.BI \-f " FILE" "\fR,\fP \-\^\-file=" FILE
Получать шаблоны из
.IR FILE ,
по одному на строку.
Если параметр указан несколько раз или используется вместе с
.B \-e
.RB ( \-\^\-regexp )
то ищутся все указанные шаблоны.
Пустой файл содержит ноль шаблонов и, следовательно, ничего не совпадает.
.TP
.BR \-i ", " \-\^\-ignore\-case
Игнорировать различия регистра в шаблонах и входных данных, так что символы, различающиеся только регистром, считаются совпадающими.
.TP
.B \-\^\-no\-ignore\-case
Не игнорировать различия регистра в шаблонах и входных данных.
Это значение по умолчанию.
Параметр полезен для передачи скриптам оболочки, которые уже используют
.BR \-i ,
чтобы отменить его действие, поскольку два параметра взаимно переопределяют друг друга.
.TP
.BR \-v ", " \-\^\-invert\-match
Инвертировать смысл совпадения, выбирая строки, не соответствующие шаблону.
.TP
.BR \-w ", " \-\^\-word\-regexp
Выбирать только те строки, где совпадения образуют полные слова.
Тест заключается в том, что совпадающая подстрока должна находиться либо в начале строки, либо предшествоваться символом, не являющимся частью слова.
Аналогично, она должна находиться в конце строки или за ней должен быть символ, не являющийся частью слова.
К символам, составляющим слово, относятся буквы, цифры и подчёркивание.
Этот параметр не действует, если одновременно указано
.B \-x
.
.TP
.BR \-x ", " \-\^\-line\-regexp
Выбирать только те совпадения, которые точно соответствуют всей строке.
Для шаблона в виде регулярного выражения это эквивалентно заключению шаблона в скобки и добавлению
.B ^
и
.BR $ .
.TP
.B \-y
Устаревший синоним для
.BR \-i .
.SS "Общее управление выводом"
.TP
.BR \-c ", " \-\^\-count
Подавить обычный вывод; вместо этого вывести количество строк, совпавших с шаблоном, для каждого входного файла.
С параметром
.BR \-v ", " \-\^\-invert\-match
(см. ниже) выводится количество строк, не совпавших с шаблоном.
.TP
.BR \-\^\-color [ =\fIWHEN\fP "], " \-\^\-colour [ =\fIWHEN\fP ]
Окрасить найденные (непустые) строки, совпадающие строки, строки контекста, имена файлов, номера строк, смещения в байтах и разделители (для полей и групп строк контекста) управляющими последовательностями для отображения их цветом в терминале.
Цвета задаются переменной окружения
.BR GREP_COLORS .
Устаревшая переменная
.B GREP_COLOR
по‑прежнему поддерживается, но её значение не имеет приоритета.
.I WHEN
может принимать значения
.BR never ", " always ", or " auto .
.TP
.BR \-L ", " \-\^\-files\-without\-match
Подавить обычный вывод; вместо этого вывести имя каждого входного файла, из которого не было бы выведено ничего.
.TP
.BR \-l ", " \-\^\-files\-with\-matches
Подавить обычный вывод; вместо этого вывести имя каждого входного файла, из которого обычно выводится результат.
Сканирование каждого входного файла прекращается после первого совпадения.
.TP
.BI \-m " NUM" "\fR,\fP \-\^\-max\-count=" NUM
Прекратить чтение файла после
.I NUM
совпавших строк.
Если входом является стандартный ввод из обычного файла, и
.I NUM
совпавших строк было выведено,
.B grep
перемещает позицию стандартного ввода сразу после последней совпавшей строки перед завершением, независимо от наличия завершающих строк контекста.
Это позволяет вызывающему процессу возобновить поиск.
Когда
.B grep
останавливается после
.I NUM
совпавших строк, он выводит любые завершающие строки контекста.
Если одновременно указаны параметры
.B \-c
или
.B \-\^\-count,
.B grep
не выводит количество, превышающее
.IR NUM .
Если одновременно указаны параметры
.B \-v
или
.B \-\^\-invert\-match,
.B grep
останавливается после вывода
.I NUM
строк, не совпавших с шаблоном.
.TP
.BR \-o ", " \-\^\-only\-matching
Выводить только совпавшие (непустые) части строки, каждая часть в отдельной строке вывода.
.TP
.BR \-q ", " \-\^\-quiet ", " \-\^\-silent
Тихий режим; ничего не выводить в стандартный вывод.
Немедленно завершить с кодом возврата 0, если найдено любое совпадение, даже если была обнаружена ошибка.
См. также параметры
.B \-s
или
.B \-\^\-no\-messages .
.TP
.BR \-s ", " \-\^\-no\-messages
Подавить сообщения об ошибках, связанных с несуществующими или нечитаемыми файлами.
.SS "Управление префиксом строк вывода"
.TP
.BR \-b ", " \-\^\-byte\-offset
Выводить смещение в байтах (нумерация с нуля) внутри входного файла перед каждой строкой вывода.
Если указано
.B \-o
.RB ( \-\^\-only\-matching ),
выводится смещение самой совпавшей части.
.TP
.BR \-H ", " \-\^\-with\-filename
Выводить имя файла перед каждой совпавшей строкой.
Это значение по умолчанию, если ищется более одного файла.
Это расширение GNU.
.TP
.BR \-h ", " \-\^\-no\-filename
Не выводить имена файлов в начале строк вывода.
Это значение по умолчанию, если ищется только один файл (или только стандартный ввод).
.TP
.BI \-\^\-label= LABEL
Отображать вход, поступающий со стандартного ввода, как если бы он исходил из файла
.IR LABEL .
Это может быть полезно для команд, которые преобразуют содержимое файла перед поиском,
например,
.BR "gzip \-cd foo.gz | grep \-\^\-label=foo \-H 'some pattern'" .
См. также параметр
.B \-H .
.TP
.BR \-n ", " \-\^\-line\-number
Префиксировать каждую строку вывода номером строки (нумерация с единицы) внутри её входного файла.
.TP
.BR \-T ", " \-\^\-initial\-tab
Убедиться, что первый символ реального содержания строки находится на табуляции, чтобы выравнивание табуляций выглядело нормально.
Это полезно с параметрами, которые добавляют свои префиксы к содержимому:
.BR \-H , \-n ,
и
.BR \-b .
Для повышения вероятности того, что строки из одного файла начнутся в одной колонке,
это также заставляет номер строки и смещение в байтах (если присутствуют) выводиться в поле минимальной ширины.
.TP
.BR \-Z ", " \-\^\-null
Выводить нулевой байт (символ ASCII
.B NUL
) вместо обычного разделителя после имени файла.
Например,
.B "grep \-lZ"
выводит нулевой байт после каждого имени файла вместо обычного символа новой строки.
Этот параметр делает вывод однозначным, даже если имена файлов содержат необычные символы, такие как новые строки.
Его можно использовать вместе с командами
.BR "find \-print0" ,
.BR "perl \-0" ,
.BR "sort \-z" ,
и
.B "xargs \-0"
для обработки произвольных имён файлов, даже содержащих символы новой строки.
.SS "Управление строками контекста"
.TP
.BI \-A " NUM" "\fR,\fP \-\^\-after\-context=" NUM
Вывести
.I NUM
строк последующего контекста после каждой совпавшей строки.
Между соседними группами совпадений вставляется строка‑разделитель
.RB ( \-\^\- ).
С параметром
.B \-o
или
.B \-\^\-only\-matching
это не имеет эффекта; выводится предупреждение.
.TP
.BI \-B " NUM" "\fR,\fP \-\^\-before\-context=" NUM
Вывести
.I NUM
строк предшествующего контекста перед каждой совпавшей строкой.
Между соседними группами совпадений вставляется строка‑разделитель
.RB ( \-\^\- ).
С параметром
.B \-o
или
.B \-\^\-only\-matching
это не имеет эффекта; выводится предупреждение.
.TP
.BI \-C " NUM" "\fR,\fP \-" NUM "\fR,\fP \-\^\-context=" NUM
Вывести
.I NUM
строк контекста (до и после) вокруг каждой совпавшей строки.
Между соседними группами совпадений вставляется строка‑разделитель
.RB ( \-\^\- ).
С параметром
.B \-o
или
.B \-\^\-only\-matching
это не имеет эффекта; выводится предупреждение.
.TP
.BI \-\^\-group\-separator= SEP
Когда используются
.BR \-A ,
.BR \-B ,
или
.B \-C
, вместо
.B \-\^\-
выводить
.I SEP
между группами строк.
.TP
.B \-\^\-no\-group\-separator
Когда используются
.BR \-A ,
.BR \-B ,
или
.B \-C
, не выводить разделитель между группами строк.
.SS "Выбор файлов и каталогов"
.TP
.BR \-a ", " \-\^\-text
Обрабатывать бинарный файл как текстовый; это эквивалент параметра
.B \-\^\-binary\-files=text
.
.TP
.BI \-\^\-binary\-files= TYPE
Если данные или метаданные файла указывают, что файл содержит бинарные данные,
предполагать, что тип файла
.IR TYPE .
Небинарные байты указывают на бинарные данные; это либо байты вывода, некорректно закодированные для текущей локали, либо нулевые входные байты, когда параметр
.B \-z
не указан.
.IP
По умолчанию
.I TYPE
равен
.BR binary ,
и
.B grep
подавляет вывод после обнаружения нулевых бинарных данных,
а также подавляет строки вывода, содержащие некорректно закодированные данные.
Когда часть вывода подавлена,
.B grep
добавляет одну строку‑сообщение о том, что найден бинарный файл.
.IP
Если
.I TYPE
равен
.BR without\-match ,
при обнаружении нулевых бинарных данных
.B grep
предполагает, что остальная часть файла не совпадает; это эквивалент параметра
.B \-I .
.IP
Если
.I TYPE
равен
.BR text ,
.B grep
обрабатывает бинарный файл как текстовый; это эквивалент параметра
.B \-a .
.IP
Когда
.I type
равен
.BR binary ,
.B grep
может рассматривать небинарные байты как разделители строк даже без параметра
.B \-z
. Это значит, что выбор между
.B binary
и
.B text
может влиять на то, совпадает ли шаблон с файлом. Например, когда
.I type
равен
.B binary
шаблон
.B q$
может совпадать с
.B q
сразу после нулевого байта, хотя при
.I type
равном
.BR text
это не происходит.
Обратно, при
.I type
равном
.B binary
шаблон
.B .\&
(точка) может не совпадать с нулевым байтом.
.IP
\fIWarning\fR:
Параметр
.B \-a
может выводить бинарный мусор, что может иметь неприятные побочные эффекты, если вывод направлен в терминал и драйвер терминала интерпретирует часть вывода как команды.
С другой стороны, при чтении файлов с неизвестными кодировками может быть полезно использовать
.B \-a
или установить
.B LC_ALL='C'
в окружении, чтобы находить больше совпадений, даже если они небезопасны для прямого отображения.
.TP
.BI \-D " ACTION" "\fR,\fP \-\^\-devices=" ACTION
Если входной файл является устройством, FIFO или сокетом, использовать
.I ACTION
для его обработки.
По умолчанию
.I ACTION
равен
.BR read ,
что означает чтение устройств так же, как обычных файлов.
Если
.I ACTION
равен
.BR skip ,
устройства пропускаются без сообщений.
.TP
.BI \-d " ACTION" "\fR,\fP \-\^\-directories=" ACTION
Если входной файл является каталогом, использовать
.I ACTION
для его обработки.
По умолчанию
.I ACTION
равен
.BR read ,
т.е. каталоги читаются как обычные файлы.
Если
.I ACTION
равен
.BR skip ,
каталоги пропускаются без сообщений.
Если
.I ACTION
равен
.BR recurse ,
рекурсивно читаются все файлы в каждом каталоге, следуя символическим ссылкам только если они указаны в командной строке.
Это эквивалент параметра
.B \-r
.
.TP
.BI \-\^\-exclude= GLOB
Пропускать любой файл из командной строки, имя которого заканчивается шаблоном
.IR GLOB ,
используя подстановку; суффикс имени может быть либо полным именем, либо конечной частью, начинающейся после символа, не являющегося слешем, сразу после слеша
.RB ( / )
в имени.
При рекурсивном поиске пропускать любой подфайл, базовое имя которого соответствует
.IR GLOB ;
базовое имя — часть после последнего слеша.
Шаблон может использовать
.BR * ,
.BR ? ,
и
.BR [ .\|.\|. ]\&
в качестве подстановочных знаков, а
.B \e
для экранирования подстановочного знака или обратного слеша.
.TP
.BI \-\^\-exclude\-from= FILE
Пропускать файлы, базовое имя которых соответствует любому из шаблонов, прочитанных из
.I FILE
(используя подстановку, как описано в
.BR \-\^\-exclude )
.
.TP
.BI \-\^\-exclude\-dir= GLOB
Пропускать любой каталог из командной строки, суффикс имени которого соответствует шаблону
.IR GLOB .
При рекурсивном поиске пропускать любой подкаталог, базовое имя которого соответствует
.IR GLOB .
Игнорировать любые избыточные завершающие слеши в
.IR GLOB .
.TP
.BR \-I
Обрабатывать бинарный файл так, как если бы в нём не было совпадающих данных; это эквивалент параметра
.B \-\^\-binary\-files=without\-match
.
.TP
.BI \-\^\-include= GLOB
Искать только файлы, базовое имя которых соответствует
.I GLOB
(используя подстановку, как описано в
.BR \-\^\-exclude )
. Если заданы противоречивые параметры
.B \-\^\-include
и
.B \-\^\-exclude
, последняя совпавшая опция имеет приоритет.
Если ни один из параметров
.B \-\^\-include
или
.B \-\^\-exclude
не совпадает, файл включается, если первая такая опция была
.BR \-\^\-exclude .
.TP
.BR \-r ", " \-\^\-recursive
Рекурсивно читать все файлы в каждом каталоге, следуя символическим ссылкам только если они указаны в командной строке.
Обратите внимание, что если не указано ни одного файлового операнда,
.B grep
поискает в текущем каталоге.
Это эквивалент параметра
.B "\-d recurse"
.
.TP
.BR \-R ", " \-\^\-dereference\-recursive
Рекурсивно читать все файлы в каждом каталоге, следуя всем символическим ссылкам, в отличие от
.BR \-r .
.SS "Прочие параметры"
.TP
.B \-\^\-line\-buffered
Использовать буферизацию по строкам при выводе.
Это может привести к потере производительности.
.TP
.BR \-U ", " \-\^\-binary
Обрабатывать файл(ы) как бинарные.
По умолчанию в MS-DOS и MS-Windows
.B grep
пытается определить, является ли файл текстовым или бинарным, как описано для параметра
.B \-\^\-binary\-files
.
Если
.B grep
решает, что файл текстовый, он удаляет символы CR из исходного содержимого файла (чтобы регулярные выражения с
.B ^
и
.B $
работали корректно).
Указание
.B \-U
переписывает эту догадку, заставляя все файлы читаться и передаваться в механизм сопоставления без изменений; если файл текстовый с парами CR/LF в конце каждой строки, это может привести к сбоям некоторых регулярных выражений.
Этот параметр не влияет на платформы, отличные от MS-DOS и MS-Windows.
.TP
.BR \-z ", " \-\^\-null\-data
Обрабатывать входные и выходные данные как последовательности строк, каждая из которых завершается нулевым байтом (символ ASCII NUL) вместо символа новой строки.
Как и параметр
.B \-Z
или
.B \-\^\-null
, его можно использовать с командами вроде
.B sort -z
для обработки произвольных имён файлов.
.
.SH "РЕГУЛЯРНЫЕ ВЫРАЖЕНИЯ"
Регулярное выражение — это шаблон, описывающий набор строк.
Регулярные выражения формируются аналогично арифметическим выражениям, используя различные операторы для объединения более простых выражений.
.PP
.B grep
понимает три разных версии синтаксиса регулярных выражений:
\*(lqbasic\*(rq (BRE), \*(lqextended\*(rq (ERE) и \*(lqperl\*(rq (PCRE).
В GNU
.B grep
нет различий в доступных возможностях между базовым и расширенным синтаксисом.
В других реализациях базовые регулярные выражения менее мощные.
Следующее описание относится к расширенным регулярным выражениям; различия для базовых регулярных выражений суммированы ниже.
Регулярные выражения, совместимые с Perl, предоставляют дополнительные возможности и документированы в B<pcresyntax>(3) и B<pcrepattern>(3), но работают только при включённой поддержке PCRE.
.PP
Основные строительные блоки — это регулярные выражения, которые сопоставляют один символ.
Большинство символов, включая все буквы и цифры, являются регулярными выражениями, сопоставляющими себя.
Любой метасимвол со специальным значением может быть экранирован обратным слешем.
.PP
Точка
.B .\&
совпадает с любым одиночным символом.
Не указано, будет ли она совпадать с ошибкой кодировки.
.SS "Классы символов и скобочные выражения"
\*(lqBracket expression\*(rq — это список символов, заключённый между
.B [
и
.BR ] .
Он совпадает с любым одиночным символом из этого списка.
Если первым символом списка является карет
.B ^
, он совпадает с любым символом,
.I не
входящим в список; не указано, будет ли он совпадать с ошибкой кодировки.
Например, регулярное выражение
.B [0123456789]
совпадает с любой отдельной цифрой.
.PP
Внутри скобочного выражения \*(lqrange expression\*(rq состоит из двух символов, разделённых дефисом.
Он совпадает с любым одиночным символом, который находится между двумя символами включительно, используя локальную последовательность сортировки и набор символов.
Например, в локали C по умолчанию
.B [a\-d]
эквивалентно
.BR [abcd] .
Во многих локалях символы сортируются в словарном порядке, и в этих локалях
.B [a\-d]
обычно не эквивалентно
.BR [abcd] ;
это может быть эквивалентно, например,
.BR [aBbCcDd] .
Для получения традиционной интерпретации скобочных выражений можно использовать локаль C, задав переменную окружения
.B LC_ALL
в значение
.BR C .
.PP
Наконец, внутри скобочных выражений предопределены некоторые именованные классы символов:
.BR [:alnum:] ,
.BR [:alpha:] ,
.BR [:blank:] ,
.BR [:cntrl:] ,
.BR [:digit:] ,
.BR [:graph:] ,
.BR [:lower:] ,
.BR [:print:] ,
.BR [:punct:] ,
.BR [:space:] ,
.BR [:upper:] ,
и
.BR [:xdigit:] .
Их имена говорящие сами за себя.
Например,
.B [[:alnum:]]
означает класс символов цифр и букв в текущей локали.
В локали C и кодировке ASCII это то же самое, что
.BR [0\-9A\-Za\-z] .
(Обратите внимание, что квадратные скобки в этих именах являются частью символических имён и должны присутствовать в дополнение к скобкам, ограничивающим скобочное выражение.)
Большинство метасимволов теряют своё специальное значение внутри скобочных выражений.
Чтобы включить буквальный
.B ]
разместите его первым в списке.
Аналогично, чтобы включить буквальный
.B ^
разместите его где‑угодно, кроме первого.
Наконец, чтобы включить буквальный
.B \-
разместите его последним.
.SS "Якорение"
Карет
.B ^
и знак доллара
.B $
— метасимволы, которые соответственно совпадают с пустой строкой в начале и в конце строки.
.SS "Символ обратного слеша и специальные выражения"
Символы
.B \e<
и
.B \e>
соответственно совпадают с пустой строкой в начале и в конце слова.
Символ
.B \eb
совпадает с пустой строкой на границе слова,
а
.B \eB
совпадает с пустой строкой, если он
.I не
на границе слова.
Символ
.B \ew
является синонимом
.B [_[:alnum:]]
а
.B \eW
— синонимом
.BR [^_[:alnum:]] .
.SS "Повторения"
Регулярное выражение может быть дополнено одним из нескольких операторов повторения:
.PD 0
.TP
.B ?
Предшествующий элемент необязателен и может встретиться не более одного раза.
.TP
.B *
Предшествующий элемент может встретиться ноль или более раз.
.TP
.B +
Предшествующий элемент может встретиться один или более раз.
.TP
.BI { n }
Предшествующий элемент встречается ровно
.I n
раз.
.TP
.BI { n ,}
Предшествующий элемент встречается
.I n
или более раз.
.TP
.BI {, m }
Предшествующий элемент встречается не более
.I m
раз.
Это расширение GNU.
.TP
.BI { n , m }
Предшествующий элемент встречается как минимум
.I n
раз, но не более
.I m
раз.
.PD
.SS "Конкатенация"
Два регулярных выражения могут быть конкатенированы; получившееся регулярное выражение совпадает с любой строкой, образованной конкатенацией двух подстрок, которые соответственно совпадают с конкатенированными выражениями.
.SS "Альтернация"
Два регулярных выражения могут быть соединены инфиксным оператором
.BR | ;
результирующее регулярное выражение совпадает с любой строкой, совпадающей с любым из альтернативных выражений.
.SS "Приоритет"
Повторения имеют более высокий приоритет, чем конкатенация, а конкатенация — более высокий, чем альтернация.
Всю выражение можно заключить в скобки, чтобы переопределить эти правила приоритета и сформировать подвыражение.
.SS "Обратные ссылки и подвыражения"
Обратная ссылка
.BI \e n\c
\&, где
.I n
— одна цифра, совпадает с подстрокой, ранее совпавшей с
.IR n th
скобочным подвыражением регулярного выражения.
.SS "Базовые vs расширенные регулярные выражения"
В базовых регулярных выражениях метасимволы
.BR ? ,
.BR + ,
.BR { ,
.BR | ,
.BR ( ,
и
.BR )
теряют своё специальное значение; вместо этого используются экранированные версии
.BR \e? ,
.BR \e+ ,
.BR \e{ ,
.BR \e| ,
.BR \e( ,
и
.BR \e) .
.
.SH КОД ВЫХОДА
Обычно код выхода равен 0, если строка выбрана, 1 — если строк не выбрано, и 2 — если произошла ошибка. Однако если использованы параметры
.B \-q
или
.B \-\^\-quiet
или
.B \-\^\-silent
и строка выбрана, код выхода будет 0 даже при наличии ошибки.
.
.SH ПЕРЕМЕННЫЕ ОКРУЖЕНИЯ
Поведение
.B grep
зависит от следующих переменных окружения.
.PP
Локаль для категории
.BI LC_ foo
определяется проверкой трёх переменных окружения
.BR LC_ALL ,
.BR LC_\fIfoo\fP ,
.BR LANG ,
в указанном порядке.
Первая из установленных переменных задаёт локаль.
Например, если
.B LC_ALL
не задан, но
.B LC_MESSAGES
установлена в
.BR pt_BR ,
то используется бразильская португальская локаль для категории
.B LC_MESSAGES
.
Если ни одна из этих переменных не задана, если каталог локали не установлен, или если
.B grep
не был скомпилирован с поддержкой национальных языков (NLS), используется локаль C.
Команда оболочки
.B "locale \-a"
перечисляет доступные в данный момент локали.
.TP
.B GREP_COLOR
Эта переменная задаёт цвет, используемый для подсветки найденного (непустого) текста.
Она устарела в пользу
.BR GREP_COLORS ,
но всё ещё поддерживается.
Возможности
.BR mt ,
.BR ms ,
и
.B mc
из
.B GREP_COLORS
имеют приоритет над ней.
Эта переменная может задавать только цвет, используемый для подсветки найденного непустого текста в любой совпадающей строке (выбранной строке, если параметр
.B \-v
не указан, или строке контекста, если параметр
.B \-v
указан).
Значение по умолчанию —
.BR 01;31 ,
что означает жирный красный текст на фоне терминала по умолчанию.
.TP
.B GREP_COLORS
Задаёт цвета и другие атрибуты, используемые для подсветки различных частей вывода.
Её значение — список возможностей, разделённых двоеточиями, по умолчанию
.B ms=01;31:mc=01;31:sl=:cx=:fn=35:ln=32:bn=32:se=36
с отключёнными булевыми возможностями
.B rv
и
.B ne
(т.е. ложными).
Поддерживаемые возможности:
.RS
.TP
.B sl=
SGR‑подстрока для целых выбранных строк
(т.е. совпадающих строк, если параметр
.B \-v
не указан, или несовпадающих строк, если
.B \-v
указан).
Если же булевая возможность
.B rv
и параметр
.B \-v
указаны одновременно, применяется к строкам контекста.
По умолчанию пусто (т.е. используется цвет терминала по умолчанию).
.TP
.B cx=
SGR‑подстрока для целых строк контекста
(т.е. несовпадающих строк, если параметр
.B \-v
не указан, или совпадающих строк, если
.B \-v
указан).
Если же булевая возможность
.B rv
и параметр
.B \-v
указаны одновременно, применяется к выбранным несовпадающим строкам.
По умолчанию пусто.
.TP
.B rv
Булевое значение, меняющее (переключающее) смысл возможностей
.B sl=
и
.B cx=
при указании параметра
.B \-v
. По умолчанию false (отсутствует).
.TP
.B mt=01;31
SGR‑подстрока для подсветки найденного непустого текста в любой совпадающей строке (т.е. выбранной строке, если параметр
.B \-v
не указан, или строке контекста, если
.B \-v
указан).
Установка этого эквивалентна одновременному присвоению одинакового значения
.B ms=
и
.B mc= .
По умолчанию жирный красный текст на фоне текущей строки.
.TP
.B ms=01;31
SGR‑подстрока для подсветки найденного непустого текста в выбранной строке.
(Используется только когда параметр
.B \-v
не указан.)
Эффект возможностей
.B sl=
(или
.B cx=
при
.BR rv )
остается активным, когда это включается.
По умолчанию жирный красный текст на фоне текущей строки.
.TP
.B mc=01;31
SGR‑подстрока для подсветки найденного непустого текста в строке контекста.
(Используется только когда параметр
.B \-v
указан.)
Эффект возможностей
.B cx=
(или
.B sl=
при
.BR rv )
остается активным, когда это включается.
По умолчанию жирный красный текст на фоне текущей строки.
.TP
.B fn=35
SGR‑подстрока для имён файлов, предшествующих любой строке содержимого.
По умолчанию пурпурный текст на фоне терминала по умолчанию.
.TP
.B ln=32
SGR‑подстрока для номеров строк, предшествующих любой строке содержимого.
По умолчанию зелёный текст на фоне терминала по умолчанию.
.TP
.B bn=32
SGR‑подстрока для смещений в байтах, предшествующих любой строке содержимого.
По умолчанию зелёный текст на фоне терминала по умолчанию.
.TP
.B se=36
SGR‑подстрока для разделителей, вставляемых между полями выбранных строк
.RB ( : ),
между полями строк контекста
.RB ( \- ),
и между группами смежных строк при указании ненулевого контекста
.RB ( \-\^\- ).
По умолчанию циан‑текст на фоне терминала по умолчанию.
.TP
.B ne
Булевое значение, предотвращающее очистку до конца строки с помощью команды Erase in Line (EL) вправо
.RB ( \e33[K )
каждый раз, когда завершается цветной элемент.
Это необходимо в терминалах, где EL не поддерживается.
Также полезно в терминалах, где булевая возможность
.B back_color_erase
( bce )
терминфо не применяется, когда выбранные цвета подсветки не влияют на фон, либо когда EL слишком медленен или вызывает мерцание.
По умолчанию false (отсутствует).
.PP
Обратите внимание, что булевые возможности не имеют части
.BR = .\|.\|.\&
. Они опущены (т.е. false) по умолчанию и становятся true при указании.
.PP
См. раздел Select Graphic Rendition (SGR) в документации вашего текстового терминала для разрешённых значений и их смыслов как атрибутов символов.
Эти подстроки задаются целыми числами в десятичной системе и могут быть соединены точками с запятыми.
.B grep
сам собирает полную SGR‑последовательность
.RB ( \e33[ .\|.\|. m ).
Часто используемые значения: 1 — жирный, 4 — подчёркнутый, 5 — мигающий, 7 — инверсия, 39 — цвет переднего плана по умолчанию, 30‑37 — цвета переднего плана, 90‑97 — 16‑цветные режимы переднего плана, 38;5;0‑38;5;255 — 88‑ и 256‑цветные режимы переднего плана, 49 — цвет фона по умолчанию, 40‑47 — цвета фона, 100‑107 — 16‑цветные режимы фона, 48;5;0‑48;5;255 — 88‑ и 256‑цветные режимы фона.
.RE
.TP
\fBLC_ALL\fP, \fBLC_COLLATE\fP, \fBLANG\fP
Эти переменные задают локаль для категории
.B LC_COLLATE
, определяющей порядок сортировки, используемый при интерпретации диапазонных выражений, таких как
.BR [a\-z] .
.TP
\fBLC_ALL\fP, \fBLC_CTYPE\fP, \fBLANG\fP
Эти переменные задают локаль для категории
.B LC_CTYPE
, определяющей типы символов, например, какие символы являются пробельными.
Эта категория также определяет кодировку символов, то есть, в каком виде текст закодирован (UTF‑8, ASCII и т.п.). В локали C или POSIX все символы кодируются одним байтом, и каждый байт является допустимым символом.
.TP
\fBLC_ALL\fP, \fBLC_MESSAGES\fP, \fBLANG\fP
Эти переменные задают локаль для категории
.B LC_MESSAGES
, определяющей язык сообщений
.B grep
. По умолчанию локаль C использует американский английский.
.TP
.B POSIXLY_CORRECT
Если установлена, то
.B grep
поводит себя согласно POSIX; иначе поведение более типично для GNU.
POSIX требует, чтобы параметры, следующие за именами файлов, рассматривались как имена файлов; по умолчанию такие параметры перемещаются в начало списка операндов и рассматриваются как параметры.
Также POSIX требует, чтобы нераспознанные параметры диагностировались как «illegal», но поскольку они не противозаконны, по умолчанию они диагностируются как «invalid».
.B POSIXLY_CORRECT
также отключает
\fB_\fP\fIN\fP\fB_GNU_nonoption_argv_flags_\fP,
описанный ниже.
.TP
\fB_\fP\fIN\fP\fB_GNU_nonoption_argv_flags_\fP
(Здесь
.I N
— числовой идентификатор процесса
.B grep
.)  Если
.IR i th
символ этой переменной равен
.B 1 ,
не рассматривать
.IR i th
операнд
.B grep
как параметр, даже если он выглядит как параметр.
Оболочка может помещать эту переменную в окружение для каждой запускаемой команды, указывая, какие операнды являются результатом расширения шаблонов имён файлов и поэтому не должны рассматриваться как параметры.
Это поведение доступно только с GNU C library и только если
.B POSIXLY_CORRECT
не установлен.
.
.SH ПРИМЕЧАНИЯ
Эта страница руководства поддерживается лишь ненадёжно; полная документация часто более актуальна.
.
.SH АВТОРСКИЕ ПРАВА
Copyright 1998-2000, 2002, 2005-2021 Free Software Foundation, Inc.
.PP
Это свободное программное обеспечение; см. исходный код для условий копирования.
Гарантий НЕТ; даже гарантии ТОВАРНОЙ ПРИГОДНОСТИ или ПРИГОДНОСТИ ДЛЯ КОНКРЕТНОЙ ЦЕЛИ нет.
.
.SH ОШИБКИ
.SS "Сообщение об ошибках"
Отправляйте сообщения об ошибках по адресу
.MT bug-grep@gnu.org
bug-reporting address
.ME .
Архив
.UR https://lists.gnu.org/mailman/listinfo/bug-grep
почтовой рассылки
.UE
и трекер
.UR https://debbugs.gnu.org/cgi/pkgreport.cgi?package=grep
.UE
доступны.
.SS "Известные ошибки"
Большие количества повторений в конструкции
.BI { n , m }
могут заставить
.B grep
использовать много памяти.
Кроме того, некоторые другие редкие регулярные выражения требуют экспоненциального времени и пространства, и могут привести к исчерпанию памяти.
.PP
Обратные ссылки работают очень медленно и могут требовать экспоненциального времени.
.
.SH ПРИМЕР
Следующий пример выводит расположение и содержимое любой строки,
содержащей «f» и заканчивающейся на «.c»,
во всех файлах текущего каталога, имена которых содержат «g» и заканчиваются на «.h».
Параметр
.B \-n
выводит номера строк, аргумент
.B \-\-
обрабатывает расширения «*g*.h», начинающиеся с «‑», как имена файлов, а не как параметры,
а пустой файл /dev/null заставляет выводить имена файлов даже если только один файл попадает под шаблон «*g*.h».
.PP
.in +2n
.EX
$ \fBgrep\fP \-n \-\- 'f.*\e.c$' *g*.h /dev/null
argmatch.h:1:/* definitions and prototypes for argmatch.c
.EE
.in
.PP
Единственная строка, соответствующая шаблону, находится в строке 1 файла argmatch.h.
Обратите внимание, что синтаксис регулярных выражений, используемый в шаблоне, отличается от синтаксиса подстановки (globbing), который оболочка использует для сопоставления имён файлов.
.
.SH СМ. ТАКЖЕ
.SS "Страницы обычных руководств"
.BR awk (1),
.BR cmp (1),
.BR diff (1),
.BR find (1),
.BR perl (1),
.BR sed (1),
.BR sort (1),
.BR xargs (1),
.BR read (2),
.BR pcre (3),
.BR pcresyntax (3),
.BR pcrepattern (3),
.BR terminfo (5),
.BR glob (7),
.BR regex (7)
.SS "Полная документация"
Полное руководство доступно по адресу
.UR https://www.gnu.org/software/grep/manual/
.UE
Если программы
.B info
и
.B grep
установлены корректно, команда
.IP
.B info grep
.PP
должна предоставить доступ к полному руководству.
.
.\" Work around problems with some troff -man implementations.
.br
.
.\" Format for Emacs-maintained Dt string defined at this file's start.
.\" Local variables:
.\" time-stamp-format: "%:y-%02m-%02d"
.\" End:
