.\"
.\" scp.1
.\"
.\" Author: Tatu Ylonen <ylo@cs.hut.fi>
.\"
.\" Copyright (c) 1995 Tatu Ylonen <ylo@cs.hut.fi>, Espoo, Finland
.\"                    All rights reserved
.\"
.\" Created: Sun May  7 00:14:37 1995 ylo
.\"
.\" $OpenBSD: scp.1,v 1.112 2022/12/16 07:13:22 djm Exp $
.\"
.Dd $Mdocdate: December 16 2022 $
.Dt SCP 1
.Os
.Sh ИМЯ
.Nm scp
.Nd безопасное копирование файлов OpenSSH
.Sh СИНТАКСИС
.Nm scp
.Op Fl 346ABCOpqRrsTv
.Op Fl c Ar шифр
.Op Fl D Ar путь_к_sftp_серверу
.Op Fl F Ar ssh_config
.Op Fl i Ar файл_идентификации
.Op Fl J Ar место назначения
.Op Fl l Ar лимит
.Op Fl o Ar параметр_ssh
.Op Fl P Ar порт
.Op Fl S Ar программа
.Op Fl X Ar параметр_sftp
.Ar источник ... цель
.Sh ОПИСАНИЕ
.Nm
копирует файлы между хостами в сети.
.Pp
.Nm
использует протокол SFTP через соединение
.Xr ssh 1
для передачи данных и использует ту же аутентификацию и обеспечивает
ту же безопасность, что и сеанс входа в систему.
.Pp
.Nm
запросит пароли или парольные фразы, если они необходимы для
аутентификации.
.Pp
.Ar Источник
и
.Ar цель
могут быть указаны как локальный путь, удаленный хост с необязательным путем
в форме
.Sm off
.Oo пользователь @ Oc хост : Op путь ,
.Sm on
или как URI в форме
.Sm off
.No scp:// Oo пользователь @ Oc хост Oo : порт Oc Op / путь .
.Sm on
Локальные имена файлов можно сделать явными, используя абсолютные или относительные пути,
чтобы избежать
.Nm
обработки имен файлов, содержащих
.Sq :\&
как спецификаторы хоста.
.Pp
При копировании между двумя удаленными хостами, если используется формат URI,
.Ar порт
не может быть указан для
.Ar цели
если используется параметр
.Fl R .
.Pp
Доступны следующие параметры:
.Bl -tag -width Ds
.It Fl 3
Копирование между двумя удаленными хостами выполняется через локальный хост.
Без этого параметра данные копируются напрямую между двумя удаленными
хостами.
Обратите внимание, что при использовании устаревшего протокола SCP (через флаг
.Fl O )
этот параметр
выбирает пакетный режим для второго хоста, так как
.Nm
не может запрашивать пароли или парольные фразы для обоих хостов.
Этот режим используется по умолчанию.
.It Fl 4
Заставляет
.Nm
использовать только IPv4-адреса.
.It Fl 6
Заставляет
.Nm
использовать только IPv6-адреса.
.It Fl A
Разрешает перенаправление
.Xr ssh-agent 1
на удаленную систему.
По умолчанию перенаправление агента аутентификации не выполняется.
.It Fl B
Выбирает пакетный режим (запрещает запрос паролей или парольных фраз).
.It Fl C
Включение сжатия.
Передает флаг
.Fl C
в
.Xr ssh 1
для включения сжатия.
.It Fl c Ar шифр
Выбирает шифр для использования при шифровании передачи данных.
Этот параметр напрямую передается в
.Xr ssh 1 .
.It Fl D Ar путь_к_sftp_серверу
Подключается напрямую к локальной программе SFTP-сервера, а не к
удаленной через
.Xr ssh 1 .
Этот параметр может быть полезен при отладке клиента и сервера.
.It Fl F Ar ssh_config
Указывает альтернативный
файл конфигурации для пользователя для
.Nm ssh .
Этот параметр напрямую передается в
.Xr ssh 1 .
.It Fl i Ar файл_идентификации
Выбирает файл, из которого считывается идентификатор (закрытый ключ) для аутентификации
по открытому ключу.
Этот параметр напрямую передается в
.Xr ssh 1 .
.It Fl J Ar место назначения
Подключается к целевому хосту, сначала устанавливая
.Nm
соединение с промежуточным хостом, описанным
.Ar место назначения
и затем устанавливая TCP-перенаправление к конечному месту назначения
оттуда.
Может быть указано несколько промежуточных переходов, разделенных запятыми.
Это сокращение для указания директивы конфигурации
.Cm ProxyJump .
Этот параметр напрямую передается в
.Xr ssh 1 .
.It Fl l Ar лимит
Ограничивает используемую полосу пропускания, указанную в Кбит/с.
.It Fl O
Использует устаревший протокол SCP для передачи файлов вместо протокола SFTP.
Принудительное использование протокола SCP может потребоваться для серверов, которые
не реализуют SFTP, для обратной совместимости с определенными шаблонами
подстановки имен файлов и для раскрытия путей с префиксом
.Sq ~
для старых SFTP-серверов.
.It Fl o Ar параметр_ssh
Может использоваться для передачи параметров в
.Nm ssh
в формате, используемом в
.Xr ssh_config 5 .
Это полезно для указания параметров,
для которых нет отдельного флага командной строки
.Nm scp .
Полные сведения о параметрах, перечисленных ниже, и их возможных значениях см. в
.Xr ssh_config 5 .
.Pp
.Bl -tag -width Ds -offset indent -compact
.It AddressFamily
.It BatchMode
.It BindAddress
.It BindInterface
.It CanonicalDomains
.It CanonicalizeFallbackLocal
.It CanonicalizeHostname
.It CanonicalizeMaxDots
.It CanonicalizePermittedCNAMEs
.It CASignatureAlgorithms
.It CertificateFile
.It CheckHostIP
.It Ciphers
.It Compression
.It ConnectionAttempts
.It ConnectTimeout
.It ControlMaster
.It ControlPath
.It ControlPersist
.It GlobalKnownHostsFile
.It GSSAPIAuthentication
.It GSSAPIDelegateCredentials
.It HashKnownHosts
.It Host
.It HostbasedAcceptedAlgorithms
.It HostbasedAuthentication
.It HostKeyAlgorithms
.It HostKeyAlias
.It Hostname
.It IdentitiesOnly
.It IdentityAgent
.It IdentityFile
.It IPQoS
.It KbdInteractiveAuthentication
.It KbdInteractiveDevices
.It KexAlgorithms
.It KnownHostsCommand
.It LogLevel
.It MACs
.It NoHostAuthenticationForLocalhost
.It NumberOfPasswordPrompts
.It PasswordAuthentication
.It PKCS11Provider
.It Port
.It PreferredAuthentications
.It ProxyCommand
.It ProxyJump
.It PubkeyAcceptedAlgorithms
.It PubkeyAuthentication
.It RekeyLimit
.It RequiredRSASize
.It SendEnv
.It ServerAliveInterval
.It ServerAliveCountMax
.It SetEnv
.It StrictHostKeyChecking
.It TCPKeepAlive
.It UpdateHostKeys
.It User
.It UserKnownHostsFile
.It VerifyHostKeyDNS
.El
.It Fl P Ar порт
Указывает порт для подключения к удаленному хосту.
Обратите внимание, что этот параметр пишется с заглавной
.Sq P ,
потому что
.Fl p
уже зарезервирован для сохранения времени и битов режима файла.
.It Fl p
Сохраняет время изменения, время доступа и биты режима файла из
исходного файла.
.It Fl q
Тихий режим: отключает индикатор выполнения, а также предупреждения и диагностические
сообщения от
.Xr ssh 1 .
.It Fl R
Копирование между двумя удаленными хостами выполняется путем подключения к исходному
хосту и выполнения
.Nm
там.
Это требует, чтобы
.Nm
запущенный на исходном хосте, мог пройти аутентификацию на целевом хосте без
запроса пароля.
.It Fl r
Рекурсивное копирование целых каталогов.
Обратите внимание, что
.Nm
следует за символическими ссылками, встречающимися при обходе дерева.
.It Fl S Ar программа
Имя
.Ar программы
для использования для зашифрованного соединения.
Программа должна понимать параметры
.Xr ssh 1 .
.It Fl T
Отключает строгую проверку имен файлов.
По умолчанию при копировании файлов с удаленного хоста в локальный каталог
.Nm
проверяет, что полученные имена файлов соответствуют запрошенным в командной строке,
чтобы предотвратить отправку удаленной стороной неожиданных или нежелательных файлов.
Из-за различий в том, как различные операционные системы и оболочки интерпретируют
шаблоны имен файлов, эти проверки могут привести к отклонению нужных файлов.
Этот параметр отключает эти проверки ценой полного доверия тому,
что сервер не отправит неожиданные имена файлов.
.It Fl v
Подробный режим.
Заставляет
.Nm
и
.Xr ssh 1
выводить отладочные сообщения о своем прогрессе.
Это полезно при
отладке проблем с соединением, аутентификацией и конфигурацией.
.It Fl X Ar параметр_sftp
Указывает параметр, управляющий аспектами поведения протокола SFTP.
Допустимые параметры:
.Bl -tag -width Ds
.It Cm nrequests Ns = Ns Ar значение
Управляет тем, сколько одновременных запросов на чтение или запись SFTP может выполняться
в любой момент времени во время загрузки или выгрузки.
По умолчанию одновременно может быть активно 64 запроса.
.It Cm buffer Ns = Ns Ar значение
Управляет максимальным размером буфера для одной операции чтения/записи SFTP, используемой
во время загрузки или выгрузки.
По умолчанию используется буфер размером 32 КБ.
.El
.El
.Sh КОД ВЫХОДА
.Ex -std scp
.Sh СМ. ТАКЖЕ
.Xr sftp 1 ,
.Xr ssh 1 ,
.Xr ssh-add 1 ,
.Xr ssh-agent 1 ,
.Xr ssh-keygen 1 ,
.Xr ssh_config 5 ,
.Xr sftp-server 8 ,
.Xr sshd 8
.Sh ИСТОРИЯ
.Nm
основан на программе rcp из
.Bx
исходного кода от Regents of the University of California.
.Pp
Начиная с OpenSSH 9.0,
.Nm
по умолчанию использует протокол SFTP для передачи.
.Sh АВТОРЫ
.An Timo Rinne Aq Mt tri@iki.fi
.An Tatu Ylonen Aq Mt ylo@cs.hut.fi
.Sh ПРЕДОСТЕРЕЖЕНИЯ
Устаревший протокол SCP (выбираемый флагом
.Fl O )
требует выполнения оболочки удаленного пользователя для выполнения
сопоставления с шаблонами
.Xr glob 3 .
Это требует тщательного экранирования любых символов, которые имеют специальное значение для
удаленной оболочки, таких как кавычки.
