.\" Copyright (C) 2006 Michael Kerrisk <mtk.manpages@gmail.com>
.\" A few fragments remain from an earlier (1992) page by
.\" Drew Eckhardt (drew@cs.colorado.edu),
.\"
.\" %%%LICENSE_START(VERBATIM)
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one.
.\"
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\"
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\" %%%LICENSE_END
.\"
.\" Modified by Michael Haardt (michael@moria.de)
.\" Modified Sat Jul 24 13:22:07 1993 by Rik Faith (faith@cs.unc.edu)
.\" Modified 21 Aug 1994 by Michael Chastain (mec@shell.portal.com):
.\"   Referenced 'clone(2)'.
.\" Modified 1995-06-10, 1996-04-18, 1999-11-01, 2000-12-24
.\"   by Andries Brouwer (aeb@cwi.nl)
.\" Modified, 27 May 2004, Michael Kerrisk <mtk.manpages@gmail.com>
.\"     Added notes on capability requirements
.\" 2006-09-04, Michael Kerrisk
.\"     Greatly expanded, to describe all attributes that differ
.\"	parent and child.
.\"
.TH FORK 2 2020-06-09 "Linux" "Руководство программиста Linux"
.SH ИМЯ
fork \- создание дочернего процесса
.SH СИНТАКСИС
.B #include <sys/types.h>
.br
.B #include <unistd.h>
.PP
.B pid_t fork(void);
.SH ОПИСАНИЕ
.BR fork ()
создаёт новый процесс путём копирования вызывающего процесса.
Новый процесс называется
.I дочерним
процессом.
Вызывающий процесс называется
.I родительским
процессом.
.PP
Дочерний процесс и родительский процесс выполняются в отдельных адресных пространствах.
На момент вызова
.BR fork ()
оба адресных пространства имеют одинаковое содержимое.
Операции записи в память, отображения файлов
.RB ( mmap (2))
и удаления отображений
.RB ( munmap (2)),
выполненные одним из процессов, не влияют на другой.
.PP
Дочерний процесс является точной копией родительского,
за исключением следующих пунктов:
.IP * 3
Дочерний процесс имеет свой уникальный идентификатор процесса,
и этот PID не совпадает с идентификатором ни одной существующей группы процессов
.RB ( setpgid (2))
или сеанса.
.IP *
Идентификатор родительского процесса дочернего процесса совпадает с идентификатором родительского процесса.
.IP *
Дочерний процесс не наследует блокировки памяти родителя
.RB ( mlock (2),
.BR mlockall (2)).
.IP *
Показатели использования ресурсов процесса
.RB ( getrusage (2))
и счётчики процессорного времени
.RB ( times (2))
в дочернем процессе сбрасываются в ноль.
.IP *
Набор ожидающих сигналов дочернего процесса изначально пуст
.RB ( sigpending (2)).
.IP *
Дочерний процесс не наследует корректировки семафоров от родителя
.RB ( semop (2)).
.IP *
Дочерний процесс не наследует блокировки записей, связанные с процессом, от родителя
.RB ( fcntl (2)).
(С другой стороны, он наследует блокировки описаний открытых файлов
.BR fcntl (2)
и блокировки
.BR flock (2)
от родителя.)
.IP *
Дочерний процесс не наследует таймеры от родителя
.RB ( setitimer (2),
.BR alarm (2),
.BR timer_create (2)).
.IP *
Дочерний процесс не наследует незавершённые операции асинхронного ввода-вывода
от родителя
.RB ( aio_read (3),
.BR aio_write (3)),
а также не наследует контексты асинхронного ввода-вывода от родителя (см.
.BR io_setup (2)).
.PP
Атрибуты процесса в предыдущем списке все указаны в POSIX.1.
Родительский и дочерний процессы также различаются в отношении следующих
специфичных для Linux атрибутов процесса:
.IP * 3
Дочерний процесс не наследует уведомления об изменениях в каталогах (dnotify)
от родителя
(см. описание
.B F_NOTIFY
в
.BR fcntl (2)).
.IP *
Настройка
.BR prctl (2)
.B PR_SET_PDEATHSIG
сбрасывается, так что дочерний процесс не получает сигнал
при завершении родительского процесса.
.IP *
Значение слабого ограничения таймера по умолчанию устанавливается равным
текущему значению слабого ограничения таймера родителя.
См. описание
.BR PR_SET_TIMERSLACK
в
.BR prctl (2).
.IP *
Отображения памяти, помеченные флагом
.BR madvise (2)
.B MADV_DONTFORK,
не наследуются при
.BR fork ().
.IP *
Память в диапазонах адресов, помеченных флагом
.BR madvise (2)
.B MADV_WIPEONFORK,
обнуляется в дочернем процессе после
.BR fork ().
(Настройка
.B MADV_WIPEONFORK
сохраняется для этих диапазонов адресов в дочернем процессе.)
.IP *
Сигнал завершения дочернего процесса всегда
.B SIGCHLD
(см.
.BR clone (2)).
.IP *
Биты разрешений доступа к портам, установленные
.BR ioperm (2),
не наследуются дочерним процессом;
дочерний процесс должен включить все необходимые ему биты с помощью
.BR ioperm (2).
.PP
Обратите внимание на следующие дополнительные моменты:
.IP * 3
Дочерний процесс создаётся с одной нитью\(emтой,
которая вызвала
.BR fork ().
Всё виртуальное адресное пространство родителя реплицируется в дочернем процессе,
включая состояния мьютексов, условных переменных
и других объектов pthreads; использование
.BR pthread_atfork (3)
может помочь в решении проблем, которые это может вызвать.
.IP *
После
.BR fork ()
в многопоточной программе
дочерний процесс может безопасно вызывать только функции, безопасные для async-signal (см.
.BR signal\-safety (7)),
до тех пор, пока не будет вызван
.BR execve (2).
.IP *
Дочерний процесс наследует копии набора открытых файловых дескрипторов родителя.
Каждый файловый дескриптор в дочернем процессе ссылается на то же
открытое описание файла (см.
.BR open (2)),
что и соответствующий файловый дескриптор в родителе.
Это означает, что два файловых дескриптора разделяют флаги состояния открытого файла,
смещение в файле
и атрибуты ввода-вывода, управляемого сигналами (см. описание
.B F_SETOWN
и
.B F_SETSIG
в
.BR fcntl (2)).
.IP *
Дочерний процесс наследует копии набора открытых дескрипторов очередей сообщений
(см.
.BR mq_overview (7)).
Каждый дескриптор в дочернем процессе ссылается на то же
открытое описание очереди сообщений,
что и соответствующий дескриптор в родителе.
Это означает, что два дескриптора разделяют одни и те же флаги
.RI ( mq_flags ).
.IP *
Дочерний процесс наследует копии набора открытых потоков каталогов (см.
.BR opendir (3)).
В POSIX.1 сказано, что соответствующие потоки каталогов
в родительском и дочернем процессах
.I могут
разделять позиционирование в потоке каталога;
в Linux/glibc они этого не делают.
.SH ВОЗВРАЩАЕМОЕ ЗНАЧЕНИЕ
В случае успеха PID дочернего процесса возвращается в родительском процессе,
а 0 возвращается в дочернем процессе.
В случае ошибки в родительском процессе возвращается \-1,
дочерний процесс не создаётся, а
.I errno
устанавливается соответствующим образом.
.SH ОШИБКИ
.TP
.B EAGAIN
.\" NOTE! The following should match the description in pthread_create(3)
Достигнуто системное ограничение на количество нитей.
Существует ряд ограничений, которые могут вызвать эту ошибку:
.RS
.IP * 3
достигнуто мягкое ограничение ресурса
.BR RLIMIT_NPROC
(устанавливается через
.BR setrlimit (2)),
которое ограничивает количество процессов и нитей для реального идентификатора пользователя;
.IP *
достигнут общесистемный лимит ядра на количество процессов и нитей,
.IR /proc/sys/kernel/threads-max
(см.
.BR proc (5));
.IP *
достигнуто максимальное количество PID,
.IR /proc/sys/kernel/pid_max
(см.
.BR proc (5));
или
.IP *
достигнут лимит PID
.RI ( pids.max ),
налагаемый контроллером cgroup "количество процессов" (PIDs).
.RE
.TP
.B EAGAIN
Вызывающий процесс работает в рамках политики планирования
.BR SCHED_DEADLINE
и не имеет установленного флага сброса при fork.
См.
.BR sched (7).
.TP
.B ENOMEM
.BR fork ()
не удалось выделить необходимые структуры ядра из-за нехватки памяти.
.TP
.B ENOMEM
Была предпринята попытка создать дочерний процесс в пространстве имён PID,
"init" процесс которого завершился.
См.
.BR pid_namespaces (7).
.TP
.B ENOSYS
.BR fork ()
не поддерживается на этой платформе (например,
.\" e.g., arm (optionally), blackfin, c6x, frv, h8300, microblaze, xtensa
оборудование без блока управления памятью).
.TP
.BR ERESTARTNOINTR " (начиная с Linux 2.6.17)"
.\" commit 4a2c7a7837da1b91468e50426066d988050e4d56
Системный вызов был прерван сигналом и будет перезапущен.
(Это можно увидеть только при трассировке.)
.SH СООТВЕТСТВИЕ СТАНДАРТАМ
POSIX.1-2001, POSIX.1-2008, SVr4, 4.3BSD.
.SH ПРИМЕЧАНИЯ
В Linux
.BR fork ()
реализован с использованием страниц с копированием при записи, поэтому единственными затратами являются
время и память, необходимые для дублирования таблиц страниц родителя
и создания уникальной структуры задачи для дочернего процесса.
.SS Различия между библиотекой C и ядром
Начиная с версии 2.3.3,
.\" nptl/sysdeps/unix/sysv/linux/fork.c
вместо вызова системного вызова ядра
.BR fork ()
обёртка glibc
.BR fork (),
предоставляемая как часть реализации
NPTL threading, вызывает
.BR clone (2)
с флагами, которые дают тот же эффект, что и традиционный системный вызов.
(Вызов
.BR fork ()
эквивалентен вызову
.BR clone (2)
с указанием
.I flags
только как
.BR SIGCHLD .)
Обёртка glibc вызывает все обработчики fork, которые были установлены
с помощью
.BR pthread_atfork (3).
.\" and does some magic to ensure that getpid(2) returns the right value.
.SH ПРИМЕРЫ
См.
.BR pipe (2)
и
.BR wait (2).
.SH СМ. ТАКЖЕ
.BR clone (2),
.BR execve (2),
.BR exit (2),
.BR setrlimit (2),
.BR unshare (2),
.BR vfork (2),
.BR wait (2),
.BR daemon (3),
.BR pthread_atfork (3),
.BR capabilities (7),
.BR credentials (7)
.SH COLOPHON
Эта страница является частью проекта Linux
.I man-pages
версии 5.10.
Описание проекта,
информацию о сообщении об ошибках
и последнюю версию этой страницы
можно найти по адресу
\%https://www.kernel.org/doc/man\-pages/.
