.\" This manpage is Copyright (C) 1992 Drew Eckhardt;
.\" and Copyright (C) 1993 Michael Haardt, Ian Jackson.
.\" and Copyright (C) 2008 Greg Banks
.\" and Copyright (C) 2006, 2008, 2013, 2014 Michael Kerrisk <mtk.manpages@gmail.com>
.\"
.\" SPDX-License-Identifier: Linux-man-pages-copyleft
.\"
.\" Modified 1993-07-21 by Rik Faith <faith@cs.unc.edu>
.\" Modified 1994-08-21 by Michael Haardt
.\" Modified 1996-04-13 by Andries Brouwer <aeb@cwi.nl>
.\" Modified 1996-05-13 by Thomas Koenig
.\" Modified 1996-12-20 by Michael Haardt
.\" Modified 1999-02-19 by Andries Brouwer <aeb@cwi.nl>
.\" Modified 1998-11-28 by Joseph S. Myers <jsm28@hermes.cam.ac.uk>
.\" Modified 1999-06-03 by Michael Haardt
.\" Modified 2002-05-07 by Michael Kerrisk <mtk.manpages@gmail.com>
.\" Modified 2004-06-23 by Michael Kerrisk <mtk.manpages@gmail.com>
.\" 2004-12-08, mtk, reordered flags list alphabetically
.\" 2004-12-08, Martin Pool <mbp@sourcefrog.net> (& mtk), added O_NOATIME
.\" 2007-09-18, mtk, Added description of O_CLOEXEC + other minor edits
.\" 2008-01-03, mtk, with input from Trond Myklebust
.\"     <trond.myklebust@fys.uio.no> and Timo Sirainen <tss@iki.fi>
.\"     Rewrite description of O_EXCL.
.\" 2008-01-11, Greg Banks <gnb@melbourne.sgi.com>: add more detail
.\"     on O_DIRECT.
.\" 2008-02-26, Michael Haardt: Reorganized text for O_CREAT and mode
.\"
.\" FIXME . Apr 08: The next POSIX revision has O_EXEC, O_SEARCH, and
.\" O_TTYINIT.  Eventually these may need to be documented.  --mtk
.\"
.TH open 2 2024-01-16 "Linux man-pages 6.7"
.SH ИМЯ
open, openat, creat \- открыть и, возможно, создать файл
.SH БИБЛИОТЕКА
Стандартная библиотека C
.RI ( libc ", \-lc ")
.SH СИНТАКСИС
.nf
.B #include <fcntl.h>
.P
.BI "int open(const char *" pathname ", int " flags ", ..."
.BI "           \fR/*\fP mode_t " mode " \fR*/\fP );"
.P
.BI "int creat(const char *" pathname ", mode_t " mode );
.P
.BI "int openat(int " dirfd ", const char *" pathname ", int " flags ", ..."
.BI "           \fR/*\fP mode_t " mode " \fR*/\fP );"
.P
/* Описано отдельно, в \c
.BR openat2 (2):\c
\& */
.BI "int openat2(int " dirfd ", const char *" pathname ,
.BI "           const struct open_how *" how ", size_t " size );
.fi
.P
.RS -4
Требования макросов тестирования возможностей для glibc (см.
.BR feature_test_macros (7)):
.RE
.P
.BR openat ():
.nf
    Начиная с glibc 2.10:
        _POSIX_C_SOURCE >= 200809L
    До glibc 2.10:
        _ATFILE_SOURCE
.fi
.SH ОПИСАНИЕ
Системный вызов
.BR open ()
открывает файл, указанный в
.IR pathname .
Если указанный файл не существует,
он может быть (если
.B O_CREAT
указан в
.IR flags )
создан с помощью
.BR open ().
.P
Возвращаемое значение
.BR open ()
это файловый дескриптор, небольшое неотрицательное целое число, являющееся
индексом в таблице открытых файловых дескрипторов процесса.
Файловый дескриптор используется
в последующих системных вызовах
(\c
.BR read (2),
.BR write (2),
.BR lseek (2),
.BR fcntl (2),
и т.д.)
для ссылки на открытый файл.
Файловый дескриптор, возвращенный при успешном вызове, будет
наименьшим номером файлового дескриптора, который в данный момент не открыт для процесса.
.P
По умолчанию новый файловый дескриптор остается открытым при
.BR execve (2)
(т.е. флаг файлового дескриптора
.B FD_CLOEXEC
, описанный в
.BR fcntl (2),
изначально отключен); флаг
.B O_CLOEXEC
, описанный ниже, можно использовать для изменения этого поведения по умолчанию.
Смещение в файле устанавливается в начало файла (см.
.BR lseek (2)).
.P
Вызов
.BR open ()
создает новое
.IR "описание открытого файла" ,
запись в общесистемной таблице открытых файлов.
Описание открытого файла хранит смещение в файле и флаги состояния файла
(см. ниже).
Файловый дескриптор является ссылкой на описание открытого файла;
эта ссылка не изменяется, если
.I pathname
впоследствии удаляется или изменяется для ссылки на другой файл.
Дополнительные сведения об описаниях открытых файлов см. в ЗАМЕЧАНИЯХ.
.P
Аргумент
.I flags
должен включать один из следующих
.IR "режимов доступа" :
.BR O_RDONLY ", " O_WRONLY ", или " O_RDWR .
Они требуют открытия файла только для чтения, только для записи или для чтения/записи,
соответственно.
.P
Кроме того, ноль или более флагов создания файла и флагов состояния файла
могут быть
объединены побитовым ИЛИ
в
.IR flags .
.IR "Флагами создания файла"
являются
.BR O_CLOEXEC ,
.BR O_CREAT ,
.BR O_DIRECTORY ,
.BR O_EXCL ,
.BR O_NOCTTY ,
.BR O_NOFOLLOW ,
.BR O_TMPFILE ,
и
.BR O_TRUNC .
.IR "Флагами состояния файла"
являются все остальные флаги, перечисленные ниже.
.\" SUSv4 divides the flags into:
.\" * Access mode
.\" * File creation
.\" * File status
.\" * Other (O_CLOEXEC, O_DIRECTORY, O_NOFOLLOW)
.\" though it's not clear what the difference between "other" and
.\" "File creation" flags is.  I raised an Aardvark to see if this
.\" can be clarified in SUSv4; 10 Oct 2008.
.\" http://thread.gmane.org/gmane.comp.standards.posix.austin.general/64/focus=67
.\" TC1 (balloted in 2013), resolved this, so that those three constants
.\" are also categorized" as file status flags.
.\"
Различие между этими двумя группами флагов заключается в том,
что флаги создания файла влияют на семантику самой операции открытия,
в то время как флаги состояния файла влияют на семантику последующих операций ввода-вывода.
Флаги состояния файла можно получить и (в некоторых случаях)
изменить; подробности см. в
.BR fcntl (2).
.P
Полный список флагов создания файла и флагов состояния файла:
.TP
.B O_APPEND
Файл открывается в режиме добавления.
Перед каждым
.BR write (2)
смещение в файле устанавливается в конец файла,
как если бы с помощью
.BR lseek (2).
Изменение смещения в файле и операция записи
выполняются как одно атомарное действие.
.IP
.B O_APPEND
может привести к повреждению файлов в файловых системах NFS, если несколько процессов
одновременно добавляют данные в файл.
.\" For more background, see
.\" http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=453946
.\" http://nfs.sourceforge.net/
Это связано с тем, что NFS не поддерживает
добавление в файл, поэтому клиентскому ядру приходится эмулировать его, что
не может быть выполнено без состояния гонки.
.TP
.B O_ASYNC
Включить управляемый сигналами ввод-вывод:
генерировать сигнал
.RB ( SIGIO
по умолчанию, но это можно изменить с помощью
.BR fcntl (2))
когда ввод или вывод становится возможным для этого файлового дескриптора.
Эта возможность доступна только для терминалов, псевдотерминалов,
сокетов и (начиная с Linux 2.6) каналов и FIFO.
См.
.BR fcntl (2)
для получения дополнительной информации.
См. также ОШИБКИ, ниже.
.TP
.BR O_CLOEXEC " (начиная с Linux 2.6.23)"
.\" NOTE! several other man pages refer to this text
Включить флаг close-on-exec для нового файлового дескриптора.
.\" FIXME . for later review when Issue 8 is one day released...
.\" POSIX proposes to fix many APIs that provide hidden FDs
.\" http://austingroupbugs.net/tag_view_page.php?tag_id=8
.\" http://austingroupbugs.net/view.php?id=368
Указание этого флага позволяет программе избежать дополнительных
операций
.BR fcntl (2)
.B F_SETFD
для установки флага
.B FD_CLOEXEC .
.IP
Обратите внимание, что использование этого флага важно в некоторых многопоточных программах,
поскольку использование отдельной операции
.BR fcntl (2)
.B F_SETFD
для установки флага
.B FD_CLOEXEC
недостаточно для избежания состояний гонки,
когда один поток открывает файловый дескриптор и
пытается установить его флаг close-on-exec с помощью
.BR fcntl (2)
в то же время, когда другой поток выполняет
.BR fork (2)
и
.BR execve (2).
В зависимости от порядка выполнения,
гонка может привести к тому, что файловый дескриптор, возвращенный
.BR open ()
будет непреднамеренно передан программе, выполняемой дочерним процессом,
созданным
.BR fork (2).
(Такая гонка в принципе возможна для любого системного вызова,
который создает файловый дескриптор, для которого должен быть установлен флаг close-on-exec,
и различные другие системные вызовы Linux предоставляют эквивалент флага
.B O_CLOEXEC
для решения этой проблемы.)
.\" This flag fixes only one form of the race condition;
.\" The race can also occur with, for example, file descriptors
.\" returned by accept(), pipe(), etc.
.TP
.B O_CREAT
Если
.I pathname
не существует, создать его как обычный файл.
.IP
Владелец (идентификатор пользователя) нового файла устанавливается в эффективный идентификатор пользователя
процесса.
.IP
Владелец группы (идентификатор группы) нового файла устанавливается либо в
эффективный идентификатор группы процесса (семантика System V),
либо в идентификатор группы родительского каталога (семантика BSD).
В Linux поведение зависит от того, установлен ли
бит set-group-ID в родительском каталоге:
если этот бит установлен, то применяется семантика BSD;
в противном случае применяется семантика System V.
Для некоторых файловых систем поведение также зависит от параметров монтирования
.I bsdgroups
и
.I sysvgroups
, описанных в
.BR mount (8).
.\" As at Linux 2.6.25, bsdgroups is supported by ext2, ext3, ext4, and
.\" XFS (since Linux 2.6.14).
.IP
Аргумент
.I mode
задает биты режима файла, которые применяются при создании нового файла.
Если ни
.B O_CREAT
, ни
.B O_TMPFILE
не указаны в
.IR flags ,
то
.I mode
игнорируется (и может быть указан как 0 или просто опущен).
Аргумент
.I mode
.B должен
быть указан, если
.B O_CREAT
или
.B O_TMPFILE
указаны в
.IR flags ;
если он не указан,
к файлу будут применены произвольные байты из стека в качестве режима файла.
.IP
Эффективный режим изменяется с помощью
.I umask
процесса обычным способом: при отсутствии ACL по умолчанию режим
созданного файла равен
.IR "(mode\ &\ \[ti]umask)" .
.IP
Обратите внимание, что
.I mode
применяется только к будущим обращениям к
вновь созданному файлу; вызов
.BR open ()
, который создает файл только для чтения, может вполне вернуть файловый дескриптор
для чтения/записи.
.IP
Для
.I mode
предоставляются следующие символические константы:
.RS
.TP 9
.B S_IRWXU
00700 пользователь (владелец файла) имеет права на чтение, запись и выполнение
.TP
.B S_IRUSR
00400 пользователь имеет право на чтение
.TP
.B S_IWUSR
00200 пользователь имеет право на запись
.TP
.B S_IXUSR
00100 пользователь имеет право на выполнение
.TP
.B S_IRWXG
00070 группа имеет права на чтение, запись и выполнение
.TP
.B S_IRGRP
00040 группа имеет право на чтение
.TP
.B S_IWGRP
00020 группа имеет право на запись
.TP
.B S_IXGRP
00010 группа имеет право на выполнение
.TP
.B S_IRWXO
00007 остальные имеют права на чтение, запись и выполнение
.TP
.B S_IROTH
00004 остальные имеют право на чтение
.TP
.B S_IWOTH
00002 остальные имеют право на запись
.TP
.B S_IXOTH
00001 остальные имеют право на выполнение
.RE
.IP
Согласно POSIX, эффект при установке других битов в
.I mode
не определен.
В Linux следующие биты также учитываются в
.IR mode :
.RS
.TP 9
.B S_ISUID
0004000 бит set-user-ID
.TP
.B S_ISGID
0002000 бит set-group-ID (см.
.BR inode (7)).
.TP
.B S_ISVTX
0001000 липкий бит (см.
.BR inode (7)).
.RE
.TP
.BR O_DIRECT " (начиная с Linux 2.4.10)"
Пытаться минимизировать влияние кэширования на ввод-вывод для этого файла.
В целом это снизит производительность, но полезно в
особых ситуациях, например, когда приложения выполняют собственное кэширование.
Ввод-вывод файла выполняется непосредственно в/из буферов пользовательского пространства.
Флаг
.B O_DIRECT
сам по себе предпринимает попытку передать данные синхронно,
но не дает гарантий флага
.B O_SYNC
, что данные и необходимые метаданные переданы.
Для гарантии синхронного ввода-вывода
.B O_SYNC
должен использоваться вместе с
.BR O_DIRECT .
См. ЗАМЕЧАНИЯ ниже для дальнейшего обсуждения.
.IP
Семантически похожий (но устаревший) интерфейс для блочных устройств
описан в
.BR raw (8).
.TP
.B O_DIRECTORY
Если \fIpathname\fP не является каталогом, вызвать ошибку открытия.
.\" But see the following and its replies:
.\" http://marc.theaimsgroup.com/?t=112748702800001&r=1&w=2
.\" [PATCH] open: O_DIRECTORY and O_CREAT together should fail
.\" O_DIRECTORY | O_CREAT causes O_DIRECTORY to be ignored.
Этот флаг был добавлен в Linux 2.1.126 для
предотвращения проблем отказа в обслуживании, если
.BR opendir (3)
вызывается на
FIFO или ленточном устройстве.
.TP
.B O_DSYNC
Операции записи в файл будут завершены в соответствии с требованиями
синхронизированного завершения
.I данных
ввода-вывода.
.IP
К моменту возврата
.BR write (2)
(и аналогичных),
выходные данные
были переданы на базовое оборудование,
вместе с любыми метаданными файла, которые потребовались бы для извлечения этих данных
(т.е. как если бы каждый
.BR write (2)
за которым следовал вызов
.BR fdatasync (2)).
.IR "См. ЗАМЕЧАНИЯ ниже" .
.TP
.B O_EXCL
Гарантировать, что этот вызов создает файл:
если этот флаг указан вместе с
.BR O_CREAT ,
и
.I pathname
уже существует, то
.BR open ()
завершается с ошибкой
.BR EEXIST .
.IP
Когда указаны эти два флага, символические ссылки не раскрываются:
.\" POSIX.1-2001 explicitly requires this behavior.
если
.I pathname
является символической ссылкой, то
.BR open ()
завершается ошибкой независимо от того, куда указывает символическая ссылка.
.IP
В общем случае поведение
.B O_EXCL
не определено, если он используется без
.BR O_CREAT .
Есть одно исключение: в Linux 2.6 и новее,
.B O_EXCL
можно использовать без
.B O_CREAT
, если
.I pathname
ссылается на блочное устройство.
Если блочное устройство используется системой (например, смонтировано),
.BR open ()
завершается с ошибкой
.BR EBUSY .
.IP
В NFS
.B O_EXCL
поддерживается только при использовании NFSv3 или новее в ядре 2.6 или новее.
В средах NFS, где поддержка
.B O_EXCL
не предоставляется, программы, полагающиеся на него
для выполнения задач блокировки, будут содержать состояние гонки.
Портативные программы, которые хотят выполнять атомарную блокировку файлов с использованием файла блокировки
и должны избегать зависимости от поддержки NFS для
.BR O_EXCL ,
могут создать уникальный файл в
той же файловой системе (например, включая имя хоста и PID) и использовать
.BR link (2)
для создания ссылки на файл блокировки.
Если
.BR link (2)
возвращает 0, блокировка успешна.
В противном случае используйте
.BR stat (2)
для уникального файла, чтобы проверить, увеличилось ли количество его ссылок до 2,
в этом случае блокировка также успешна.
.TP
.B O_LARGEFILE
(LFS)
Разрешить открытие файлов, размеры которых не могут быть представлены в
.I off_t
(но могут быть представлены в
.IR off64_t ).
Макрос
.B _LARGEFILE64_SOURCE
должен быть определен (до включения
.I любых
заголовочных файлов),
чтобы получить это определение.
Установка макроса тестирования возможностей
.B _FILE_OFFSET_BITS
в 64 (вместо использования
.BR O_LARGEFILE )
является предпочтительным
способом доступа к большим файлам в 32-разрядных системах (см.
.BR feature_test_macros (7)).
.TP
.BR O_NOATIME " (начиная с Linux 2.6.8)"
Не обновлять время последнего доступа к файлу
.RI ( st_atime
в inode)
при
.BR read (2) файла.
.IP
Этот флаг можно использовать только при выполнении одного из следующих условий:
.RS
.IP \[bu] 3
Эффективный UID процесса
.\" Strictly speaking: the filesystem UID
совпадает с UID владельца файла.
.IP \[bu]
Вызывающий процесс имеет возможность
.B CAP_FOWNER
в своем пространстве имен пользователя и
UID владельца файла имеет отображение в этом пространстве имен.
.RE
.IP
Этот флаг предназначен для использования программами индексации или резервного копирования,
где его использование может значительно снизить объем дисковых операций.
Этот флаг может работать не во всех файловых системах.
Один из примеров \- NFS, где время доступа поддерживает сервер.
.\" The O_NOATIME flag also affects the treatment of st_atime
.\" by mmap() and readdir(2), MTK, Dec 04.
.TP
.B O_NOCTTY
Если
.I pathname
ссылается на терминальное устройство\[em]см.
.BR tty (4)\[em]оно
не станет управляющим терминалом процесса, даже если у
процесса его нет.
.TP
.B O_NOFOLLOW
Если последний компонент (т.е. базовое имя)
.I pathname
является символической ссылкой, то открытие завершается с ошибкой
.BR ELOOP .
Символические ссылки в предыдущих компонентах пути по-прежнему будут
раскрыты.
(Обратите внимание, что ошибка
.B ELOOP
, которая может возникнуть в этом случае, неотличима от случая, когда
открытие завершается ошибкой из-за того, что при раскрытии компонентов
в префиксной части пути найдено слишком много символических ссылок.)
.IP
Этот флаг является расширением FreeBSD, которое было добавлено в Linux 2.1.126
и впоследствии стандартизировано в POSIX.1-2008.
.IP
См. также
.B O_PATH
ниже.
.\" The headers from glibc 2.0.100 and later include a
.\" definition of this flag; \fIkernels before Linux 2.1.126 will ignore it if
.\" used\fP.
.TP
.BR O_NONBLOCK " или " O_NDELAY
По возможности файл открывается в неблокирующем режиме.
Ни
.BR open ()
ни какие-либо последующие операции ввода-вывода с возвращенным файловым дескриптором
не будут заставлять вызывающий процесс ждать.
.IP
Обратите внимание, что установка этого флага не влияет на работу
.BR poll (2),
.BR select (2),
.BR epoll (7),
и аналогичных,
поскольку эти интерфейсы лишь сообщают вызывающему о том,
готов ли файловый дескриптор,
что означает, что операция ввода-вывода, выполняемая с
файловым дескриптором с
.I сброшенным
флагом
.B O_NONBLOCK
, не будет блокироваться.
.IP
Обратите внимание, что этот флаг не влияет на обычные файлы и блочные устройства;
то есть операции ввода-вывода будут (кратковременно) блокироваться, когда требуется активность устройства,
независимо от того, установлен ли
.B O_NONBLOCK
.
Поскольку семантика
.B O_NONBLOCK
может быть реализована в будущем,
приложения не должны полагаться на блокирующее поведение
при указании этого флага для обычных файлов и блочных устройств.
.IP
Обработка FIFO (именованных каналов) также описана в
.BR fifo (7).
Обсуждение влияния
.B O_NONBLOCK
в сочетании с обязательными блокировками файлов и арендой файлов см. в
.BR fcntl (2).
.TP
.BR O_PATH " (начиная с Linux 2.6.39)"
.\" commit 1abf0c718f15a56a0a435588d1b104c7a37dc9bd
.\" commit 326be7b484843988afe57566b627fb7a70beac56
.\" commit 65cfc6722361570bfe255698d9cd4dccaf47570d
.\"
.\" http://thread.gmane.org/gmane.linux.man/2790/focus=3496
.\"     Subject: Re: [PATCH] open(2): document O_PATH
.\"     Newsgroups: gmane.linux.man, gmane.linux.kernel
.\"
Получить файловый дескриптор, который можно использовать для двух целей:
для указания местоположения в дереве файловой системы и
для выполнения операций, которые действуют исключительно на уровне файлового дескриптора.
Сам файл не открывается, и другие файловые операции (например,
.BR read (2),
.BR write (2),
.BR fchmod (2),
.BR fchown (2),
.BR fgetxattr (2),
.BR ioctl (2),
.BR mmap (2))
завершаются с ошибкой
.BR EBADF .
.IP
Следующие операции
.I можно
выполнять с полученным файловым дескриптором:
.RS
.IP \[bu] 3
.BR close (2).
.IP \[bu]
.BR fchdir (2),
если файловый дескриптор ссылается на каталог
(начиная с Linux 3.5).
.\" commit 332a2e1244bd08b9e3ecd378028513396a004a24
.IP \[bu]
.BR fstat (2)
(начиная с Linux 3.6).
.IP \[bu]
.\" fstat(): commit 55815f70147dcfa3ead5738fd56d3574e2e3c1c2
.BR fstatfs (2)
(начиная с Linux 3.12).
.\" fstatfs(): commit 9d05746e7b16d8565dddbe3200faa1e669d23bbf
.IP \[bu]
Дублирование файлового дескриптора
.RB ( dup (2),
.BR fcntl (2)
.BR F_DUPFD ,
и т.д.).
.IP \[bu]
Получение и установка флагов файлового дескриптора
.RB ( fcntl (2)
.B F_GETFD
и
.BR F_SETFD ).
.IP \[bu]
Получение флагов состояния открытого файла с помощью операции
.BR fcntl (2)
.B F_GETFL
: возвращаемые флаги будут включать бит
.BR O_PATH .
.IP \[bu]
Передача файлового дескриптора в качестве аргумента
.I dirfd
в
.BR openat ()
и другие системные вызовы "*at()".
Это включает
.BR linkat (2)
с
.B AT_EMPTY_PATH
(или через procfs с использованием
.BR AT_SYMLINK_FOLLOW )
даже если файл не является каталогом.
.IP \[bu]
Передача файлового дескриптора другому процессу через доменный сокет UNIX
(см.
.B SCM_RIGHTS
в
.BR unix (7)).
.RE
.IP
Когда
.B O_PATH
указан в
.IR flags ,
биты флагов, кроме
.BR O_CLOEXEC ,
.BR O_DIRECTORY ,
и
.B O_NOFOLLOW
игнорируются.
.IP
Открытие файла или каталога с флагом
.B O_PATH
не требует прав на сам объект
(но требует права на выполнение для каталогов в префиксе пути).
В зависимости от последующей операции
может выполняться проверка на наличие соответствующих прав доступа к файлу (например,
.BR fchdir (2)
требует права на выполнение для каталога, на который ссылается
его аргумент файлового дескриптора).
В отличие от этого,
получение ссылки на объект файловой системы путем его открытия с флагом
.B O_RDONLY
требует, чтобы вызывающий имел право на чтение объекта,
даже если последующая операция (например,
.BR fchdir (2),
.BR fstat (2))
не требует права на чтение объекта.
.IP
Если
.I pathname
является символической ссылкой и флаг
.B O_NOFOLLOW
также указан,
то вызов возвращает файловый дескриптор, ссылающийся на символическую ссылку.
Этот файловый дескриптор можно использовать в качестве аргумента
.I dirfd
в вызовах
.BR fchownat (2),
.BR fstatat (2),
.BR linkat (2),
и
.BR readlinkat (2)
с пустым путем, чтобы вызовы выполнялись над символической ссылкой.
.IP
Если
.I pathname
ссылается на точку автомонтирования, которая еще не была активирована, так что на ней
не смонтирована другая файловая система, то вызов возвращает файловый
дескриптор, ссылающийся на каталог автомонтирования без запуска монтирования.
.BR fstatfs (2)
затем можно использовать, чтобы определить, является ли это действительно неактивированной
точкой автомонтирования
.RB ( ".f_type == AUTOFS_SUPER_MAGIC" ).
.IP
Одно из применений
.B O_PATH
для обычных файлов \- предоставить эквивалент функциональности POSIX.1
.B O_EXEC
.
Это позволяет нам открыть файл, на выполнение которого у нас есть право,
но не на чтение, а затем выполнить этот файл
с шагами, примерно такими:
.IP
.in +4n
.EX
char buf[PATH_MAX];
fd = open("some_prog", O_PATH);
snprintf(buf, PATH_MAX, "/proc/self/fd/%d", fd);
execl(buf, "some_prog", (char *) NULL);
.EE
.in
.IP
Файловый дескриптор
.B O_PATH
также может быть передан в качестве аргумента
.BR fexecve (3).
.TP
.B O_SYNC
Операции записи в файл будут завершены в соответствии с требованиями
синхронизированного завершения
.I файла
ввода-вывода
(в отличие от синхронизированного завершения
.I данных
ввода-вывода,
предоставляемого
.BR O_DSYNC .)
.IP
К моменту возврата
.BR write (2)
(или аналогичного),
выходные данные и связанные метаданные файла
были переданы на базовое оборудование
(т.е. как если бы каждый
.BR write (2)
за которым следовал вызов
.BR fsync (2)).
.IR "См. ЗАМЕЧАНИЯ ниже" .
.TP
.BR O_TMPFILE " (начиная с Linux 3.11)"
.\" commit 60545d0d4610b02e55f65d141c95b18ccf855b6e
.\" commit f4e0c30c191f87851c4a53454abb55ee276f4a7e
.\" commit bb458c644a59dbba3a1fe59b27106c5e68e1c4bd
Создать безымянный временный обычный файл.
Аргумент
.I pathname
указывает каталог;
в файловой системе этого каталога будет создан безымянный inode.
Все, что записано в результирующий файл, будет потеряно, когда
последний файловый дескриптор будет закрыт, если только файлу не будет присвоено имя.
.IP
.B O_TMPFILE
должен быть указан с одним из
.B O_RDWR
или
.B O_WRONLY
и, опционально,
.BR O_EXCL .
Если
.B O_EXCL
не указан, то
.BR linkat (2)
можно использовать для связывания временного файла с файловой системой, делая его
постоянным, используя код, подобный следующему:
.IP
.in +4n
.EX
char path[PATH_MAX];
fd = open("/path/to/dir", O_TMPFILE | O_RDWR,
                        S_IRUSR | S_IWUSR);
\&
/* Ввод-вывод файла с помощью \[aq]fd\[aq]... */
\&
linkat(fd, "", AT_FDCWD, "/path/for/file", AT_EMPTY_PATH);
\&
/* Если у вызывающего нет возможности CAP_DAC_READ_SEARCH
   (необходимой для использования AT_EMPTY_PATH с linkat(2)),
   и смонтирована файловая система proc(5), то вызов
   linkat(2) выше можно заменить на:
\&
snprintf(path, PATH_MAX,  "/proc/self/fd/%d", fd);
linkat(AT_FDCWD, path, AT_FDCWD, "/path/for/file",
                        AT_SYMLINK_FOLLOW);
*/
.EE
.in
.IP
В этом случае
аргумент
.I mode
.BR open ()
определяет режим прав доступа к файлу, как и в случае с
.BR O_CREAT .
.IP
Указание
.B O_EXCL
вместе с
.B O_TMPFILE
предотвращает связывание временного файла с файловой системой
описанным выше способом.
(Обратите внимание, что значение
.B O_EXCL
в этом случае отличается от значения
.B O_EXCL
в других случаях.)
.IP
Есть два основных варианта использования
.\" Inspired by http://lwn.net/Articles/559147/
.BR O_TMPFILE :
.RS
.IP \[bu] 3
Улучшенная функциональность
.BR tmpfile (3):
создание временных файлов без состояния гонки, которые
(1) автоматически удаляются при закрытии;
(2) никогда не могут быть достигнуты через какое-либо имя пути;
(3) не подвержены атакам через символические ссылки; и
(4) не требуют от вызывающего придумывать уникальные имена.
.IP \[bu]
Создание файла, который изначально невидим, затем заполняется
данными и настраивается с соответствующими атрибутами файловой системы
.RB ( fchown (2),
.BR fchmod (2),
.BR fsetxattr (2),
и т.д.)
перед атомарным связыванием с файловой системой
в полностью сформированном состоянии (с использованием
.BR linkat (2)
как описано выше).
.RE
.IP
.B O_TMPFILE
требует поддержки со стороны базовой файловой системы;
только подмножество файловых систем Linux предоставляют такую поддержку.
В первоначальной реализации поддержка была предоставлена в
файловых системах ext2, ext3, ext4, UDF, Minix и tmpfs.
.\" To check for support, grep for "tmpfile" in kernel sources
Поддержка других файловых систем была добавлена впоследствии:
XFS (Linux 3.15);
.\" commit 99b6436bc29e4f10e4388c27a3e4810191cc4788
.\" commit ab29743117f9f4c22ac44c13c1647fb24fb2bafe
Btrfs (Linux 3.16);
.\" commit ef3b9af50bfa6a1f02cd7b3f5124b712b1ba3e3c
F2FS (Linux 3.16);
.\" commit 50732df02eefb39ab414ef655979c2c9b64ad21c
и ubifs (Linux 4.9)
.TP
.B O_TRUNC
Если файл уже существует и является обычным файлом, и режим доступа разрешает
запись (т.е. это
.B O_RDWR
или
.BR O_WRONLY )
он будет усечен до длины 0.
Если файл является FIFO или терминальным устройством, флаг
.B O_TRUNC
игнорируется.
В противном случае эффект
.B O_TRUNC
не определен.
.SS creat()
Вызов
.BR creat ()
эквивалентен вызову
.BR open ()
с
.I flags
равными
.BR O_CREAT|O_WRONLY|O_TRUNC .
.SS openat()
Системный вызов
.BR openat ()
работает точно так же, как
.BR open (),
за исключением различий, описанных здесь.
.P
Аргумент
.I dirfd
используется вместе с аргументом
.I pathname
следующим образом:
.IP \[bu] 3
Если имя пути, указанное в
.I pathname
, является абсолютным, то
.I dirfd
игнорируется.
.IP \[bu]
Если имя пути, указанное в
.I pathname
, является относительным и
.I dirfd
имеет специальное значение
.BR AT_FDCWD ,
то
.I pathname
интерпретируется относительно текущего рабочего
каталога вызывающего процесса (как
.BR open ()).
.IP \[bu]
Если имя пути, указанное в
.I pathname
, является относительным, то оно интерпретируется относительно каталога,
на который ссылается файловый дескриптор
.I dirfd
(а не относительно текущего рабочего каталога
вызывающего процесса, как это делается в
.BR open ()
для относительного имени пути).
В этом случае
.I dirfd
должен быть каталогом, открытым для чтения
.RB ( O_RDONLY )
или с использованием флага
.B O_PATH .
.P
Если имя пути, указанное в
.I pathname
, является относительным, а
.I dirfd
не является допустимым файловым дескриптором, возникает ошибка
.RB ( EBADF ).
(Указание недопустимого номера файлового дескриптора в
.I dirfd
можно использовать как средство для гарантии того, что
.I pathname
является абсолютным.)
.\"
.SS openat2(2)
Системный вызов
.BR openat2 (2)
является расширением
.BR openat ()
и предоставляет надмножество функций
.BR openat ().
Он описан отдельно в
.BR openat2 (2).
.SH ВОЗВРАЩАЕМОЕ ЗНАЧЕНИЕ
При успешном выполнении
.BR open (),
.BR openat (),
и
.BR creat ()
возвращают новый файловый дескриптор (неотрицательное целое число).
При ошибке возвращается \-1, и
.I errno
устанавливается для указания ошибки.
.SH ОШИБКИ
.BR open (),
.BR openat (),
и
.BR creat ()
могут завершиться со следующими ошибками:
.TP
.B EACCES
Запрошенный доступ к файлу не разрешен, или запрещено право поиска
для одного из каталогов в префиксе пути
.IR pathname ,
или файл еще не существовал, и запрещен доступ на запись к родительскому каталогу.
(См. также
.BR path_resolution (7).)
.TP
.B EACCES
.\" commit 30aba6656f61ed44cba445a3c0d38b296fa9e8f5
Когда указан
.B O_CREAT
, включен sysctl
.I protected_fifos
или
.I protected_regular
, файл уже существует и является FIFO или обычным файлом,
владелец файла не является ни текущим пользователем, ни владельцем
содержащего каталога, а содержащий каталог является общедоступным для записи
или групповым и имеет липкий бит.
Подробности см. в описаниях
.I /proc/sys/fs/protected_fifos
и
.I /proc/sys/fs/protected_regular
в
.BR proc (5).
.TP
.B EBADF
.RB ( openat ())
.I pathname
является относительным, но
.I dirfd
не является ни
.B AT_FDCWD
, ни допустимым файловым дескриптором.
.TP
.B EBUSY
.B O_EXCL
был указан в
.I flags
и
.I pathname
ссылается на блочное устройство, которое используется системой (например, оно смонтировано).
.TP
.B EDQUOT
Когда указан
.B O_CREAT
, файл не существует, и квота пользователя на дисковые
блоки или inodes в файловой системе исчерпана.
.TP
.B EEXIST
.I pathname
уже существует, и использовались
.BR O_CREAT " и " O_EXCL .
.TP
.B EFAULT
.I pathname
находится за пределами доступного адресного пространства.
.TP
.B EFBIG
См.
.BR EOVERFLOW .
.TP
.B EINTR
Во время ожидания завершения открытия медленного устройства
(например, FIFO; см.
.BR fifo (7))
вызов был прерван обработчиком сигнала; см.
.BR signal (7).
.TP
.B EINVAL
Файловая система не поддерживает флаг
.B O_DIRECT .
См.
.B ЗАМЕЧАНИЯ
для получения дополнительной информации.
.TP
.B EINVAL
Недопустимое значение в
.\" In particular, __O_TMPFILE instead of O_TMPFILE
.IR flags .
.TP
.B EINVAL
.B O_TMPFILE
был указан в
.IR flags ,
но не был указан ни
.B O_WRONLY
, ни
.B O_RDWR .
.TP
.B EINVAL
.B O_CREAT
был указан в
.I flags
, и последний компонент ("базовое имя") нового файла
.I pathname
недопустим
(например, содержит символы, не разрешенные базовой файловой системой).
.TP
.B EINVAL
Последний компонент ("базовое имя")
.I pathname
недопустим
(например, содержит символы, не разрешенные базовой файловой системой).
.TP
.B EISDIR
.I pathname
ссылается на каталог, и запрошенный доступ включает запись
(т.е. установлен
.B O_WRONLY
или
.B O_RDWR ).
.TP
.B EISDIR
.I pathname
ссылается на существующий каталог,
.B O_TMPFILE
и один из
.B O_WRONLY
или
.B O_RDWR
были указаны в
.IR flags ,
но эта версия ядра не предоставляет функциональность
.B O_TMPFILE .
.TP
.B ELOOP
При раскрытии
.I pathname
встречено слишком много символических ссылок.
.TP
.B ELOOP
.I pathname
была символической ссылкой, и
.I flags
указывали
.B O_NOFOLLOW
, но не
.BR O_PATH .
.TP
.B EMFILE
Достигнут лимит процесса на количество открытых файловых дескрипторов
(см. описание
.B RLIMIT_NOFILE
в
.BR getrlimit (2)).
.TP
.B ENAMETOOLONG
.I pathname
слишком длинное.
.TP
.B ENFILE
Достигнут общесистемный лимит на общее количество открытых файлов.
.TP
.B ENODEV
.I pathname
ссылается на специальный файл устройства, и соответствующее устройство не существует.
(Это ошибка ядра Linux; в этой ситуации
должен возвращаться
.B ENXIO .)
.TP
.B ENOENT
.B O_CREAT
не установлен, и указанный файл не существует.
.TP
.B ENOENT
Компонент каталога в
.I pathname
не существует или является висячей символической ссылкой.
.TP
.B ENOENT
.I pathname
ссылается на несуществующий каталог,
.B O_TMPFILE
и один из
.B O_WRONLY
или
.B O_RDWR
были указаны в
.IR flags ,
но эта версия ядра не предоставляет функциональность
.B O_TMPFILE .
.TP
.B ENOMEM
Указанный файл является FIFO,
но память для буфера FIFO не может быть выделена, поскольку
достигнут жесткий лимит пользователя на выделение памяти для каналов,
и вызывающий не имеет привилегий; см.
.BR pipe (7).
.TP
.B ENOMEM
Недостаточно памяти ядра.
.TP
.B ENOSPC
.I pathname
должен был быть создан, но на устройстве, содержащем
.I pathname
, нет места для нового файла.
.TP
.B ENOTDIR
Компонент, используемый как каталог в
.I pathname
, на самом деле не является каталогом, или указан \fBO_DIRECTORY\fP, а
.I pathname
не является каталогом.
.TP
.B ENOTDIR
.RB ( openat ())
.I pathname
является относительным именем пути, а
.I dirfd
является файловым дескриптором, ссылающимся на файл, не являющийся каталогом.
.TP
.B ENXIO
Установлены
.BR O_NONBLOCK " | " O_WRONLY
, указанный файл является FIFO, и
ни один процесс не открыл FIFO для чтения.
.TP
.B ENXIO
Файл является специальным файлом устройства, и соответствующее устройство не существует.
.TP
.B ENXIO
Файл является доменным сокетом UNIX.
.TP
.B EOPNOTSUPP
Файловая система, содержащая
.I pathname
, не поддерживает
.BR O_TMPFILE .
.TP
.B EOVERFLOW
.I pathname
ссылается на обычный файл, который слишком велик для открытия.
Обычный сценарий здесь заключается в том, что приложение, скомпилированное
на 32-битной платформе без
.I \-D_FILE_OFFSET_BITS=64
, попыталось открыть файл, размер которого превышает
.I (1<<31)\-1
байт;
см. также
.B O_LARGEFILE
выше.
Это ошибка, указанная POSIX.1;
до Linux 2.6.24 Linux возвращал ошибку
.B EFBIG
для этого случая.
.\" See http://bugzilla.kernel.org/show_bug.cgi?id=7253
.\" "Open of a large file on 32-bit fails with EFBIG, should be EOVERFLOW"
.\" Reported 2006-10-03
.TP
.B EPERM
Был указан флаг
.B O_NOATIME
, но эффективный идентификатор пользователя вызывающего
.\" Strictly speaking, it's the filesystem UID... (MTK)
не совпадал с владельцем файла, и вызывающий не имел привилегий.
.TP
.B EPERM
Операция была предотвращена печатью файла; см.
.BR fcntl (2).
.TP
.B EROFS
.I pathname
ссылается на файл в файловой системе только для чтения, и был запрошен
доступ на запись.
.TP
.B ETXTBSY
.I pathname
ссылается на исполняемый образ, который в данный момент выполняется, и
был запрошен доступ на запись.
.TP
.B ETXTBSY
.I pathname
ссылается на файл, который в данный момент используется как файл подкачки, и
был указан флаг
.B O_TRUNC .
.TP
.B ETXTBSY
.I pathname
ссылается на файл, который в данный момент читается ядром (например, для
загрузки модуля/прошивки), и был запрошен доступ на запись.
.TP
.B EWOULDBLOCK
Был указан флаг
.B O_NONBLOCK
, и на файле удерживалась несовместимая аренда
(см.
.BR fcntl (2)).
.SH ВЕРСИИ
Эффект (не определенный) от
.B O_RDONLY | O_TRUNC
различается в разных реализациях.
Во многих системах файл действительно усекается.
.\" Linux 2.0, 2.5: truncate
.\" Solaris 5.7, 5.8: truncate
.\" Irix 6.5: truncate
.\" Tru64 5.1B: truncate
.\" HP-UX 11.22: truncate
.\" FreeBSD 4.7: truncate
.SS Синхронизированный ввод-вывод
Опция "синхронизированный ввод-вывод" POSIX.1-2008
определяет различные варианты синхронизированного ввода-вывода
и определяет флаги
.BR open ()
.BR O_SYNC ,
.BR O_DSYNC ,
и
.B O_RSYNC
для управления поведением.
Независимо от того, поддерживает ли реализация эту опцию,
она должна по крайней мере поддерживать использование
.B O_SYNC
для обычных файлов.
.P
Linux реализует
.B O_SYNC
и
.BR O_DSYNC ,
но не
.BR O_RSYNC .
Некорректно glibc определяет
.B O_RSYNC
имеющим то же значение, что и
.BR O_SYNC .
.RB ( O_RSYNC
определен в заголовочном файле Linux
.I <asm/fcntl.h>
на HP PA-RISC, но не используется.)
.P
.B O_SYNC
обеспечивает синхронизированное завершение
.I файла
ввода-вывода,
что означает, что операции записи будут сбрасывать данные и все связанные метаданные
на базовое оборудование.
.B O_DSYNC
обеспечивает синхронизированное завершение
.I данных
ввода-вывода,
что означает, что операции записи будут сбрасывать данные
на базовое оборудование,
но будут сбрасывать только обновления метаданных, которые необходимы
для успешного завершения последующей операции чтения.
Завершение по данным может уменьшить количество дисковых операций,
необходимых для приложений, которым не нужны гарантии
завершения файла.
.P
Чтобы понять разницу между двумя типами завершения,
рассмотрим две части метаданных файла:
время последней модификации файла
.RI ( st_mtime )
и длину файла.
Все операции записи обновляют время последней модификации файла,
но только записи, которые добавляют данные в конец
файла, изменяют длину файла.
Время последней модификации не требуется для того, чтобы
чтение завершилось успешно, но длина файла нужна.
Таким образом,
.B O_DSYNC
гарантирует только сброс обновлений метаданных длины файла
(тогда как
.B O_SYNC
всегда сбрасывает также метаданные времени последней модификации).
.P
До Linux 2.6.33 Linux реализовывал только флаг
.B O_SYNC
для
.BR open ().
Однако, когда этот флаг был указан,
большинство файловых систем фактически предоставляли эквивалент синхронизированного завершения
.I данных
ввода-вывода (т.е.
.B O_SYNC
фактически был реализован как эквивалент
.BR O_DSYNC ).
.P
Начиная с Linux 2.6.33, предоставляется надлежащая поддержка
.B O_SYNC .
Однако для обеспечения обратной двоичной совместимости
.B O_DSYNC
был определен с тем же значением, что и исторический
.BR O_SYNC ,
а
.B O_SYNC
был определен как новое (двухбитовое) значение флага, которое включает
значение флага
.B O_DSYNC .
Это гарантирует, что приложения, скомпилированные с использованием
новых заголовков, получают по крайней мере семантику
.B O_DSYNC
до Linux 2.6.33.
.\"
.SS Различия между библиотекой C и ядром
Начиная с glibc 2.26,
функция-обертка glibc для
.BR open ()
использует системный вызов
.BR openat ()
вместо системного вызова ядра
.BR open ().
Для некоторых архитектур это также верно и до glibc 2.26.
.\"
.SH СТАНДАРТЫ
.TP
.BR open ()
.TQ
.BR creat ()
.TQ
.BR openat ()
POSIX.1-2008.
.P
.BR openat2 (2)
Linux.
.P
Флаги
.BR O_DIRECT ,
.BR O_NOATIME ,
.BR O_PATH ,
и
.B O_TMPFILE
являются специфичными для Linux.
Для получения их определений необходимо определить
.B _GNU_SOURCE .
.P
Флаги
.BR O_CLOEXEC ,
.BR O_DIRECTORY ,
и
.B O_NOFOLLOW
не указаны в POSIX.1-2001,
но указаны в POSIX.1-2008.
Начиная с glibc 2.12, их определения можно получить, определив либо
.B _POSIX_C_SOURCE
со значением больше или равным 200809L, либо
.B _XOPEN_SOURCE
со значением больше или равным 700.
В glibc 2.11 и более ранних версиях определения получаются путем определения
.BR _GNU_SOURCE .
.SH ИСТОРИЯ
.TP
.BR open ()
.TQ
.BR creat ()
SVr4, 4.3BSD, POSIX.1-2001.
.TP
.BR openat ()
POSIX.1-2008.
Linux 2.6.16,
glibc 2.4.
.SH ЗАМЕЧАНИЯ
В Linux флаг
.B O_NONBLOCK
иногда используется в случаях, когда нужно открыть,
но нет необходимости читать или писать.
Например,
это может использоваться для открытия устройства, чтобы получить файловый дескриптор
для использования с
.BR ioctl (2).
.P
Обратите внимание, что
.BR open ()
может открывать специальные файлы устройств, но
.BR creat ()
не может их создавать; используйте
.BR mknod (2)
вместо этого.
.P
Если файл создан заново, его поля
.IR st_atime ,
.IR st_ctime ,
.I st_mtime
(соответственно, время последнего доступа, время последнего изменения состояния и
время последней модификации; см.
.BR stat (2))
устанавливаются
в текущее время, а также поля
.I st_ctime
и
.I st_mtime
родительского каталога.
В противном случае, если файл изменен из-за флага
.B O_TRUNC
, его поля
.I st_ctime
и
.I st_mtime
устанавливаются в текущее время.
.P
Файлы в каталоге
.IR /proc/ pid /fd
показывают открытые файловые дескрипторы процесса с PID
.IR pid .
Файлы в каталоге
.IR /proc/ pid /fdinfo
показывают еще больше информации об этих файловых дескрипторах.
См.
.BR proc (5)
для получения дополнительной информации об обоих этих каталогах.
.P
Заголовочный файл Linux
.B <asm/fcntl.h>
не определяет
.BR O_ASYNC ;
вместо него определен синоним (из BSD)
.BR FASYNC .
.\"
.\"
.SS Описания открытых файлов
Термин "описание открытого файла" используется POSIX для обозначения
записей в общесистемной таблице открытых файлов.
В других контекстах этот объект
также называют "объектом открытого файла",
"дескриптором файла", "записью таблицы открытых файлов"
или\[em]на жаргоне разработчиков ядра\[em]
.IR "struct file" .
.P
Когда файловый дескриптор дублируется (с помощью
.BR dup (2)
или аналогичных),
дубликат ссылается на то же описание открытого файла,
что и исходный файловый дескриптор, и, следовательно, два файловых дескриптора
совместно используют смещение в файле и флаги состояния файла.
Такое совместное использование также может происходить между процессами:
дочерний процесс, созданный с помощью
.BR fork (2)
, наследует дубликаты файловых дескрипторов своего родителя,
и эти дубликаты ссылаются на те же описания открытых файлов.
.P
Каждый
.BR open ()
файла создает новое описание открытого файла;
таким образом, может быть несколько описаний открытых файлов,
соответствующих одному inode файла.
.P
В Linux можно использовать операцию
.BR kcmp (2)
.B KCMP_FILE
для проверки того, ссылаются ли два файловых дескриптора
(в одном процессе или в двух разных процессах)
на одно и то же описание открытого файла.
.\"
.SS NFS
В протоколе, лежащем в основе NFS, есть много недостатков, влияющих
среди прочего на
.BR O_SYNC " и " O_NDELAY .
.P
В файловых системах NFS с включенным отображением UID
.BR open ()
может
возвращать файловый дескриптор, но, например,
запросы
.BR read (2)
отклоняются
с
.BR EACCES .
Это связано с тем, что клиент выполняет
.BR open ()
проверяя
разрешения, но отображение UID выполняется сервером при
запросах чтения и записи.
.\"
.\"
.SS FIFO
Открытие конца чтения или записи FIFO блокируется до тех пор, пока другой
конец также не будет открыт (другим процессом или потоком).
См.
.BR fifo (7)
для получения дополнительной информации.
.\"
.\"
.SS Режим доступа к файлу
В отличие от других значений, которые могут быть указаны в
.IR flags ,
значения
.I "режима доступа"
.BR O_RDONLY ", " O_WRONLY ", и " O_RDWR
не определяют отдельные биты.
Вместо этого они определяют два младших бита
.IR flags ,
и определены соответственно как 0, 1 и 2.
Другими словами, комбинация
.B "O_RDONLY | O_WRONLY"
является логической ошибкой и, безусловно, не имеет того же значения, что и
.BR O_RDWR .
.P
Linux резервирует специальный нестандартный режим доступа 3 (двоичное 11) в
.I flags
для обозначения:
проверить права на чтение и запись для файла и вернуть файловый дескриптор,
который нельзя использовать для чтения или записи.
Этот нестандартный режим доступа используется некоторыми драйверами Linux для возврата
файлового дескриптора, который предназначен только для операций
.BR ioctl (2)
, специфичных для устройства.
.\" See for example util-linux's disk-utils/setfdprm.c
.\" For some background on access mode 3, see
.\" http://thread.gmane.org/gmane.linux.kernel/653123
.\" "[RFC] correct flags to f_mode conversion in __dentry_open"
.\" LKML, 12 Mar 2008
.\"
.\"
.SS Обоснование openat() и других API с "файловым дескриптором каталога"
.BR openat ()
и другие системные вызовы и функции библиотеки, которые принимают
аргумент файлового дескриптора каталога
(т.е.
.BR execveat (2),
.BR faccessat (2),
.BR fanotify_mark (2),
.BR fchmodat (2),
.BR fchownat (2),
.BR fspick (2),
.BR fstatat (2),
.BR futimesat (2),
.BR linkat (2),
.BR mkdirat (2),
.BR mknodat (2),
.BR mount_setattr (2),
.BR move_mount (2),
.BR name_to_handle_at (2),
.BR open_tree (2),
.BR openat2 (2),
.BR readlinkat (2),
.BR renameat (2),
.BR renameat2 (2),
.BR statx (2),
.BR symlinkat (2),
.BR unlinkat (2),
.BR utimensat (2),
.BR mkfifoat (3),
и
.BR scandirat (3))
решают две проблемы старых интерфейсов, которые им предшествовали.
Здесь объяснение дается в терминах вызова
.BR openat (),
но обоснование аналогично для других интерфейсов.
.P
Во-первых,
.BR openat ()
позволяет приложению избегать состояний гонки, которые могут
возникнуть при использовании
.BR open ()
для открытия файлов в каталогах, отличных от текущего рабочего каталога.
Эти состояния гонки возникают из-за того, что некоторый компонент
префикса каталога, переданного в
.BR open (),
может быть изменен параллельно с вызовом
.BR open ().
Предположим, например, что мы хотим создать файл
.I dir1/dir2/xxx.dep
, если файл
.I dir1/dir2/xxx
существует.
Проблема в том, что между проверкой существования и шагом создания файла
.I dir1
или
.I dir2
(которые могут быть символическими ссылками)
могут быть изменены так, чтобы указывать на другое место.
Таких гонок можно избежать,
открыв файловый дескриптор для целевого каталога,
а затем указав этот файловый дескриптор в качестве аргумента
.I dirfd
(например)
.BR fstatat (2)
и
.BR openat ().
Использование файлового дескриптора
.I dirfd
также имеет другие преимущества:
.IP \[bu] 3
файловый дескриптор является стабильной ссылкой на каталог,
даже если каталог переименован; и
.IP \[bu]
открытый файловый дескриптор предотвращает размонтирование базовой файловой системы,
так же как когда процесс имеет текущий рабочий каталог в файловой системе.
.P
Во-вторых,
.BR openat ()
позволяет реализовать "текущий рабочий каталог" для каждого потока
с помощью файловых дескрипторов, поддерживаемых приложением.
(Эта функциональность также может быть получена с помощью трюков, основанных
на использовании
.IR /proc/self/fd/ dirfd,
но менее эффективно.)
.P
Аргумент
.I dirfd
для этих API может быть получен с помощью
.BR open ()
или
.BR openat ()
для открытия каталога (с флагом
.B O_RDONLY
или
.B O_PATH
).
В качестве альтернативы такой файловый дескриптор можно получить, применив
.BR dirfd (3)
к потоку каталога, созданному с помощью
.BR opendir (3).
.P
Когда этим API передается аргумент
.I dirfd
со значением
.B AT_FDCWD
или указанный путь является абсолютным,
они обрабатывают свой аргумент пути так же, как
соответствующие обычные API.
Однако в этом случае некоторые из этих API имеют аргумент
.I flags
, который обеспечивает доступ к функциональности, недоступной в
соответствующих обычных API.
.\"
.\"
.SS O_DIRECT
Флаг
.B O_DIRECT
может накладывать ограничения на выравнивание длины и адреса
буферов пользовательского пространства и смещения в файле для операций ввода-вывода.
В Linux ограничения на выравнивание
различаются в зависимости от файловой системы и версии ядра и могут вообще
отсутствовать.
Обработка невыровненных
.B O_DIRECT
операций ввода-вывода также различается;
они могут либо завершаться с ошибкой
.B EINVAL
, либо переключаться на буферизованный ввод-вывод.
.P
Начиная с Linux 6.1,
поддержку
.B O_DIRECT
и ограничения на выравнивание для файла можно запросить с помощью
.BR statx (2),
используя флаг
.B STATX_DIOALIGN .
Поддержка
.B STATX_DIOALIGN
различается в зависимости от файловой системы;
см.
.BR statx (2).
.P
Некоторые файловые системы предоставляют свои собственные интерфейсы для запроса
ограничений на выравнивание
.B O_DIRECT ,
например, операция
.B XFS_IOC_DIOINFO
в
.BR xfsctl (3).
.B STATX_DIOALIGN
следует использовать вместо него, когда он доступен.
.P
Если ни одно из вышеперечисленных средств недоступно,
то поддержка прямого ввода-вывода и ограничения на выравнивание
могут быть определены только на основе известных характеристик файловой системы,
отдельного файла,
базовых устройств хранения
и версии ядра.
В Linux 2.4
большинство файловых систем, основанных на блочных устройствах, требуют, чтобы
смещение в файле, длина и адрес памяти всех сегментов ввода-вывода
были кратны размеру блока файловой системы
(обычно 4096 байт).
В Linux 2.6.0
это было смягчено до логического размера блока блочного устройства
(обычно 512 байт).
Логический размер блока блочного устройства можно определить с помощью операции
.BR ioctl (2)
.B BLKSSZGET
или из командной оболочки с помощью команды:
.P
.in +4n
.EX
blockdev \-\-getss
.EE
.in
.P
Операции ввода-вывода
.B O_DIRECT
никогда не должны выполняться одновременно с системным вызовом
.BR fork (2),
если буфер памяти является частным отображением
(т.е. любое отображение, созданное с помощью флага
.BR mmap (2)
.B MAP_PRIVATE
; это включает память, выделенную в куче, и статически выделенные буферы).
Любые такие операции ввода-вывода, независимо от того, отправлены ли они через интерфейс асинхронного ввода-вывода или из
другого потока в процессе,
должны быть завершены до вызова
.BR fork (2).
Несоблюдение этого требования может привести к повреждению данных и неопределенному поведению в
родительском и дочернем процессах.
Это ограничение не применяется, когда буфер памяти для
операций ввода-вывода
.B O_DIRECT
был создан с помощью
.BR shmat (2)
или
.BR mmap (2)
с флагом
.B MAP_SHARED .
Это ограничение также не применяется, когда буфер памяти был помечен как
.B MADV_DONTFORK
с помощью
.BR madvise (2),
гарантируя, что он не будет доступен
дочернему процессу после
.BR fork (2).
.P
Флаг
.B O_DIRECT
был представлен в SGI IRIX, где он имеет ограничения на выравнивание,
аналогичные ограничениям Linux 2.4.
IRIX также имеет вызов
.BR fcntl (2)
для запроса соответствующих выравниваний и размеров.
FreeBSD 4.x представила
флаг с тем же именем, но без ограничений на выравнивание.
.P
Поддержка
.B O_DIRECT
была добавлена в Linux 2.4.10.
Старые ядра Linux просто игнорируют этот флаг.
Некоторые файловые системы могут не реализовывать этот флаг, и в этом случае
.BR open ()
завершается с ошибкой
.B EINVAL
при его использовании.
.P
Приложения должны избегать смешивания
.B O_DIRECT
и обычного ввода-вывода для одного и того же файла,
и особенно для перекрывающихся областей байтов в одном файле.
Даже если файловая система правильно обрабатывает проблемы согласованности в
этой ситуации, общая пропускная способность ввода-вывода, скорее всего, будет ниже, чем
при использовании любого из режимов по отдельности.
Аналогично, приложения должны избегать смешивания
.BR mmap (2)
файлов с прямым вводом-выводом для тех же файлов.
.P
Поведение
.B O_DIRECT
в NFS будет отличаться от локальных файловых систем.
Старые ядра или
ядра, настроенные определенным образом, могут не поддерживать эту комбинацию.
Протокол NFS не поддерживает передачу флага на сервер, поэтому
ввод-вывод
.B O_DIRECT
будет обходить страничный кэш только на клиенте; сервер может
по-прежнему кэшировать ввод-вывод.
Клиент просит сервер сделать ввод-вывод
синхронным, чтобы сохранить синхронную семантику
.BR O_DIRECT .
Некоторые серверы будут работать плохо в таких обстоятельствах, особенно
если размер ввода-вывода мал.
Некоторые серверы также могут быть настроены на
ложное сообщение клиенту о том, что ввод-вывод достиг стабильного хранилища; это
позволит избежать снижения производительности, но с некоторым риском для целостности данных
в случае сбоя питания сервера.
Клиент NFS Linux не накладывает ограничений на выравнивание для
ввода-вывода
.B O_DIRECT.
.P
Резюмируя,
.B O_DIRECT
является потенциально мощным инструментом, который следует использовать с осторожностью.
Рекомендуется, чтобы приложения рассматривали использование
.B O_DIRECT
как параметр производительности, который по умолчанию отключен.
.SH ОШИБКИ
В настоящее время невозможно включить управляемый сигналами
ввод-вывод, указав
.B O_ASYNC
при вызове
.BR open ();
используйте
.BR fcntl (2)
для включения этого флага.
.\" FIXME . Check bugzilla report on open(O_ASYNC)
.\" See http://bugzilla.kernel.org/show_bug.cgi?id=5993
.P
При попытке определить, поддерживает ли ядро функциональность
.B O_TMPFILE
, необходимо проверять два разных кода ошибки,
.B EISDIR
и
.BR ENOENT .
.P
Когда в
.I flags
указаны как
.B O_CREAT
, так и
.B O_DIRECTORY
, и файл, указанный
.I pathname
, не существует,
.BR open ()
создаст обычный файл (т.е.
.B O_DIRECTORY
игнорируется).
.SH СМ. ТАКЖЕ
.BR chmod (2),
.BR chown (2),
.BR close (2),
.BR dup (2),
.BR fcntl (2),
.BR link (2),
.BR lseek (2),
.BR mknod (2),
.BR mmap (2),
.BR mount (2),
.BR open_by_handle_at (2),
.BR openat2 (2),
.BR read (2),
.BR socket (2),
.BR stat (2),
.BR umask (2),
.BR unlink (2),
.BR write (2),
.BR fopen (3),
.BR acl (5),
.BR fifo (7),
.BR inode (7),
.BR path_resolution (7),
.BR symlink (7)
