.\" This manpage is Copyright (C) 1992 Drew Eckhardt;
.\"             and Copyright (C) 1993 Michael Haardt, Ian Jackson.
.\" and Copyright (C) 2007 Michael Kerrisk <mtk.manpages@gmail.com>
.\"
.\" %%%LICENSE_START(VERBATIM)
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one.
.\"
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\"
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\" %%%LICENSE_END
.\"
.\" Modified Sat Jul 24 13:35:59 1993 by Rik Faith <faith@cs.unc.edu>
.\" Modified Sun Nov 28 17:19:01 1993 by Rik Faith <faith@cs.unc.edu>
.\" Modified Sat Jan 13 12:58:08 1996 by Michael Haardt
.\"   <michael@cantor.informatik.rwth-aachen.de>
.\" Modified Sun Jul 21 18:59:33 1996 by Andries Brouwer <aeb@cwi.nl>
.\" 2001-12-13 added remark by Zack Weinberg
.\" 2007-06-18 mtk:
.\"    	Added details about seekable files and file offset.
.\"	Noted that write() may write less than 'count' bytes, and
.\"	gave some examples of why this might occur.
.\"	Noted what happens if write() is interrupted by a signal.
.\"
.TH WRITE 2 2019-10-10 "Linux" "Руководство программиста Linux"
.SH ИМЯ
write \- запись в файловый дескриптор
.SH СИНТАКСИС
.B #include <unistd.h>
.PP
.BI "ssize_t write(int " fd ", const void *" buf ", size_t " count );
.SH ОПИСАНИЕ
.BR write ()
записывает до
.I count
байт из буфера, начиная с
.I buf
в файл, на который ссылается файловый дескриптор
.IR fd .
.PP
Количество записанных байт может быть меньше
.I count
если, например,
недостаточно места на физическом носителе, или достигнут
ресурсный лимит
.B RLIMIT_FSIZE
(см.
.BR setrlimit (2)),
или вызов был прерван обработчиком сигнала
после записи менее
.I count
байт.
(См. также
.BR pipe (7).)
.PP
Для файла с возможностью позиционирования (т.е. такого, к которому
может быть применён
.BR lseek (2),
например, обычный файл)
запись выполняется по смещению файла,
и смещение файла увеличивается на
количество байт, фактически записанных.
Если файл был
.BR open (2)открыт
с флагом
.BR O_APPEND ,
то перед записью смещение файла сначала устанавливается в конец файла.
Корректировка смещения файла и операция записи
выполняются как атомарный шаг.
.PP
POSIX требует, чтобы
.BR read (2),
которое может быть доказано как происходящее после возврата из
.BR write (),
возвращало новые данные.
Заметьте, что не все файловые системы соответствуют POSIX.
.PP
В соответствии с POSIX.1, если
.I count
больше
.BR SSIZE_MAX ,
результат зависит от реализации;
смотрите ЗАМЕЧАНИЯ касательно верхнего предела в Linux.
.SH ВОЗВРАЩАЕМОЕ ЗНАЧЕНИЕ
При успешном выполнении возвращается количество записанных байт.
При ошибке возвращается \-1, и \fIerrno\fP устанавливается
для указания причины ошибки.
.PP
Заметьте, что успешный
.BR write ()
может передать меньше, чем
.I count
байт.
Такие частичные записи могут происходить по различным причинам;
например, из-за недостаточного места на дисковом устройстве
для записи всех запрошенных байт, или потому что заблокированный
.BR write ()
в сокет, канал или подобное был прерван обработчиком сигнала
после передачи некоторой части, но до передачи всех
запрошенных байт.
В случае частичной записи, вызывающая сторона может сделать ещё один
.BR write ()
для передачи оставшихся байт.
Последующий вызов либо передаст дополнительные байты, либо
может привести к ошибке (например, если диск теперь заполнен).
.PP
Если \fIcount\fP равно нулю и
.I fd
ссылается на обычный файл, то
.BR write ()
может вернуть статус ошибки, если обнаружена одна из ошибок, перечисленных ниже.
Если ошибок не обнаружено или проверка на ошибки не выполняется,
будет возвращён 0 без каких-либо других эффектов.
Если
\fIcount\fP равно нулю и
.I fd
ссылается на файл, не являющийся обычным,
результаты не определены.
.SH ОШИБКИ
.TP
.B EAGAIN
Файловый дескриптор
.I fd
ссылается на файл, отличный от сокета, и помечен как неблокирующий
.RB ( O_NONBLOCK ),
а запись заблокировалась бы.
См.
.BR open (2)
для получения дальнейших сведений о флаге
.BR O_NONBLOCK .
.TP
.BR EAGAIN " или " EWOULDBLOCK
.\" Actually EAGAIN on Linux
Файловый дескриптор
.I fd
ссылается на сокет и помечен как неблокирующий
.RB ( O_NONBLOCK ),
а запись заблокировалась бы.
POSIX.1-2001 допускает возврат любой из этих ошибок в данном случае,
и не требует, чтобы эти константы имели одинаковое значение,
поэтому переносимое приложение должно проверять оба варианта.
.TP
.B EBADF
.I fd
не является допустимым файловым дескриптором или не открыт на запись.
.TP
.B EDESTADDRREQ
.I fd
ссылается на датаграммный сокет, для которого адрес узла не был установлен с помощью
.BR connect (2).
.TP
.B EDQUOT
Квота пользователя на дисковые блоки в файловой системе, содержащей файл,
на который ссылается
.I fd
исчерпана.
.TP
.B EFAULT
.I buf
находится за пределами доступного адресного пространства.
.TP
.B EFBIG
Была предпринята попытка записи в файл, превышающую определяемый реализацией
максимальный размер файла или ограничение на размер файла процесса,
или запись в позицию за пределы максимально допустимого смещения.
.TP
.B EINTR
Вызов был прерван сигналом до того, как были записаны какие-либо данные; см.
.BR signal (7).
.TP
.B EINVAL
.I fd
привязан к объекту, который не подходит для записи;
или файл был открыт с флагом
.B O_DIRECT,
и либо адрес, указанный в
.IR buf ,
значение, указанное в
.IR count ,
или смещение файла не выровнены должным образом.
.TP
.B EIO
Произошла низкоуровневая ошибка ввода-вывода при изменении inode.
Эта ошибка может относиться к обратной записи данных, записанных ранее
.BR write (),
который мог быть выполнен для другого файлового дескриптора того же файла.
Начиная с Linux 4.13, ошибки обратной записи сопровождаются
обещанием, что они
.I могут
быть сообщены последующими
.BR write ()
и
.I будут
сообщены последующим
.BR fsync (2)
(независимо от того, были ли они также сообщены
.BR write ()).
.\" commit 088737f44bbf6378745f5b57b035e57ee3dc4750
Альтернативной причиной
.B EIO
в сетевых файловых системах является ситуация, когда на файловом дескрипторе
была установлена рекомендательная блокировка, и эта блокировка была потеряна.
См. раздел
.I "Потерянные блокировки"
в
.BR fcntl (2)
для получения дополнительных сведений.
.TP
.B ENOSPC
Устройство, содержащее файл, на который ссылается
.I fd
не имеет места для данных.
.TP
.B EPERM
Операция была предотвращена файловой печатью; см.
.BR fcntl (2).
.TP
.B EPIPE
.I fd
подключён к каналу или сокету, конец чтения которого закрыт.
Когда это происходит, пишущий процесс также получит сигнал
.B SIGPIPE .
(Таким образом, возвращаемое значение записи видно только в том случае, если программа
перехватывает, блокирует или игнорирует этот сигнал.)
.PP
Могут возникать и другие ошибки, в зависимости от объекта, подключённого к
.IR fd .
.SH СООТВЕТСТВИЕ СТАНДАРТАМ
SVr4, 4.3BSD, POSIX.1-2001.
.\" SVr4 documents additional error
.\" conditions EDEADLK, ENOLCK, ENOLNK, ENOSR, ENXIO, or ERANGE.
.PP
В SVr4 запись может быть прервана и вернуть
.B EINTR
в любой момент,
а не только до записи каких-либо данных.
.SH ЗАМЕЧАНИЯ
Типы
.I size_t
и
.I ssize_t
являются, соответственно,
беззнаковым и знаковым целочисленными типами данных, определёнными POSIX.1.
.PP
Успешный возврат из
.BR write ()
не даёт никакой гарантии, что данные были записаны на диск.
В некоторых файловых системах, включая NFS, он даже не гарантирует,
что место для данных было успешно зарезервировано.
В этом случае
некоторые ошибки могут быть отложены до будущего
.BR write (),
.BR fsync (2),
или даже
.BR close (2).
Единственный способ быть уверенным — вызвать
.BR fsync (2)
после того, как вы закончили запись всех данных.
.PP
Если
.BR write ()
прерывается обработчиком сигнала до того, как записаны какие-либо байты,
то вызов завершается с ошибкой
.BR EINTR ;
если он прерван после того, как записан хотя бы один байт,
вызов завершается успешно и возвращает количество записанных байт.
.PP
В Linux,
.BR write ()
(и подобные системные вызовы) передают не более
0x7ffff000 (2 147 479 552) байт,
возвращая количество фактически переданных байт.
.\" commit e28cc71572da38a5a12c1cfe4d7032017adccf69
(Это верно как для 32-битных, так и для 64-битных систем.)
.PP
Возврат ошибки при выполнении
.BR write ()
с использованием прямого ввода-вывода не означает, что
вся запись завершилась неудачей. Часть данных может быть записана,
и данные по смещению файла, для которого
.BR write ()
был предпринят, следует считать несогласованными.
.SH ДЕФЕКТЫ
В соответствии с POSIX.1-2008/SUSv4, раздел XSI 2.9.7
("Взаимодействия потоков с операциями над обычными файлами"):
.PP
.RS 4
Все следующие функции должны быть атомарными по отношению
друг к другу в эффектах, указанных в POSIX.1-2008, когда они
работают с обычными файлами или символическими ссылками: ...
.RE
.PP
Среди API, перечисленных далее, находятся
.BR write ()
и
.BR writev (2).
И среди эффектов, которые должны быть атомарными для потоков (и процессов),
находятся обновления смещения файла.
Однако в Linux до версии 3.14
это было не так: если два процесса, которые разделяют
открытое описание файла (см.
.BR open (2))
выполняют
.BR write ()
(или
.BR writev (2))
одновременно, то операции ввода-вывода не были атомарными
в отношении обновления смещения файла,
в результате чего блоки данных, выводимых двумя процессами,
могли (неправильно) перекрываться.
Эта проблема была исправлена в Linux 3.14.
.\" http://thread.gmane.org/gmane.linux.kernel/1649458
.\"    From: Michael Kerrisk (man-pages <mtk.manpages <at> gmail.com>
.\"    Subject: Update of file offset on write() etc. is non-atomic with I/O
.\"    Date: 2014-02-17 15:41:37 GMT
.\"    Newsgroups: gmane.linux.kernel, gmane.linux.file-systems
.\" commit 9c225f2655e36a470c4f58dbbc99244c5fc7f2d4
.\"    Author: Linus Torvalds <torvalds@linux-foundation.org>
.\"    Date:   Mon Mar 3 09:36:58 2014 -0800
.\"
.\"        vfs: atomic f_pos accesses as per POSIX
.SH СМ. ТАКЖЕ
.BR close (2),
.BR fcntl (2),
.BR fsync (2),
.BR ioctl (2),
.BR lseek (2),
.BR open (2),
.BR pwrite (2),
.BR read (2),
.BR select (2),
.BR writev (2),
.BR fwrite (3)
.SH КОЛОФОН
Эта страница является частью проекта Linux
.I man-pages
версии 5.10.
Описание проекта,
информацию о сообщении об ошибках
и последнюю версию этой страницы
можно найти по адресу
\%https://www.kernel.org/doc/man\-pages/.
