.TH PERROR 3 2020-11-01 "" "Linux Programmer's Manual"
.SH ИМЯ
perror \- печатает сообщение об ошибке системы
.SH СИНТАКСИС
.B #include <stdio.h>
.PP
.BI "void perror(const char *" s );
.B
#include <errno.h>
.PP
.BI "const char * const " sys_errlist [];
.br
.BI "int " sys_nerr ;
.br
.BI "int " errno ";       \fR/* Not really declared this way; see errno(3) */"
.PP
.RS -4
Feature Test Macro Requirements for glibc (see
.BR feature_test_macros (7)):
.RE
.PP
.IR sys_errlist ,
.IR sys_nerr :
    From glibc 2.19 to 2.31:
        _DEFAULT_SOURCE
    Glibc 2.19 and earlier:
        _BSD_SOURCE
.SH ОПИСАНИЕ
Функция
.BR perror ()
выводит сообщение об ошибке на стандартный поток ошибок, описывающее последнюю ошибку, возникшую во время вызова системной или библиотечной функции.
.PP
Сначала (если
.I s
не равен NULL и
.I *s
не является нулевым байтом (\(aq\e0\(aq)), строка аргумента
.I s
печатается, за ней следует двоеточие и пробел.
Затем выводится сообщение об ошибке, соответствующее текущему значению
.I errno
и добавляется перевод строки.
.PP
Чтобы это было максимально полезно, строка аргумента должна содержать имя функции, которая вызвала ошибку.
.PP
Глобальный список ошибок
.IR sys_errlist "[],"
который индексируется значением
.IR errno ,
можно использовать для получения сообщения об ошибке без перевода строки.
Наибольший номер сообщения, приведённый в таблице, равен
.IR sys_nerr "\-1."
Будьте осторожны при прямом доступе к этому списку, потому что новые значения ошибок
могут ещё не быть добавлены в
.IR sys_errlist "[]."
Использование
.IR sys_errlist "[]"
в настоящее время устарело; вместо этого следует использовать
.BR strerror (3)
. PP
Когда системный вызов завершается с ошибкой, он обычно возвращает \-1 и устанавливает переменную
.I errno
в значение, описывающее, что пошло не так.
(Эти значения можно найти в
.IR <errno.h> .)
Многие функции библиотек поступают аналогично.
Функция
.BR perror ()
служит для преобразования этого кода ошибки в форму, понятную человеку.
Обратите внимание, что
.I errno
не определён после успешного вызова системной функции или вызова функции библиотеки:
этот вызов может изменить эту переменную, даже если он завершится успешно, например потому что внутри использовалась другая функция библиотеки, которая неудачно завершилась.
Таким образом, если вызываемая ошибка не сопровождается немедленным вызовом
.BR perror (),
значение
.I errno
следует сохранить.
.SH ВЕРСИИ
С версии glibc 2.32 объявления
.I sys_errlist
и
.I sys_nerr
больше не выводятся через
.IR <stdio.h> .
.SH АТРИБУТЫ
Для объяснения терминов, используемых в этом разделе, см. 
.BR attributes (7).
.TS
allbox;
lb lb lb
l  l  l.
Interface       Attribute       Value
T{
.BR perror ()
T}      Потокобезопасность   MT-Safe race:stderr
.TE
.sp 1
.SH СООТВЕТСТВИЕ
.BR perror (),
.IR errno :
POSIX.1-2001, POSIX.1-2008, C89, C99, 4.3BSD.
.PP
Внешние переменные
.I sys_nerr
и
.I sys_errlist
происходят из BSD, но не определены в POSIX.1.
.PP
.The externals
.I sys_nerr
и
.I sys_errlist
определены в glibc, но в
.IR <stdio.h> .
.\" and only when _BSD_SOURCE is defined.
.\" When
.\" .B _GNU_SOURCE
.\" is defined, the symbols
.\" .I _sys_nerr
.\" и
.\" .I _sys_errlist
.\" are provided.
.SH ПРИМЕЧАНИЯ
.The externals
.I sys_nerr
и
.I sys_errlist
определены в glibc, но в
.IR <stdio.h> .
.\" и только когда определён _BSD_SOURCE.
.\" Когда
.\" .B _GNU_SOURCE
.\" определяется, символы
.\" .I _sys_nerr
.\" и
.\" .I _sys_errlist
.\" предоставляются.
.SH СМ. ТАКЖЕ
.BR err (3),
.BR errno (3),
.BR error (3),
.BR strerror (3)
.SH КОЛОФОН
Эта страница является частью выпуска 5.10 проекта
.I man-pages
. Описание проекта, информация об сообщении об ошибках и последняя версия этой страницы
доступны по адресу
\%https://www.kernel.org/doc/man\-pages/.

